formbricks/formbricks

.env.example
The next configuration refers to two required values `process.env.TERMS_URL` and `process.env.PRIVACY_URL` that are currently missing from the example .env.example file that is copied during the local deployment instructions.
I have added sensible default values to this file which allows the build to complete.
=> Fixed missing required environment variables

lib/email.ts, next.config.js, pages/api/auth/[...nextauth].ts, pages/api/public/users/index.tsx, pages/auth/signup-without-verification-success.tsx, pages/auth/signup.tsx
- adds `canSendEmails` function which reads the SMTP config provided
- only send confirmation mail on signup when `canSendEmails` returns true
- conditionally route to verification requested page or to newly added "go to login" page.
Probably could also leave out the login step, but I felt like this is the better UX :)
=> Add default flow if SMTP data not provided

apps/web/Dockerfile
Fixes a build error with prisma on the [latest alpine 3.17](https://github.com/prisma/prisma/issues/16642#issuecomment-1347743938) in the snoopforms branch
=> fix(build): pin to alpine 3.16 (fixes prisma install error)

apps/formbricks-com/pages/docs/contributing/setup/index.mdx, apps/formbricks-com/pages/docs/self-hosting/deployment/index.mdx, apps/web/README.md
In the documentation, at some places, localhost URLs were started with https instead of http
=> FIX: localhost URLs fixed 

apps/web/app/s/[surveyId]/LinkSurvey.tsx
Fixes the increase of display count on preview surveys. It should only increase on live surveys.
- Visit preview survey and check that display count is not changing
- Visit live survey and check that it does change
=> fix: do not create a display if the survey is in preview mode

apps/web/pages/api/v1/environments/[environmentId]/surveys/[surveyId]/index.ts
The current ﻿`updatedAt` field's value is passed in the survey’s update API request, so the date remains the same as the ﻿`createdAt` date. As a result, even if many changes are made to the survey, an alert to delete the draft is shown when the Back button is clicked.
To reproduce the bug:
1. Create a new survey
2. Make a change
3. Save
4. Open the same survey
5. Click the Back Button
6. See the alert asking if you want to delete the draft
This PR fixes the issue by removing the ﻿`updatedAt` field from the request body, allowing Prisma to set the datetime correctly.
Follow the steps above. It shouldn't now show an alert described in point no 6.
- <s>I haven't read the [contributing guide](https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md)
- My code doesn't follow the …
=> Exclude updatedAt field in survey update

apps/web/app/environments/[environmentId]/surveys/[surveyId]/summary/SummaryMetadata.tsx, apps/web/components/preview/OpenTextQuestion.tsx, apps/web/lib/questions.ts
minor changes:
- add autoFocus to open text questions standalone (didnt add it to in-app because it might steal focus from what user currently is doing -> bad UX)
- Add default text content for open text question
- Update "Edit" button color to darkCTA
Yes
=> Add autoFocus to Free Text in Standalone Surveys

apps/web/app/api/csv-conversion/route.ts, apps/web/app/environments/[environmentId]/surveys/[surveyId]/responses/ResponseTimeline.tsx, apps/web/lib/csvConversion.ts, apps/web/lib/surveys/surveys.ts, apps/web/package.json, packages/lib/time.ts, pnpm-lock.yaml
=> Export to CSV

apps/web/components/preview/Modal.tsx, packages/js/package.json, packages/js/src/components/Modal.tsx
Close Icon not showing on mobile in formbricks-js
=> Close Icon not showing on mobile in formbricks-js

apps/formbricks-com/components/docs/Layout.tsx, apps/formbricks-com/components/shared/Navigation.tsx
Fixes #378
https://github.com/formbricks/formbricks/assets/69904519/2728b411-cd6a-4348-aa3b-cfaf8cb20b18
https://github.com/formbricks/formbricks/assets/69904519/8c29307d-59c5-4e00-a96d-dcb78f58e967
- Go to docs and scroll side nav to the bottom and click on any topic
=> fix: preserve docs nav scroll position

apps/web/app/environments/[environmentId]/surveys/[surveyId]/responses/SingleResponse.tsx
Deleted responses are no longer shown in frontend
=> Deleted responses are no longer shown in frontend

packages/lib/services/person.ts, packages/lib/services/response.ts, packages/types/v1/people.ts, packages/types/v1/responses.ts
Sends the `createdAt` and `updatedAt` of the user model in the response primarily in `getPerson()` and `getPeople()` methods and wherever else we deal with the type `TransformPersonOutput` and `ZResponse`
- Call the `getPerson()` method and log the output, you should see the relevant fields
=> Add Timestamps in User Model Response

.github/workflows/release-on-dockerhub.yml, apps/formbricks-com/pages/docs/self-hosting/deployment/index.mdx, apps/web/Dockerfile, docker/README.md, docker/docker-compose.yml
Whenever we tag a commit prefixed with "v", this actions gets triggered and builds the Formbricks docker image and pushes it to `formbricks/formbricks`.
For example, for a tag v1.0.0:
- We will push to the formbricks dockerhub an image as: 
- `formbricks/formbricks:1.0.0`
- `formbricks/formbricks:latest`
TODO:
- Pushed from gh actions from my fork to my dockerhub here: https://hub.docker.com/repository/docker/laalshaitaan/formbricks/tags?page=1&ordering=last_updated
- Tested by running this with the `formbricks/docker`'s docker-compose.yml
=> Ci/CD: Push Formbricks Image to Dockerhub on Release with GitHub Actions

apps/formbricks-com/pages/docs/self-hosting/deployment/index.mdx
The URL had a misplaced branch name in the cURL URL for formbricks quickstart local deployment method. That is now fixed in this PR!
=> Fix Docker Compose URL for cURL

apps/web/app/(app)/environments/[environmentId]/surveys/PreviewSurvey.tsx, apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/LogicEditor.tsx
- Introduce Restart Survey Button
- Restart also clears the progress made in the previous questions unlike the back button which stores it
- Uses the Hero Icon for the Restart Icon
- Truncate the logic edit field and hides the overflow for better UX on narrower screens
Due to padding issues and the small size of the button, I went ahead with the "minimal" variant as the other buttons were not looking great.
=> Introduce Restart Survey Button on Preview of Survey & Truncate Logic Values

apps/web/app/(app)/environments/[environmentId]/(actionsAndAttributes)/actions/ActionSettingsTab.tsx, apps/web/app/(app)/environments/[environmentId]/people/[personId]/HeadingSection.tsx
Adds loader and state management for the loaders in deletion of action and person!
It takes 20ish seconds to delete an action on prod:
- The modal closes immediately after button click and the action is still visible. Instead, add a loading state to the delete button and wait for the action to be deleted to close it.
Make sure the frontend does not display the action even though it was deleted.
Same is true for deleting a person
=> Add Loading State to Action Delete & Person Delete Buttons

apps/web/app/(app)/environments/[environmentId]/surveys/PreviewSurvey.tsx, apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/SurveyMenuBar.tsx
- Fixed padding and margins in the warning note in orange in tablet screens!
- Introduced padding in link type survey preview for tablet screens!
=> UI fixes in Survey Editor

apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/SummaryHeader.tsx, apps/web/components/shared/SurveyStatusDropdown.tsx
This PR fixes button descendent button error in survey page in both mobile and desktop view
Fixes #711
- Go to any survey page
=> fix: Button descendent button error

.gitpod.Dockerfile, .gitpod.yml, .gitpod/init.bash, .gitpod/setup-api.bash, .gitpod/setup-demo.bash, .gitpod/setup-web.bash, apps/demo/package.json, packages/database/package.json, turbo.json
Fixes #509 
- Adds Gitpod Scripts with Prebuilds scripts and by abstractions optimized to support turborepo tasks of Formbricks to start under 2 mins!
Added better DevX to open up already setup dev environment to get started Coding/Reviewing and Contributing!!
You can test it by clicking on the below "Open in Gitpod" button as it has prebuilds enabled at [Palanikannan1437:gitpod-integration](https://github.com/Palanikannan1437/formbricks/tree/gitpod-integration)
[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/#https://github.com/Palanikannan1437/formbricks/tree/gitpod-integration)
Installs `yq` and `turbo` globally before the workspace starts -> `.gitpod.Dockerfile` for starting upon a base custom image building on …
=> Initialized Gitpod tested scripts

apps/formbricks-com/pages/api/oss-friends/index.ts, packages/ui/components/editor/plugins/ToolbarPlugin.tsx
Fixes [624](https://linear.app/formbricks/issue/FOR-624/cta-question-link-ux-improvements)
Check CTA question link
=> fix: CTA question link UX

apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/SurveyMenuBar.tsx
When you set an invalid URL in the "Forward after survey completion" input field, the app breaks, this PR fixes it by putting a check and sending a toast when the URL is not a valid one!
=> Validate URL on Redirection to avoid breaking app

apps/formbricks-com/app/docs/self-hosting/docker/page.mdx, apps/formbricks-com/app/docs/self-hosting/from-source/page.mdx, apps/formbricks-com/app/docs/self-hosting/production/page.mdx
We faced quite a few queries about people trying to edit the `NEXT_PUBLIC_` and since they are configured at build-time, the changes are not reflected resulting in a bad UX! This PR adds a Note and a link to the **From Source** page to the other 2 deployment guides ie the Docker and the Single Script setup Guide.
=> Mention Editing Build-time Variables in deployment Guides

apps/formbricks-com/app/docs/api/api-key-setup/page.mdx, apps/formbricks-com/app/docs/api/overview/page.mdx, apps/formbricks-com/app/docs/api/responses/page.mdx, apps/formbricks-com/app/docs/api/surveys/page.mdx, apps/formbricks-com/components/docs/Navigation.tsx
Adds Missing Documentation for the 2 APIs:
- `/surveys`
- `/me`
- Renames User API to Management API
=> API documentation for Surveys & Profile

packages/lib/utils/array.ts
For in-app surveys, the multi-select question was throwing nullity error which on further debugging was found whenever it called the `symmetricDifference()` function! This PR adds an `|| []` check to eliminate runtime errors on empty array passing.
Fixes #759 
- Create an in-app survey with multi select question type
- On submitting, it would throw an error as per the main branch
- Now shift to the fix branch and try again, it should work!
=> fix: Array Nullity Check in JS packages

docker/docker-compose.yml, docker/production.sh
We now allow users to set custom SMTP email servers to configure email notifications and other services that we have to offer for the user!
Copy and run the new production.sh script and see your email notifications working!
=> Add Support for Email Services in Single Script Prod Setup

apps/formbricks-com/pages/learn/[slug].tsx
We now fetch and build the STRAPI learn pages only if the key exists thus preventing build failures
=> fix: landing page build issue due to strapi

apps/formbricks-com/app/docs/integrations/n8n/page.mdx
The n8n integrations page had note headings in white that used to limit it's accessibility in light mode! 
While debugging that, I also found out that the image widths were not defined accurately causing responsiveness issues! Both of these bugs have been handled in this PR.
=> fix: (docs) n8n page heading bug and responsiveness issues

apps/web/app/s/[surveyId]/LinkSurvey.tsx
link survey responses may fail when custom survey url is set
=> fix: link survey responses may fail when custom survey url is set

apps/web/app/(app)/environments/[environmentId]/surveys/SurveyDropDownMenu.tsx, apps/web/app/(app)/environments/[environmentId]/surveys/SurveyList.tsx, apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/responses/ResponsePage.tsx, apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/responses/page.tsx, apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/summary/LinkModalButton.tsx, apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/summary/LinkSurveyModal.tsx, apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/summary/SuccessMessage.tsx, apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/summary/SummaryPage.tsx, apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/summary/page.tsx, apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/SummaryHeader.tsx, apps/web/env.mjs
1. We are importing the `SURVEY_BASE_URL` from the `constants.ts` which reads the `NEXT_PUBLIC_SURVEY_BASE_URL` and if it does not exist, it sets it to the `WEBAPP_URL/s/`.
2. Now, the WEBAPP_URL is determined by:
```
export const WEBAPP_URL = process.env.WEBAPP_URL ||  process.env.NEXT_PUBLIC_WEBAPP_URL || VERCEL_URL || RAILWAY_STATIC_URL ||  HEROKU_URL || RENDER_URL || "http://localhost:3000/";
```
3. And since the import is on the **CLIENT side**, it cannot read the WEBAPP_URL from the env vars (does **not have the NEXT_PUBLIC_ prefix**) hence goes to the backup **localhost:3000**!
This PR fixes that by parsing and passing the surveyBaseUrl as a prop to all the client side components!
Fixes #799 
Set a WEBAPP_URL other than localhost:3000 and it should reflect the same when sharing the …
=> fix: webapp_url env var not reflected client side

packages/js/src/lib/config.ts, packages/js/src/lib/init.ts, packages/js/src/lib/person.ts
After calling logout() sync stops.
Fixes [1311](https://linear.app/formbricks/issue/FOR-1311/stop-sync-in-formbricks-js-when-logout-is-called)
Open demo app
Call logout()
Check for logs into console (sync shouldn't occur after logout is called)
=> fix: Stop Sync after logout()

apps/web/app/api/v1/js/people/[personId]/set-attribute/route.ts, apps/web/app/api/v1/js/people/[personId]/set-user-id/route.ts, apps/web/app/api/v1/js/surveys.ts, apps/web/app/api/v1/js/sync/route.ts, packages/database/src/client.ts, packages/lib/services/actionClass.ts, packages/lib/services/attributeClass.ts, packages/lib/services/displays.ts, packages/lib/services/environment.ts, packages/lib/services/person.ts, packages/lib/services/product.ts, packages/lib/services/session.ts, packages/types/v1/attributeClasses.ts
enable caching in all js endpoints to reduce database calls
=> chore: enable caching in all js endpoints to reduce database calls

apps/web/app/api/v1/js/actions/route.ts, packages/database/src/client.ts, packages/lib/services/actionClass.ts, packages/lib/services/actions.ts, packages/lib/services/session.ts, turbo.json
=> fix: caching in actions endpoint

packages/js/src/lib/automaticActions.ts, packages/js/src/lib/eventListeners.ts, packages/js/src/lib/init.ts, packages/js/src/lib/noCodeEvents.ts, packages/js/src/lib/sync.ts
We are still facing a lot of sync calls to Formbricks. In this PR we add additional checks to make sure event listeners are only added once in formbricks-js.
- Test all formbricks-js functionality using the Formbricks Demo app
=> fix: make sure event listeners are only added once in formbricks-js

apps/formbricks-com/pages/formtribe/index.tsx
formtribe page should only be shown in light mode
=> fix: formtribe page should only be shown in light mode

apps/web/app/(app)/environments/[environmentId]/(actionsAndAttributes)/actions/AddNoCodeActionModal.tsx
Passes environmnetId on action creation modal so that the validation does not fail at the server side
Currently a bug in prod
=> fix: pass envId on action creation

apps/web/app/(app)/environments/[environmentId]/settings/profile/DeleteAccount.tsx, apps/web/app/(app)/environments/[environmentId]/settings/profile/EditName.tsx, apps/web/app/(app)/environments/[environmentId]/settings/profile/actions.ts, apps/web/app/(app)/environments/[environmentId]/settings/profile/page.tsx, apps/web/app/(app)/onboarding/actions.ts, apps/web/app/(app)/onboarding/components/Objective.tsx, apps/web/app/(app)/onboarding/components/Onboarding.tsx, apps/web/app/(app)/onboarding/components/Role.tsx, packages/lib/services/profile.ts
Edit and Delete is now done for the user by fetching from the server session rather than a client side passed parameter.
Also a couple of services did not have the response selection hence were returning passwords/other non reqd user fields. That has also been tackled in this.
=> fix: Authorization for Profile Actions & Limit Data exposure

packages/lib/actionClass/auth.ts, packages/lib/actionClass/service.ts, packages/lib/apiKey/auth.ts, packages/lib/constants.ts, packages/lib/environment/auth.ts, packages/lib/response/auth.ts, packages/lib/services/attributeClass.ts, packages/lib/services/environment.ts, packages/lib/services/person.ts, packages/lib/services/product.ts, packages/lib/services/profile.ts, packages/lib/services/team.ts, packages/lib/tag/auth.ts, packages/lib/tagOnResponse/auth.ts
In this PR i moved the revalidation interval value that was hardcoded in multiple services now into a constant
- Did a general work through of the application to make sure nothing breaks
Not sure I should do more specific tests
=> feat: move revalidation interval to a constant

apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/summary/page.tsx
generate single surveys from the lib only when it is enabled to avoid app crashing if the env var is not set
=> fix: generate single surveys only if enabled

apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/summary/components/LinkSingleUseSurveyModal.tsx
Fixes the preview link. 
Fixes #935 
- Create a single use survey and try to preview.
=> fix: Single Use Link Preview is not correctly functioning

apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/SurveyMenuBar.tsx, apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/Validation.ts
Fixes Survey Validation bug bby redefining validation set per question as 2 questions can have the "if submitted, end survey' condition. This checks for conflicting logics per question as it should.
Also removes a not-reqd console log message.
Create/Save/Publish any templated survey and it should work! That's how I tested as well
=> fix: survey validation bug

.github/workflows/pr.yml, apps/web/app/api/cron/weekly_summary/route.ts, apps/web/app/api/cron/weekly_summary/types.ts, apps/web/app/api/v1/client/displays/[displayId]/route.ts, apps/web/app/api/v1/client/displays/route.ts, packages/lib/surveyState.ts, packages/types/v1/displays.ts
The web build was failing because of the display status now being an optional field. This PR fixes it by
1. we just needed the displays count in the weekly summary so instead of the status, we now do that through ID field
2. In the lib/surveyState, the TResponseUpdate will not have a displayId field now so removed that as well from this constructor
3. Removes commented method
=> fix: build error due to survey status becoming optional

apps/web/app/(app)/environments/[environmentId]/integrations/google-sheets/actions.ts, packages/lib/integration/auth.ts, packages/lib/integration/service.ts
Before this, we had a vulnerability that any user could delete any integration of another user. Now, we do authorization with the base environment of the integration to make sure the user is authorized to perform the action.
Try passing another integrationId and see if the delete works.
=> feat: authorization on google integrations

apps/web/app/(app)/environments/[environmentId]/integrations/page.tsx
Fix `statusText` mismatch; changed `webhooks` card `statusText` from `zaps` to `Webhooks` and `Zapier` card `statusText` from `zaps` to `Zaps` in Integrations page
#1066 
Tested typo change on localhost
=> fix: statusText mismatch in webhook integrations

.env.example, apps/formbricks-com/app/docs/contributing/setup/page.mdx
This PR adds the step to generate and set the value of the new required environment variable ENCRYPTION_KEY in the Contributing Guide
=> feat: add docs for setting ENCRYPTION_KEY in .env in contributing guide

apps/web/app/(app)/environments/[environmentId]/(actionsAndAttributes)/attributes/components/AttributeSettingsTab.tsx
It fixes  page not found error, when clicking on attributes settings tab's "Read Docs" button.
Fixes #1217 
video link : https://www.loom.com/share/32ca5c98f8f5455ab981340e6b3a9194?sid=5cebdad1-9033-4f5f-a15e-38a6bac718c2
Watch out loom video.
- Test A
- Test B
=> fix: attribute-settings-tab-button-link

docker/docker-compose.yml
The volume currently mounted had an invalid syntax resulting in docker compose not working locally. This fixes it by passing an absolute file path for file uploads
- Test A
- Test B
=> fix: docker compose volume only takes absolute paths

apps/web/app/(app)/environments/[environmentId]/surveys/templates/templates.ts
Now, In every template i made welcome card not being active by default. So, whenever user clicked on survey he will hit the 1st question in the survey. In othercase, if he wants welcome card to be active he can do that by changing the default state(false) to true
#1336
https://github.com/formbricks/formbricks/assets/113505439/1675b4ab-81af-4f27-89b8-7ddbbd092e4f
=> fix: Welcome card not being active by default in every template

packages/types/responses.ts
We only had the metadata fields optional for creation and updation! Whenever we fetched a response, if the response did not have a metadata source/url, it'd crash since the zod validation failed!
This makes sure that the fields are optional in reading as well!
=> fix: make metadata internal fields optionality uniform in response object

apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/summary/components/SummaryDropOffs.tsx
While testing, I just found out that if a response object is created but no questions are answered, the summary drop off fails since it is unable to find a question which crashes the client side! This PR handles the case for it!
=> fix: handle display with no response data in per question drop off

apps/web/middleware.ts
Rate Limiting previously was based on the `IS_FORMBRICKS_CLOUD` env var. It is now shifted to use the `NODE_ENV` and rate limit now only comes to place when it is set to production. Else, is disabled.
=> fix: rate limit is now enabled on node prod envs only

apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/summary/components/OpenTextSummary.tsx, apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/summary/components/SummaryList.tsx, apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/summary/components/SummaryPage.tsx, apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/summary/page.tsx, packages/lib/constants.ts
Loooot of open text question responses would make the response summary page really long & difficult to follow through. This PR introduces a "Show more" button that limits to 10 responses of the type at a time!
Attaching a video of the solution where the OPEN_TEXT_RESPONSES_PER_PAGE is set to 4 for testing purposes:
https://github.com/formbricks/formbricks/assets/55556994/2114ea39-188f-44fb-8c81-d5e2f3d23a0c
Have a loot of responses in an open text question type then view the summary page for the survey
=> feat: client side pagination in open text questions in responses summary

apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/responses/components/ResponsePage.tsx, apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/responses/components/ResponseTimeline.tsx, apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/responses/page.tsx, packages/lib/constants.ts
If you have a lot of responses, as of now, the page would really swamp up with all of them with a super tiny nav scroll making it extremely difficult from a UX perspective.
This PR limits to 10 responses and then as soon as the user reaches the second last response of the 10, loads the next 10 and so on. They are, as before, sorted in descending order as per date-time!
Attached video with an example with 3 Responses at a time (for testing purposes):
https://github.com/formbricks/formbricks/assets/55556994/974c9836-57a5-4816-b479-56cd9c27ef6d
Have more than 10 responses on a survey? Open the summary and then the responses tab to see this in effect!
=> feat: lazy loading and endless scrolling for responses page

packages/ui/BillingSlider/index.tsx
The slider currently exceeds the card and the page 😓 when the current count exceeds the max value! This PR limits the same to max 93% of the slider so that the text is also visible and it stays under the card
=> fix: overloading slider on exceeding max limits in pricing tier

apps/web/middleware.ts
Disables the blocking of a request if it does not have an IP address associated with it. This is possible when running it in docker and accessing it from the same network
Fixes #1533
Run `docker compose --env /dev/null up` to test it with a newly built image
=> fix: avoid blocking the request if it does not have an associated ip

packages/surveys/src/components/OpenTextQuestion.tsx
Fixes a bug where input fields are filled automatically for open text questions when long answer is off
https://github.com/formbricks/formbricks/assets/67850763/43d3f77d-fff9-4f05-a47f-ea89ddc17caa
Create consecutive short answer open text questions
Fill one question
Check others
=> fix: openText issue

apps/formbricks-com/pages/pricing.tsx, apps/web/app/(app)/environments/[environmentId]/settings/billing/components/PricingTable.tsx
=> fix: make pricing pages consistent

apps/web/app/(app)/environments/[environmentId]/settings/billing/actions.ts, apps/web/app/(app)/environments/[environmentId]/settings/billing/components/PricingTable.tsx, apps/web/app/(app)/environments/[environmentId]/settings/billing/unlimited/page.tsx, packages/ee/billing/handlers/checkoutSessionCompleted.ts, packages/ee/billing/handlers/subscriptionCreatedOrUpdated.ts, packages/ee/billing/lib/constants.ts
Introduce new plan for the unlimited offering and update accordingly  in Stripe
=> feat:  $199 pricing model for unlimited plans

apps/web/app/(app)/environments/[environmentId]/integrations/actions.ts, apps/web/app/(app)/environments/[environmentId]/integrations/airtable/actions.ts, apps/web/app/(app)/environments/[environmentId]/integrations/airtable/components/AddIntegrationModal.tsx, apps/web/app/(app)/environments/[environmentId]/integrations/airtable/components/AirtableWrapper.tsx, apps/web/app/(app)/environments/[environmentId]/integrations/airtable/components/Home.tsx, apps/web/app/(app)/environments/[environmentId]/integrations/google-sheets/actions.ts, apps/web/app/(app)/environments/[environmentId]/integrations/google-sheets/components/AddIntegrationModal.tsx, apps/web/app/(app)/environments/[environmentId]/integrations/google-sheets/components/Home.tsx
Fixes [1465](https://linear.app/formbricks/issue/FOR-1465/add-authorization-to-airtable-actions)
- Test A
- Test B
=> refactor: added authorization to airtable integration and create a common actions file

packages/surveys/src/components/ProgressBar.tsx
=> fix: editor crashing

apps/formbricks-com/app/docs/api/management/surveys/page.mdx
Fixes #1555
verify the update in https://formbricks.com/docs/api/management/surveys#create-survey
Create survey section curl command should contain POST instead of DELETE
=> fix: fixed URL example for "Create Survey" API endpoint is wrong #1555

apps/formbricks-com/app/docs/getting-started/framework-guides/page.mdx, apps/formbricks-com/components/home/SetupTabs.tsx, apps/web/app/(app)/environments/[environmentId]/settings/setup/components/SetupInstructions.tsx, packages/js/index.html
Update js package version to 1.1.4 from 1.1.2
=> fix: update setup checklists with latest js package version

apps/web/app/(app)/environments/[environmentId]/layout.tsx, apps/web/app/(app)/environments/[environmentId]/settings/profile/page.tsx
Sentry runtime errors included these 2 pages where the id of an undefined object was being fetched resulting in a runtime error. This PR handles them both.
=> fix: user existence checks in session object

apps/web/app/(app)/onboarding/page.tsx
Sentry reported 46 instances of users getting a Session not Found error specifically on the Onboarding page that we have. We currently just show the user an error without any CTA. This case is possible for when a token expires or the session JWT is not valid anymore. To tackle this, we now redirect them back to the login page so that a new token can be generated and then they will be taken to the page they should be as per the normal flow.
=> fix: redirect user if they visit onboarding page without auth

packages/js/package.json
Fixes type resolution when using the bundler moduleResolution TypeScript option.
- Create TypeScript project and install @formbricks/js
- Set compilerOptions.moduleResolution to bundler in your tsconfig.json file
- Observe that types are not resolved correctly
- Make the change detailed in this PR, observe that this PR fixes the issue
=> fix: add types to exports for @formbricks/js

apps/web/app/api/v1/client/responses/route.ts
Throws an error if no survey is found and also typecastes the variable. Avoid the current runtime errors thrown in Sentry
=> fix: handle invalid surveyId from api endpoint

.github/workflows/cron-reportUsageToStripe.yml, apps/web/app/api/cron/report-usage/route.ts
Fixes GitHub Action to use env vars as set (taking inspiration from the weekly summary cron job)
- Test A
- Test B
=> fix: github action that reports stripe usage

apps/web/app/(app)/billing-confirmation/page.tsx
Sentry reported a few runtime errors when people visited the `/billing-confirmation` page because it used the `searchParams` for the page, it could not be rendered the SSG way hence causing error. This PR now forces it to use the SSR method hence hopefully not throwing any such error.
=> fix: opt billing page forcefully out of static generation

apps/web/app/(app)/onboarding/components/Objective.tsx, apps/web/app/(app)/onboarding/components/Onboarding.tsx, apps/web/app/(app)/onboarding/components/Role.tsx
fix: infinite loop in onboarding
=> fix: infinite loop in onboarding

apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/components/SurveyEditor.tsx
Fixes [1488](https://linear.app/formbricks/issue/FOR-1488/bug-flashing-of-error-component-before-survey-editor-opens)
In survey editor we were rendering an ErrorComponent if localSurvey is not set (which is the case on initial load), so instead of showing that error , we now show our loading state
Refresh survey editor
=> fix: Error screen on survey Editor refresh

packages/surveys/src/components/wrappers/Modal.tsx
This PR improves the a11y of the survey modal close ("X") button.
before:
after:
- build pixel and check close button of in app survey
=> fix: improve a11y of survey modal close button

apps/web/app/s/[surveyId]/page.tsx
Validates param string before fetching a survey for it to reduce error logging in app as well as sentry
=> fix: validate string before fetching survey

apps/formbricks-com/components/shared/BestPracticeNavigation.tsx
The Best Practices cards have random uneven sizes on smaller screens. I found a nice way to make all elements the height of the highest one in the component.
Before:
After:
It's just a small CSS improvement. No testing required.
=> style: tiny BestPractice component styling fix

apps/web/app/api/v1/client/[environmentId]/in-app/sync/[userId]/route.ts, apps/web/app/api/v1/client/[environmentId]/in-app/sync/route.ts
add response limitations from cloud plan to sync endpoint. Don't send surveys to the client if the response limit is reached for this month.
=> fix: add response limitations to sync endpoint

.github/workflows/playwright.yml, apps/web/playwright/js.spec.ts, apps/web/playwright/utils/helper.ts, apps/web/playwright/utils/mock.ts, packages/js/index.html
E2E tests for
- Survey Creation
- Display Creation through JS Package
- Response Submission through JS Package
- Verification of the above 2 from the Admin Portal
Also adds a step in CI to build the local JS package
Also uses the native HTML file to keep things light in the CI!
- Test A
- Test B
=> feat: setup formbricks/js e2e tests

apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/components/SurveyMenuBar.tsx
Fixes [1578](https://linear.app/formbricks/issue/FOR-1578/enable-save-button-despite-missing-survey-trigger-for-in-app-surveys)
Enable save button for empty triggers (for draft survey)
Test darft survey with empty triggers
=> fix: enable save button for survey with empty triggers

packages/lib/invite/service.ts
Currently, if the email delivery fails, we do not revalidate the cache which leads to the invite list not getting update (due to cache). So the user is unable to see if they have invited a person or not.
This PR changes that by revalidating the cache irrespective of the email status since invites can also be accepted via links present in the invite list~
- Test A
- Test B
=> fix: revalidate invite cache even if email delivery fails

packages/surveys/src/components/general/Smileys.tsx, packages/surveys/src/components/questions/RatingQuestion.tsx
improve UI of Rating Quesiton mostly by sizing and filling stars:
=> fix: tweak rating UI after fix

apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/components/EditWelcomeCard.tsx, packages/ui/FileInput/index.tsx
Logos looked pretty bad on the welcome cards. 
Introduced object fit prop so it can be changed to `contain` if needed:
vs
=> fix: object fit for logo on welcome card

apps/web/app/(auth)/auth/verification-requested/components/RequestVerificationEmail.tsx
Fixes [1620](https://linear.app/formbricks/issue/FOR-1620/open-verify-email-in-same-tab)
1. Create a new account without using any provider
2. You now arrive on verify email page
3. Open verification mail and click on confirm mail
4. Check the previously opened tab
=> fix: reload Verify email page

.github/PULL_REQUEST_TEMPLATE.md, apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/layout.tsx
fix: get response count in analysis layout more efficiently
=> fix: get response count in analysis layout more efficiently

apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/components/StylingCard.tsx, packages/surveys/src/components/general/Survey.tsx, packages/types/surveys.ts
Fixes [1632](https://linear.app/formbricks/issue/FOR-1632/hide-progres-bar-setting)
https://github.com/formbricks/formbricks/assets/67850763/55e7aa0b-eca7-4d62-b021-e007dfb503fa
Go to settings > styling
Toggle `Hide Progress Bar`
=> feat: hide progress bar toggle

apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/components/QuestionCard.tsx
Now we don't automatically update the next button label for last question
Also if we now change next button label for last question, it wont get change next button label for other questions
Fixes [1705](https://linear.app/formbricks/issue/FOR-1705/add-logic-step-to-button-text-tweak)
Change next button label for last question
=> fix: next button tweak

packages/lib/constants.ts
Increases the client side API (including response submissions) rate limits to 100 per 5 mins! 🤞🏼
=> feat: increase rate limit for client api endpoints

apps/formbricks-com/app/docs/contributing/setup/page.mdx, apps/formbricks-com/app/docs/self-hosting/license/page.mdx, apps/formbricks-com/app/docs/self-hosting/production/page.mdx, apps/formbricks-com/components/docs/Navigation.tsx, apps/web/app/s/[surveyId]/components/VerifyEmail.tsx, packages/tailwind-config/tailwind.config.js
1. add self-hosting license form
2. make verify email work with colored BGs (and testing cards look 😎 )
=> docs: add self-hosting license form

apps/web/app/(app)/environments/[environmentId]/components/HowToAddPeopleButton.tsx, apps/web/app/(app)/environments/[environmentId]/people/loading.tsx, apps/web/app/(app)/environments/[environmentId]/people/page.tsx
Add new button on People Page where users can link to external docs to read more about procedure how to add people in the view screen
Fixes: [(issue)](https://github.com/formbricks/formbricks/issues/1900)
=> feat: Add "How to add people" to People View

apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/summary/lib/emailTemplate.tsx, packages/ui/RatingSmiley/index.tsx
Fixes [1725](https://linear.app/formbricks/issue/FOR-1725/bug-smileys-in-email-embed-are-all-the-same)
Before:
After:
=> fix: Embed in an Email preview

apps/formbricks-com/components/docs/Navigation.tsx, apps/web/app/(app)/environments/[environmentId]/settings/billing/components/PricingTable.tsx, packages/ui/PricingCard/index.tsx
fixes https://github.com/formbricks/formbricks/issues/1917
=> fix: Add response api link to docs navbar

packages/surveys/src/components/general/Survey.tsx
Seems like we didnt have a logic to handle logic jumps when other option is selected
In logic object we check for `Other` as response value  in order to execute the jump logic but response value is the actual answer of that Other option
Fixes [1735](https://linear.app/formbricks/issue/FOR-1735/bug-logic-jump-doesnt-work-for-other-option)
Add some logic jumps to other option
=> fix: logic jump for other option

apps/web/app/s/[surveyId]/components/LinkSurvey.tsx, packages/api/src/api/client/storage.ts, packages/surveys/src/components/general/FileInput.tsx
=> fix: error handling for file upload

apps/formbricks-com/pages/community/Roadmap.tsx, apps/formbricks-com/pages/community/index.tsx
1. added contributor images:
2. updated content
3. added CTA at bottom
=> chore: update and tweak community page

apps/web/app/(app)/environments/[environmentId]/surveys/templates/TemplateList.tsx
Apparently Next.js is not comfortable having a `button` tag wrapping your `div`, sections, etc., so it will yell "Hydration failed because the initial UI does not match what was rendered on the server".
Fixes [1694](https://linear.app/formbricks/issue/FOR-1694/bug-template-layout-breaks-app)
This error occurs when user has completed onboarding and have selected an objective (not "other")
Then when on survey stater, shift reload the page
=> fix: template breaking issue

apps/web/playwright/action.spec.ts, apps/web/playwright/js.spec.ts, apps/web/playwright/survey.spec.ts, apps/web/playwright/team.spec.ts
Fixes flaky e2e tests, implements strategies like waiting for response and so on
- Run e2e tests
=> fix: e2e flakyness

apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/summary/components/ShareSurveyResults.tsx, apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/components/ResultsShareButton.tsx
the dropdown is now responsive dependent on the published state of the results
=> chore: tweak sharing results UX

packages/surveys/src/components/questions/OpenTextQuestion.tsx
Fixes # [1786](https://linear.app/formbricks/issue/FOR-1786/[bug]-phone-field-usability) #1963
- Test A
- Test B
=> fix: Phone validation

.github/PULL_REQUEST_TEMPLATE.md, apps/formbricks-com/app/docs/contributing/introduction/page.mdx
chore: remove old CLA form from docs & github templates
=> chore: remove old CLA form from docs & github templates

apps/web/app/api/v1/(legacy)/client/responses/route.ts, apps/web/app/api/v1/client/[environmentId]/responses/route.ts
This PR adds the CloudFront-Viewer-Country header to the supported headers. This allows users with CloudFront to also see the user's country.
see https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/adding-cloudfront-headers.html
- create response with additional header `CloudFront-Viewer-Country` and check if it's visible in Formbricks
=> feat: Add support for Cloudfront country header

docker-compose.yml
Removes default environment variables in `docker-compose.yml`
=> fix: remove default env vars in docker compose

packages/lib/response/service.ts
Fixes https://github.com/formbricks/formbricks/issues/2021
Fixes a cache validation issue in the response service where deleted surveys still show in the API as long as the cache is valid.
=> fix: deleted responses still show in API

packages/lib/invite/service.ts, packages/lib/user/service.ts
=> fix: team issues

apps/formbricks-com/app/docs/api/management/responses/page.mdx, packages/lib/response/service.ts
If you create a response and try to retrieve all the response via environmentId using management API, new response wont be present in it, because of cache not being revalidated
- Test A
- Test B
=> fix: cache revalidation on createResponse and docs

packages/surveys/src/components/general/RedirectCountdown.tsx, packages/surveys/src/components/general/ThankYouCard.tsx
Right now redirect does not work for nested windows (iframe) so replaced `window.location.replace` with `window.top.location`
- Test A
- Test B
=> fix: redirect for nested windows

apps/web/app/actions.ts, apps/web/app/error.tsx, apps/web/app/page.tsx
The current Error modal does not have a CTA except for the Try Again which sometimes does not fix the issue making the app unusable. This PR adds a "Go to Dashboard" button that resets the state and lets the user use the app!
Fixes #2045
=> feat: add go to dashboard button in error modal

apps/web/app/api/v1/client/[environmentId]/in-app/sync/route.ts, apps/web/app/lib/api/response.ts
This PR adds public caching of 10min to the app.formbricks.com/api/v1/client/<environmentId>/in-app/sync endpoint. Since Formbricks caches the survey endpoint for 15min in the frontend I think it makes sense to also add it to the backend to avoid unnecessary server load.
The cache times are up for discussion, how do you see the balance between rapid updates and server load?
- make a request to app.formbricks.com/api/v1/client/<environmentId>/in-app/sync and check the Cache-Control header
- subsequent request should include Age: 123 headers when using a proxy like Cloudflare or Cloudfront
=> feat: add caching to survey sync

.github/workflows/ecs-deployment.yml
The PR reverts the changes that were made to the ECS Github Action deploy test for debugging.
=> chore: revert ECS Github Action

packages/ee/billing/handlers/subscriptionDeleted.ts, packages/ee/billing/lib/downgradePlan.ts
Downgrades the team's ability to change Link Survey Branding & In App Branding when respective paid plans are downgraded in stripe ie end of month!
- Configure Stripe CLI to pass webhooks locally
- Upgrade Team plan
- Cancel it
- Now edit product look and feel to disable branding
- Run subscription sim clock on stripe to a month later so that the sub expires till then
- Now visit the look and feel, it should be on & disabled (since plan expired)
=> feat: downgrade team functionality when payment subscription has expired

packages/lib/constants.ts
FIxes Incorrect constants check to enable Google OAuth
- Test A
- Test B
=> fix: google oauth check only on google envs

apps/web/Dockerfile, apps/web/package.json, docker-compose.yml, packages/ui/package.json, pnpm-lock.yaml
update dockerfile to use turbo prune and same prisma version throughout the process
=> chore: update dockerfile to use turbo prune

apps/web/app/health/page.tsx, packages/lib/storage/service.ts
fix: health endpoint s3 connection
=> fix: health endpoint s3 connection

apps/formbricks-com/pages/feature-chaser/index.tsx
Fixed a simple typo on the website
N/A
=> fix: landing page typo

packages/types/surveys.ts
Fixes Survey Creation input API by making the hiddenFields as an optional value thus allowing easier survey creation as it takes the default value!
- Test A
- Test B
=> fix: hidden fields object was incorrectly required in survey creation api

packages/surveys/src/components/questions/OpenTextQuestion.tsx
Increases max height of input field to 8 lines for open text long answer questions! and after 8 lines, adds a scroll
> One pointer is that it does for both In-App as well as Link Surveys!
- Test A
- Test B
=> fix: increase max height of open text question input to 8 lines

packages/surveys/src/components/questions/OpenTextQuestion.tsx
Fixes [1943](https://linear.app/formbricks/issue/FOR-1943/tweak-allow-numbers-field-to-accept-decimals)
Enter decimal in number input field
=> fix: allow decimal in number input field

apps/web/app/(app)/environments/[environmentId]/settings/members/components/EditMemberships/MemberActions.tsx, apps/web/app/(app)/onboarding/components/onboarding.tsx, apps/web/playwright/js.spec.ts, apps/web/playwright/onboarding.spec.ts, apps/web/playwright/team.spec.ts, apps/web/playwright/utils/helper.ts
=> hotfix: e2e tests

apps/web/app/(app)/environments/[environmentId]/components/PosthogIdentify.tsx, apps/web/app/(app)/onboarding/layout.tsx
=> fix: add onboarding tracking

apps/web/app/(app)/onboarding/components/onboarding.tsx, packages/surveys/src/components/general/Survey.tsx
Fixes iFrame issue https://github.com/formbricks/formbricks/issues/2172
The error is a result of the same-origin policy, a critical security mechanism in web browsers. This policy restricts how a document or script loaded from one origin can interact with resources from another origin. In our case, the script is trying to access a frame (window.top) that is not of the same origin. 
For our onboarding it works well because the iframe in embedded in a parent with the same origin as of the onboarding survey (`https://app.formbricks.com`), but it throws an error when iframes are embedded on pages with origin different from `https://app.formbricks.com`
So to solve this we now use `Window: postMessage()`. The `window.postMessage()` method safely enables cross-origin communication between window …
=> fix: CORS error while using iframes

apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/summary/components/ShareEmbedSurvey.tsx
Refetches the server state on the `/summary` and `/responses` page when the share embed modal is closed.
https://github.com/formbricks/formbricks/assets/54475686/a965f981-20be-42de-ad91-80d4faf25f1c
- Open the share embed modal, copy survey link and submit response in another tab
- Come back and close the modal, the data should be latest fetched from the server
=> fix: refetch server data when share embed modal is closed

packages/surveys/src/components/general/HtmlBody.tsx
Call to Action question bug
removes the blank line in case of empty description.
Fixes: https://linear.app/formbricks/issue/FOR-1957/call-to-action-question-bug
=> fix: Call to Action question bug

apps/web/.gitignore, apps/web/app/(app)/environments/[environmentId]/(actionsAndAttributes)/actions/components/AddActionModal.tsx, apps/web/playwright/action.spec.ts, packages/lib/actionClass/service.ts
action cacheClass cache not getting revalidation after deleting actionClass in Formbricks
=> fix: action cacheClass cache not getting revalidation after deleting

apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/components/SurveyEditor.tsx
Fixes [1972](https://linear.app/formbricks/issue/FOR-1972/bug-confirm-save-modal-opens-even-though-survey-was-just-saved)
When back button is clicked we check the equality of `localsurvey` and `survey`
But there occurs a mismatch due to field `updatedAt`
When changes are made to a survey and then saved, `survey` is updated, which further runs this useEffect
But due to the check `if (localSurvey) return;` , `localsurvey` is not updated with the latest `survey`
And due to this there occurs a time difference between the time when survey was saved (`localsurvey.updatedAt`) and the actual time at which it was saved in database (`survey.updatedAt`)
1. Save a survey 
2. Click on back button on survey menubar
=> fix: confirm modal on back button

packages/lib/response/util.ts, packages/types/responses.ts, packages/ui/SingleResponseCard/index.tsx
fix download responses not working
Fixes #2199
- Download response file for a survey having no surveys
- Download response file for a survey having `/` in the survey name
=> fix: download responses not working

apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/summary/components/SummaryList.tsx, packages/ui/EmptySpaceFiller/index.tsx
adds skeleton loader
https://linear.app/formbricks/issue/FOR-1985/add-skeleton-loading-ui-to-summary
https://github.com/formbricks/formbricks/assets/56182734/035857b7-8cce-481a-8dd0-315e281742d6
=> feat: adds skeleton loader

apps/formbricks-com/app/docs/getting-started/framework-guides/page.mdx
The `debug` property was missed in the previous PR which cleaned up the removal of code docs. This covers it by also removing it from framework guides passed as properties
- Test A
- Test B
=> docs: remove old debug functionality in params

apps/web/playwright/api/management/survey.spec.ts
Fix End-to-End tests that were failing in copying the API keys after the Copy icon changed.
- Test A
- Test B
=> fix: (e2e) API surveys after icons changed

apps/web/app/s/[surveyId]/components/MediaBackground.tsx
Animated backgrounds in iOS are now not treated as an external video
- Test A
- Test B
=> fix: animated backgrounds in ios to not have video controls

apps/formbricks-com/components/dummyUI/types.ts, packages/lib/constants.ts, packages/lib/utils/validate.ts, packages/types/surveys.ts
fix: unable to save legacy surveys
=> fix: unable to save legacy surveys

apps/web/app/(app)/environments/[environmentId]/integrations/google-sheets/components/Home.tsx, apps/web/app/(app)/environments/[environmentId]/integrations/notion/components/Connect.tsx, apps/web/app/(app)/environments/[environmentId]/integrations/notion/components/Home.tsx
make delete button more visible
Fixes
https://linear.app/formbricks/issue/FOR-2071/make-delete-notion-integration-more-visible
- check delete button on google sheet integration
- check delete button on notion integration
=> fix: make delete button more visible

apps/web/app/(auth)/invite/page.tsx, packages/lib/constants.ts, packages/lib/env.ts
Fixes [2008](https://linear.app/formbricks/issue/FOR-2008/skip-new-onboarding-for-invite-team-members)
Test onboarding for
1. Team invite
2. ONBOARDING_DISABLED=0
3. ONBOARDING_DISABLED=1
=> fix: Skip onboarding for invite

apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/summary/components/CTASummary.tsx, apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/summary/components/CalSummary.tsx, apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/summary/components/ConsentSummary.tsx, apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/summary/components/MultipleChoiceSummary.tsx, apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/summary/components/NPSSummary.tsx, apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/summary/components/PictureChoiceSummary.tsx, apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/summary/components/RatingSummary.tsx, apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/summary/lib/util.ts
Summary view proportions don't add up to 100%
Fixes #2233 
https://linear.app/formbricks/issue/FOR-2030/%5Bbug%5D-summary-view-proportions-dont-add-up-to-100percent
- Count % in response summary of questions
=> fix: Summary view proportions don't add up to 100%

apps/web/app/(app)/environments/[environmentId]/components/Navigation.tsx
Fixes [2080](https://linear.app/formbricks/issue/FOR-2080/sort-list-alphabetically)
Create multiple teams and products
=> fix: sort team and product names alphabetically

apps/formbricks-com/app/docs/link-surveys/start-at-question/page.mdx, apps/formbricks-com/components/docs/Navigation.tsx
Adds Documentation for the `startAt` parameter in Link Surveys!
Docs for the feature built in: #2175
=> docs: startAt for Link Surveys

apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/components/AnimatedSurveyBg.tsx, apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/components/SurveyBgSelectorTab.tsx
fixes an issue where the background changes when the background tabs are changed.
Fixes #2321 (issue)
https://github.com/formbricks/formbricks/assets/54475686/9a200701-dc91-4ba4-94ca-f57f85fab19b
- Open the background styling card in a link survey, change the tab to animation
- There should be no pre-selection and the bg should be correct
=> fix: background tabs fixed

apps/formbricks-com/app/docs/contributing/setup/page.mdx
Mentions WSL2's on Postgres service that has caused issues connecting to our Prisma client & step to fix it!
Fixes #2234 
- Test A
- Test B
=> docs: wsl2 postgres side note on local setup

packages/lib/survey/service.ts
Fixes #2365
Fixed an issue were a zod error is thrown for legacy surveys in the sync endpoint because dates were not returned properly.
=> fix: date format transformation causing sync error

apps/formbricks-com/pages/in-app-survey/index.tsx, apps/web/app/(auth)/auth/components/Testimonial.tsx
=> fix: change title

apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/components/MultipleChoiceMultiForm.tsx, apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/components/MultipleChoiceSingleForm.tsx, apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/components/SurveyBgSelectorTab.tsx, packages/surveys/src/components/general/QuestionConditional.tsx, packages/surveys/src/components/questions/MultipleChoiceMultiQuestion.tsx, packages/surveys/src/components/questions/MultipleChoiceSingleQuestion.tsx, packages/surveys/src/components/questions/NPSQuestion.tsx, packages/surveys/src/components/questions/RatingQuestion.tsx, packages/ui/FileInput/index.tsx, packages/ui/TabBar/index.tsx
Fixes issue in multi select, nps and rating question 
Convert to multi select and convert to single select not working
https://github.com/formbricks/formbricks/assets/67850763/57cf1943-f6f9-4ad1-8784-5bbfbb721d4c
Other option being selected by default and When filling value for other option in multi select question, entering space leads to unexpected behaviour #2391 
https://github.com/formbricks/formbricks/assets/67850763/2a5716ff-5030-4485-a69d-f09554a7a58e
For Rating and NPS, even if optional, selecting a value should result in jumping onto next question
Test above mentioned issues
=> fix: issues in multi select, rating and nps questions

packages/types/product.ts
Go to the Look & Feel page on Production, try to update the product. In your browser console, you should see an error. This is because in the service, we get the product from DB & validate it again, and the DB returns the new logo as `null` whereas currently it accepts it to be an empty object. This PR fixes that.
=> fix: product logo is received null from prisma if not set

apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/summary/components/MultipleChoiceSummary.tsx
Add load more button to MultipleChoiceSummary component
Fixes
https://github.com/formbricks/internal/issues/68
=> feat: Add load more button to MultipleChoiceSummary component

apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/summary/components/CTASummary.tsx, apps/web/playwright/js.spec.ts, packages/js-core/src/lib/widget.ts
This PR adds the survey name to debug messages to make it easier to debug certain issues.
It also fixes a small typo in "Click-through rate" (it now uses the "official" Wikipedia spelling: https://en.wikipedia.org/wiki/Click-through_rate)
It also renames "responses" to "clicks" in the CTA tile.
- check debug messages
- check CTA tile
=> chore: Improve Debug messages

apps/web/next.config.mjs, turbo.json
use CUSTOM_CACHE_DISABLED env instead of vercel specific env to control the cacheHandler behaviour
=> chore: use CUSTOM_CACHE_DISABLED env instead of vercel specific env

apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/components/MultipleChoiceSingleForm.tsx, packages/types/surveys.ts
Fixes #2439
We now parse the survey using zod before saving it, 
```
export const ZSurveyMultipleChoiceSingleLogic = ZSurveyLogicBase.extend({
condition: z.enum(["submitted", "skipped", "equals", "notEquals"]).optional(),
value: z.string().optional(),
});
```
initially for single select question, we didnt had `includesOne` in condition enum 
Also value here can be string as well as an array of string
Add single select question
Add logic including condition `includes one of `
=> fix: single select logic issue

apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/components/AnimatedSurveyBg.tsx, packages/ui/TabBar/index.tsx
Fixes https://github.com/formbricks/internal/issues/16
Before
https://github.com/formbricks/formbricks/assets/67850763/7a0d9e81-bf5b-46b8-9e0a-f146e4e8505e
After
https://github.com/formbricks/formbricks/assets/67850763/17d7d46b-0f56-42bc-8ee6-d10c9e0eff5f
Issue occurs when `video.play` and `video.pause` are called in very short time intervals, used debouncing to fix that
Change survey backgrounds too quickly
https://github.com/formbricks/formbricks/assets/67850763/6312f1d0-204f-4bb2-a906-bca919fb8daa
=> fix: The play() request was interrupted by a call to pause()

apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/summary/actions.ts, apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/summary/components/shareEmbedTabs/EmailTab.tsx, packages/lib/emails/emails.ts
- Removes input parameters from the client side actions to just a surveyId which is also validated in the server side action
- Also adds the environment ID as the footer in the preview email
- Test A
- Test B
=> fix: secure send embed preview email action & show env id in email body

packages/ui/Survey/index.tsx, packages/ui/Survey/lib/loadScript.ts
Fixes [this](https://formbricks.sentry.io/issues/5164754177/?query=is%3Aunresolved&referrer=issue-stream&sort=freq&statsPeriod=30d&stream_index=2) sentry issue where the surveys package would error out while loading and that lead to an error being thrown because the `renderSurveyInline` method was getting called on an undefined object.
- fail the loading of the surveys package
- no error should be thrown on the client
=> fix: handles errors while loading surveys pkg

apps/web/app/api/v1/client/[environmentId]/people/[userId]/route.ts, packages/database/data-migrations/20240408123456_userid_migration/data-migration.ts, packages/js-core/src/lib/person.ts
=> fix: userId migration

apps/web/middleware.ts
Fixes rate-limiting when Formbricks is used behind a load balancer. Previously Formbricks received and rate-limited the IP address of the load balancer instead of the original source.
=> fix: rate-limiting when using a load balancer

apps/formbricks-com/app/docs/api/client/actions/page.mdx
On running the endpoint with a random userId, we get a 500 error without any helpful error message. Until we handle this error message & status code, it is helpful to mention this in the docs to the user
- Test A
- Test B
=> docs: (Client Action API) mention user should pre-exist when creating action

apps/demo/components/SurveySwitch.tsx, apps/demo/next.config.js, apps/demo/package.json, apps/demo/pages/app/index.tsx, apps/demo/pages/website/index.tsx, apps/web/app/(app)/environments/[environmentId]/(actionsAndAttributes)/actions/components/ActionActivityTab.tsx, apps/web/app/(app)/environments/[environmentId]/(actionsAndAttributes)/actions/components/ActionClassesTable.tsx, apps/web/app/(app)/environments/[environmentId]/(actionsAndAttributes)/actions/components/ActionDetailModal.tsx, apps/web/app/(app)/environments/[environmentId]/(actionsAndAttributes)/actions/page.tsx, apps/web/app/(app)/environments/[environmentId]/(peopleAndSegments)/people/[personId]/components/ActivitySection.tsx, apps/web/app/(app)/environments/[environmentId]/(peopleAndSegments)/people/[personId]/components/ActivityTimeline.tsx, apps/web/app/(app)/environments/[environmentId]/(peopleAndSegments)/people/[personId]/page.tsx, apps/web/app/api/v1/client/[environmentId]/actions/route.ts, packages/lib/action/service.ts, pnpm-lock.yaml
Actions are only stored in the backed for teams with active userTargeting subscription on Formbricks Cloud.
For now we return status code 200 for backwards compatibility and will move over to a 400 error in the future.
This reduces the API and database load for users in the free plan.
This PR also updates the `Website`/`App` switcher in the demo app to make it clearer what is chosen currently.
- Trigger actions in app surveys with `IS_FORMBRICKS_CLOUD=0`. Should still store actions in the database.
- Trigger actions in app surveys with `IS_FORMBRICKS_CLOUD=1` and inactive `userTargeting` subscription. Actions should NOT be stored in the database.
- Trigger actions in app surveys with `IS_FORMBRICKS_CLOUD=1` and active `userTargeting` subscription. Actions should be stored in the database.
=> chore: limit remote action storing to userTargeting plan

apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/components/EditThankYouCard.tsx, apps/web/playwright/survey.spec.ts, apps/web/playwright/utils/helper.ts, packages/surveys/src/components/general/ThankYouCard.tsx
adds loader in the thankyou card while response submission
Fixes
https://github.com/formbricks/internal/issues/111
- Fill a survey quickly and see the thankyou card will display only after the successful response submission
=> fix: adds loader in the thankyou card while response submission

apps/formbricks-com/app/docs/in-app-surveys/developer-quickstart/page.mdx, apps/formbricks-com/components/docs/Navigation.tsx, apps/formbricks-com/next.config.mjs
This PR adds a quickstart frontend developer guide for in-app surveys. Goal is to have an overview over all available functions and link to the detailed documentation guides.
- check /docs/in-app-surveys/developer-quickstart
=> docs: Quickstart frontend developer docs

apps/formbricks-com/app/docs/link-surveys/data-prefilling/page.mdx
Fixes https://github.com/formbricks/formbricks/issues/2529
fixes the Note formatting under How it works in Data Prefilling in Link Surveys.
- Run the ```formbricks-com```  app 
- request /docs/link-surveys/data-prefilling
=> fix: Note formatting in Link Survey Data Prefilling

packages/js/src/app.ts, packages/js/src/website.ts
Adds global error handling support for the `@formbricks/js` package, currently if anything goes wrong, the package throws errors which can block the client application in the worst case. This is fixed by returning a `Result` type from the `loadSDK` method and just logging the error instead of throwing it.
Fixes [128](https://github.com/formbricks/internal/issues/128) (issue)
- Throw an error from the `app.ts` or `website.ts` file in the `js` package
- The error should just be logged to the console and not thrown
=> fix: global error handling js package

apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/components/MatrixQuestionForm.tsx, apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/lib/validation.ts
Fixes https://github.com/formbricks/internal/issues/106
We show a toast onBlur when there are identical rows/columns like we do in multi select questions
Also it makes the card red, if some validation error exist
=> fix: Matrix Validation UX

apps/docs/app/best-practices/interview-prompt/page.mdx
Fixes #2592 
1.
2.
3.
- Check fix on https://formbricks.com/docs/best-practices/interview-prompt
=> fix: incorrect format note in multiple best practices page

README.md, apps/docs/app/self-hosting/license/page.mdx
fix: remove white label info from docs
=> fix: remove white label info from docs

apps/web/app/api/v1/management/action-classes/[actionClassId]/route.ts, apps/web/app/api/v1/management/action-classes/route.ts, apps/web/app/api/v1/management/attribute-classes/[attributeClassId]/route.ts, apps/web/app/api/v1/management/attribute-classes/route.ts, apps/web/app/api/v1/management/responses/[responseId]/route.ts, apps/web/app/api/v1/management/storage/route.ts, apps/web/app/api/v1/management/surveys/[surveyId]/route.ts, apps/web/app/api/v1/management/surveys/route.ts
Fixes [formbricks/internal#185](https://github.com/formbricks/internal/issues/185)/
Adds a try catch block around all the json input parsing in the PUT and POST endpoints in the management api
- Send some malformed json input in any management PUT or POST endpoint
- The api should return a 400 bad request error and not a 500 internal server error
=> fix: handles error in json input parsing in the management endpoints

apps/web/app/(app)/(survey-editor)/environments/[environmentId]/surveys/[surveyId]/edit/components/BackgroundStylingCard.tsx, apps/web/app/(app)/(survey-editor)/environments/[environmentId]/surveys/[surveyId]/edit/components/CardStylingSettings.tsx, apps/web/app/(app)/(survey-editor)/environments/[environmentId]/surveys/[surveyId]/edit/components/FormStylingSettings.tsx, apps/web/app/(app)/environments/[environmentId]/product/look/components/ThemeStyling.tsx, apps/web/app/(app)/environments/[environmentId]/product/look/components/ThemeStylingPreviewSurvey.tsx, packages/database/data-migrations/20240320090315_add_form_styling/data-migration-fix.ts, packages/database/package.json, packages/surveys/src/components/general/Survey.tsx, packages/surveys/src/components/wrappers/StackedCardsContainer.tsx
Fixes a bug in the data migration script which leads to ignoring the product overwrites for the products that have default styling
Fixes #2625 (issue)
- Test A
- Test B
=> fix: data migration for styling fixes

packages/surveys/src/components/general/Headline.tsx, packages/surveys/src/components/general/SurveyCloseButton.tsx, packages/surveys/src/styles/global.css
Fixes https://github.com/formbricks/formbricks/issues/2627
Increased close button size
Before
After
=> fix: input color issue on rating questio

packages/surveys/src/components/general/FileInput.tsx, packages/surveys/src/components/questions/FileUploadQuestion.tsx, packages/ui/FileInput/index.tsx
- Multiple File Uploads in a row put all the files at the beginning
- Adds uniqueId prop to FileInput component
Fixes https://github.com/formbricks/formbricks/issues/2596
https://github.com/formbricks/formbricks/assets/56182734/fa51fbcf-e8c2-4f3c-bd85-6373329a2bc3
- Create a survey with a few file upload-type questions(especially enable multi-file upload for a few)
- All questions should keep track of the uploaded files into it
=> fix: Multiple File Uploads in a row put all the files at the beginning

apps/web/app/(app)/(survey-editor)/environments/[environmentId]/surveys/[surveyId]/edit/components/SelectQuestionChoice.tsx, packages/surveys/src/components/questions/MultipleChoiceMultiQuestion.tsx, packages/surveys/src/components/questions/MultipleChoiceSingleQuestion.tsx, packages/surveys/src/lib/utils.ts
we used this piece of code to derive the question choices for multi select questions. If question contains some shuffleOption, it also shuffles and outputs the shuffled choices. Here `question.choices` is included in the dependency array, which changes when user changes the choice label in survey editor, which further triggers the recalculation of question choices, which agains shuffles the options
```
const questionChoices = useMemo(() => {
if (!question.choices) {
return [];
}
const choicesWithoutOther = question.choices.filter((choice) => choice.id !== "other");
if (question.shuffleOption) {
return shuffleQuestions(choicesWithoutOther, question.shuffleOption);
}
return choicesWithoutOther;
}, [question.choices, question.shuffleOption]);
```
So now we calculate the shuffled order only …
=> fix: Shuffled choices issue

apps/web/app/s/[surveyId]/page.tsx, packages/js-core/src/shared/utils.ts
Fixes https://github.com/formbricks/internal/issues/199
Initially id user sets the language attribute to EN, it didnt show survey in english because we used lower case language codes. Now we first convert language parameter to lowercase and then compare with language code/alias
Test uppercase language codes
=> fix: case insensitive multi langauge check

apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/summary/components/SummaryMetadata.tsx, apps/web/playwright/js.spec.ts, package.json
rename responses to completed in stats card
=> chore: rename responses to completed in stats card

apps/web/app/(app)/environments/[environmentId]/actions.ts, apps/web/app/(auth)/invite/page.tsx, apps/web/app/api/v1/users/route.ts, apps/web/app/setup/organization/create/actions.ts, packages/lib/authOptions.ts, packages/lib/organization/service.ts, packages/lib/survey/service.ts
fixes notification subscription based on user membership
Checklist:
1. New organisation:
no one gets subscribed to the auto-subscribe
2. New product:
only the product creator would get the weekly updates notifications
3. New survey:
only survey creator gets subscribed to notifications, this should be subscribed to the product's creator as well, but we don't store that value.
Fixes
https://github.com/formbricks/internal/issues/239
- Test A
- Test B
=> fix: fixes notification subscription based on user membership

apps/web/app/api/v1/client/[environmentId]/actions/route.ts, packages/lib/segment/service.ts
Storing actions on the server will be deprecated soon. This PR changes the storing logic to only store actions on the server if environment has a segment requiring actions.
=> chore: only store actions on the server when enabled in environment

apps/docs/app/app-surveys/advanced-targeting/page.mdx, packages/ee/advanced-targeting/components/add-filter-modal.tsx
Targeting based on actions is deprecated in Advanced Targeting and will be removed soon. We recommend using filters on user attributes to target the survey only to specific groups of users.
This PR only removes the option to select Actions in the Segment editor for new segments. Previously created segments based on actions are still working.
=> chore: deprecate action filtering in advanced targeting

packages/ui/SingleResponseCard/components/ResponseTagsWrapper.tsx
[BUG] Tag input appears soon after a tag is created #2884
https://github.com/user-attachments/assets/c3c866c3-5c03-46c1-8467-c4a62e965b06
- Create a Survey and Publish it
- Complete the survey which will send a response for the created survey
- Once the response is received, head back to the survey in dashboard and check the responses for the survey.
for the received response add a tag
- Before when adding a tag a text box appeared even after button click or keydown press, but now the text box doesnt appear as the box disappears as soon click or keydown events occur for this action (The promise was taking time to update the state)
- [] Checked for warnings, there are none
=> fix: close tag input immediately on keydown and add tag button click

apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/summary/components/RatingSummary.tsx, packages/lib/response/utils.ts, packages/types/surveys/types.ts
Dismissed responses are (but should not be) counted in the summary graph
Fixes #2908 
- Test A
- Test B
=> fix: Dissmissed responses are (but should not be) counted in the summary graph

packages/types/surveys/types.ts
survey validation failing when custom questionId is set as a logic jump destination. This PR is re-allowing all valid strings as logic destination.
- Test A
- Test B
=> fix: survey validation failing with custom questionId logic

apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/components/QuestionFilterComboBox.tsx
Fixes filtering issue
Filter combobox value was always constructed as an array even in cases where it shouldn't and hence it threw a validation error
Test person attribute filtering for app surveys
=> fix: filtering issue

apps/docs/app/self-hosting/license/page.mdx
fix: fix typo in self-hosting license page
=> fix: fix typo in self-hosting license page

apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/summary/components/shareEmbedModal/WebpageTab.tsx
changes the embed survey height from `100vh` to `80dvh`
- Embed a survey in a webpage
- The height should be `80vh`
- [x Filled out the "How to test" section in this PR
=> fix: embed survey height

packages/lib/response/service.ts, packages/ui/SingleResponseCard/components/SingleResponseCardHeader.tsx
To improve consistency among the dates used in Formbricks we now use the `createdAt` value in the single response card instead of the `updatedAt` value.
=> fix: use createdAt instead of updatedAt in responseCard

packages/lib/response/service.ts
Fixes the bug that files with the responses did not get deleted when the response was deleted
Fixes https://github.com/formbricks/formbricks/issues/2950
- Fill out a survey with a file upload question
- Deleting the response should delete the file
=> feat: delete uploaded files with response deletion

LICENSE, packages/api/LICENSE, packages/js/LICENSE, packages/surveys/LICENSE
The main `LICENSE` file has the Formbricks licences correctly, but the lower level files inside the packages were partly wrong, leading to confusion about the licence.
This pull request includes updates to the license information across multiple files, ensuring the correct year and removing redundant license files.
Updates to license information:
* [`LICENSE`](diffhunk://#diff-c693279643b8cd5d248172d9c22cb7cf4ed163a3c98c8a3f69c2717edd3eacb7L1-R1): Updated the copyright year to 2024; add MIT licensed react-native package; remove legacy errors package reference.
* [`packages/api/LICENSE`](diffhunk://#diff-bf1278cc902919ca1e294cfb77a1d499896b47bbe4fbda755f977dfc11378e32L3-R3): Added MIT license file.
* [`packages/js/LICENSE`](diffhunk://#diff-bf1278cc902919ca1e294cfb77a1d499896b47bbe4fbda755f …
=> fix: update lower-level license files to match main license

packages/lib/constants.ts
This pull request includes changes to the `BILLING_LIMITS` constants in the `packages/lib/constants.ts` file to update the response and MIU limits for different billing tiers.
Changes to billing limits:
* [`packages/lib/constants.ts`](diffhunk://#diff-84a559b7431271bcf747be80243751e28f9e17100616987cb5776afffe63e1a6L202-R211): Updated the `FREE` tier to 1500 responses and 2000 MIU, the `STARTUP` tier to 5000 responses and 7500 MIU, and the `SCALE` tier to 10000 responses and 30000 MIU.
=> chore: update usage limits for formbricks cloud

apps/docs/app/developer-docs/js-sdk/page.mdx
This pull request includes a small change to the `apps/docs/app/developer-docs/js-sdk/page.mdx` file. The change corrects the import statement for the Formbricks JS client.
* [`apps/docs/app/developer-docs/js-sdk/page.mdx`](diffhunk://#diff-86facb8b24ec664c3709d0358e3517278a48b65ab28f31ec3f0361bfc7c8d1f3L51-R51): Corrected the import statement for the Formbricks JS client from `@formbricks/js/app` to `@formbricks/js`.
=> docs: fix last occurence of old sdk call from docs

apps/docs/app/app-surveys/framework-guides/page.mdx
This pull request includes several changes to the `apps/docs/app/app-surveys/framework-guides/page.mdx` file, mainly focusing on the removal of references to example projects. The most important changes are:
Documentation updates:
* Removed the reference to the Example HTML project.
* Removed the reference to the Example ReactJs project.
* Removed the reference to the Example NextJS App Directory project.
* Removed the reference to the Example NextJS Pages Directory project.
* Removed the reference to the Example VueJs project.
=> docs: remove links to discontinued  examples repo

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_request.yml
This pull request includes updates to the bug report and feature request issue templates to improve clarity and streamline the process.
Changes to bug report template:
* Consolidated the `labels` field to use a list format. (`.github/ISSUE_TEMPLATE/bug_report.yml`, [.github/ISSUE_TEMPLATE/bug_report.ymlL3-R4](diffhunk://#diff-637f7b97bba458badb691a1557c3d4648686292e948dbe3e8360564378b653efL3-R4))
* Removed redundant `validations` entry in the issue summary section. (`.github/ISSUE_TEMPLATE/bug_report.yml`, [.github/ISSUE_TEMPLATE/bug_report.ymlL14-L15](diffhunk://#diff-637f7b97bba458badb691a1557c3d4648686292e948dbe3e8360564378b653efL14-L15))
* Simplified the options list under the "Your Environment" section. (`.github/ISSUE_TEMPLATE/bug_report.yml`, …
=> fix: github issue template linting issues

.github/ISSUE_TEMPLATE/bug_report.yml
This pull request includes an update to the bug report issue template to gather more detailed information from users.
Enhancements to bug report template:
* [`.github/ISSUE_TEMPLATE/bug_report.yml`](diffhunk://#diff-637f7b97bba458badb691a1557c3d4648686292e948dbe3e8360564378b653efR13-R19): Added a new `textarea` field for "Expected Behavior" to allow users to provide a clear and concise description of what they expected to happen.
=> chore: add expected behaviour to github bug template

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.yml
This pull request includes changes to the GitHub issue templates to improve their configuration and categorization. The most important changes include updating the bug report and feature request templates to use the `type` field instead of labels, and enabling blank issues in the configuration file.
Improvements to issue templates:
* [`.github/ISSUE_TEMPLATE/bug_report.yml`](diffhunk://#diff-637f7b97bba458badb691a1557c3d4648686292e948dbe3e8360564378b653efL3-R3): Replaced the `labels` field with the `type` field set to `bug`.
* [`.github/ISSUE_TEMPLATE/feature_request.yml`](diffhunk://#diff-c6b098646bf32c644234bec14c2675ea2a3d9c2dc2df450a25aa0e7ff02323cdL3-R3): Replaced the `labels` field with the `type` field set to `feature`.
Configuration changes:
* …
=> chore: update github issue template

.github/workflows/draft-release.yml, apps/web/package.json
This pull request includes a modification to the GitHub Actions workflow file `.github/workflows/draft-release.yml` to reorder the steps for checking out the code and configuring git.
Changes in the GitHub Actions workflow:
* Moved the `actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683` step to occur before configuring git.
* Moved the `./.github/actions/dangerous-git-checkout` step to occur before configuring git.
=> fix: draft release workflow

.github/workflows/prepare-release.yml, apps/web/package.json
This pull request includes updates to the release workflow and a version bump for the `apps/web` package. The most important changes are as follows:
* [`.github/workflows/prepare-release.yml`](diffhunk://#diff-ddf2bab74923dcd43f9f8d05e50bb1adc9ee5366a394d151d1f04a54a6079486L1-R2): Renamed from `draft-release.yml` and updated the workflow name and run-name to "Prepare release".
* [`.github/workflows/prepare-release.yml`](diffhunk://#diff-ddf2bab74923dcd43f9f8d05e50bb1adc9ee5366a394d151d1f04a54a6079486R14-R17): Added `pull-requests: write` permission under `permissions`.
* [`.github/workflows/prepare-release.yml`](diffhunk://#diff-ddf2bab74923dcd43f9f8d05e50bb1adc9ee5366a394d151d1f04a54a6079486L45-L55): Modified the job name from `draft_release` to `prepare_release`, and updated the steps …
=> chore: prepare 3.1.3 release

docs/mint.json
This pull request includes a change to the `docs/mint.json` file to correct the destination path for a specific documentation link.
* [`docs/mint.json`](diffhunk://#diff-c91a604899dfef4b2494c317f4fd39a7f22b79986095f580399347293d534debL412-R412): Updated the `destination` path for the `/docs/app-surveys/actions` source to remove the redundant `/docs` prefix.
=> chore: add more legacy docs redirects

.github/workflows/scorecard.yml
This pull request includes a small change to the `.github/workflows/scorecard.yml` file. The change renames the artifact from `SARIF-file` to `sarif` in the upload artifact step.
* [`.github/workflows/scorecard.yml`](diffhunk://#diff-2e3112f4e81a9c47df8000638ce3b1b9ca15edcc82b228c207a7a4ff3bc7133fL67-R67): Renamed the artifact from `SARIF-file` to `sarif` in the `Upload artifact` step.
=> fix: scorecard filename

.github/workflows/scorecard.yml
This pull request includes an update to the GitHub Actions workflow configuration for the `scorecard.yml` file. The main change involves updating the version of the `actions/upload-artifact` action.
* [`.github/workflows/scorecard.yml`](diffhunk://#diff-2e3112f4e81a9c47df8000638ce3b1b9ca15edcc82b228c207a7a4ff3bc7133fL65-R65): Updated the `actions/upload-artifact` action from version `97a0fba1372883ab732affbe8f94b823f91727db` (v3.pre.node20) to `65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08` (v4.6.0).
=> chore: update scorecard action artifact version

docs/mint.json, docs/self-hosting/setup/monitoring.mdx
This pull request adds a new monitoring setup guide for self-hosting Formbricks. The most important changes include updating the documentation to include a new monitoring page and providing detailed instructions on logging, OpenTelemetry integration, and health checks.
Documentation updates:
* [`docs/mint.json`](diffhunk://#diff-c91a604899dfef4b2494c317f4fd39a7f22b79986095f580399347293d534debL247-R248): Added a reference to the new `self-hosting/setup/monitoring` page.
* [`docs/self-hosting/setup/monitoring.mdx`](diffhunk://#diff-e2febdcaaa0b05a391947d4e736f0bcdbbe45e7808c81518aa9a12198d33d47eR1-R91): Created a new monitoring setup guide with sections on logging, OpenTelemetry integration, and health checks.
=> docs: add monitoring page to self-hosting

docs/self-hosting/setup/monitoring.mdx
This pull request includes significant updates to the monitoring documentation for self-hosting Formbricks. The changes enhance the clarity and comprehensiveness of logging and observability configurations, including new sections on log levels, log formats, and Prometheus integration.
Enhancements to logging documentation:
* Added detailed descriptions of log levels (`debug`, `info`, `warn`, `error`, `fatal`) and how to configure them using the `LOG_LEVEL` environment variable.
* Introduced a new log format section explaining the JSON structure of log entries, including fields such as `level`, `time`, `pid`, `hostname`, `requestId`, `userId`, `msg`, `stack`, and `data`.
Improvements to observability integration:
* Updated the OpenTelemetry section to distinguish between tracing and …
=> docs: add prometheus to monitoring docs

.github/workflows/formbricks-release.yml, packages/lib/messages/de-DE.json, packages/lib/messages/en-US.json, packages/lib/messages/fr-FR.json, packages/lib/messages/pt-BR.json, packages/lib/messages/pt-PT.json, packages/lib/messages/zh-Hant-TW.json
This pull request includes changes to the `.github/workflows/formbricks-release.yml` file and several localization files. The most important changes include renaming the workflow file, updating job names and adding secrets inheritance, and removing a specific localization string from multiple language files.
Workflow file updates:
* Renamed `.github/workflows/formbricks-deploy.yml` to `.github/workflows/formbricks-release.yml` and updated the workflow name to "Build, release & deploy Formbricks images".
* Updated job names in the workflow to reflect the release process and added `secrets: inherit` to the `docker-build` and `helm-chart-release` jobs.
=> fix: Github release action unable to access secrets

.github/workflows/release-docker-github.yml, apps/web/app/(app)/environments/[environmentId]/components/TopControlButtons.tsx
This pull request includes a couple of changes to the configuration and UI components to improve security and user experience.
Configuration changes:
* [`.github/workflows/release-docker-github.yml`](diffhunk://#diff-97f60e2f0f6e69dfe1ae7fce8784e352b5be0d905d9de440b55d449009606717L22): Removed the hardcoded `DATABASE_URL` from the environment variables to enhance security.
UI component changes:
* `apps/web/app/(app)/environments/[environmentId]/components/TopControlButtons.tsx`: Updated the link URL in the `TopControlButtons` component to direct users to the issues page instead of the new issue creation page for better navigation. ([apps/web/app/(app)/environments/[environmentId]/components/TopControlButtons.tsxL42-R42](diffhunk://#diff-d462e6bae2a9f91b995cbce3cb921689550bfedccd79a3060d063 …
=> fix: github issues url required login

apps/web/vite.config.mts
This pull request simplifies and standardizes the configuration for test coverage in the `apps/web/vite.config.mts` file. The changes reduce redundancy and improve maintainability by consolidating the `include` and `exclude` patterns.
* Consolidated the `include` array to a more generic pattern: `["app/**/*.{ts,tsx}", "modules/**/*.{ts,tsx}", "lib/**/*.{ts,tsx}"]`. This replaces the extensive list of specific file paths and patterns with a broader and more maintainable approach.
* Standardized the `exclude` array by grouping similar file types and directories, such as test files (`**/*.spec.*`, `**/*.test.*`), mock files (`**/*.mock.*`, `**/mocks/**`, `**/__mocks__/**`), and configuration files (`**/*.config.{js,ts,mjs,mts,cjs}`). This ensures consistent exclusions while removing …
=> chore: simplify vite config for better coverage report

apps/web/modules/ui/components/editor/components/toolbar-plugin.tsx
Fixes #6116 
NOTE: - the but was not CTA specific as mentioned in issue, but it was general bug caused in long description irrespective of question (i've demonstrated with two examples).
the issue was cause because for some werid reason `white-space:pre-wrap` preserving intend from first line and adding it to all other lines except first line. 
https://github.com/user-attachments/assets/f66a99c1-8633-4e26-ae15-fc7988761cb1
https://github.com/user-attachments/assets/5c85fc0d-f980-4d4c-b7dc-1cb139eda475
https://github.com/user-attachments/assets/79a61768-5bae-4ce3-81b5-66e98474c021
=> fix: Preview in Email embed is broken

apps/web/modules/survey/editor/components/response-options-card.tsx
Backports the fix that got merged in #6249 
- The survey editor should not have any UI for the single use id in the response options card under settings view
=> fix: backports removal of suid UI from survey editor

.github/workflows/deploy-formbricks-cloud.yml
- EKS cluster endpoint is private-only (`10.0.54.118` in VPC `10.0.0.0/16`)
- `tailscale-eks-router` correctly advertises subnet routes for `10.0.0.0/16`
- GitHub Actions was connecting to Tailscale but **not accepting subnet routes**
- Traffic to EKS endpoint was attempting internet routing instead of VPC routing
Added `args: --accept-routes` to the `tailscale/github-action@v3` configuration.
This enables GitHub Actions runners to:
- Accept advertised subnet routes from `tailscale-eks-router`
- Route traffic to `10.0.54.118` through the subnet router into the VPC
- Successfully reach the private EKS cluster
- `.github/workflows/deploy-formbricks-cloud.yml`: Added `args: --accept-routes` to Tailscale step
This restores the functionality that was working previously. The route acceptance …
=> fix: enable Tailscale subnet routes for EKS access

apps/web/locales/de-DE.json, apps/web/locales/en-US.json, apps/web/locales/fr-FR.json, apps/web/locales/pt-BR.json, apps/web/locales/pt-PT.json, apps/web/locales/zh-Hant-TW.json
This doesn't correctly describe the behaviour, it actually checks partials and completed ones.
=> fix: update wording to match actual behaviour

.github/workflows/formbricks-release.yml
GitHub Actions failed to parse the release workflow due to referencing `env.ENVIRONMENT` inside a reusable workflow `with:` block. This PR removes the global `env.ENVIRONMENT` and computes the environment inline where needed.
- Error: “Unrecognized named-value: 'env'” at the reusable workflow call.
- Reason: The `env` context is not available inside `with:` for reusable workflows; only specific contexts like `github`, `inputs`, `needs`, and `vars` are allowed there.
- Removed workflow-level `env.ENVIRONMENT`.
- Updated `deploy-formbricks-cloud` to pass:
- `ENVIRONMENT: ${{ github.event.release.prerelease && 'staging' || 'production' }}`
- Updated `upload-sentry-sourcemaps` to set:
- `environment: ${{ github.event.release.prerelease && 'staging' || 'production' }}`
- Avoids invalid `env` …
=> fix: release workflow environment is not accessible

docs/development/guides/auth-and-provision/setup-saml-with-identity-providers.mdx
adds identifier note in SAML SSO docs
1. 
2.
Fixes #(issue)
- Check the [docs](https://formbricks.com/docs/development/guides/auth-and-provision/setup-saml-with-identity-providers#saml-with-okta), it should clarify the usage of entity id identifier.
=> docs: adds identifier note in saml sso docs

.github/workflows/deploy-formbricks-cloud.yml, .github/workflows/formbricks-release.yml
- Permission denial from reusable workflows: The called workflows requested `packages: write` and `id-token: write` at job level, but the calling jobs only had the default `contents: read`. GitHub rejected the run with a permissions mismatch error.
- Minimal job-level permissions
- `docker-build` (calls `release-docker-github.yml`):
- `permissions: contents: read, packages: write, id-token: write`
- `helm-chart-release` (calls `release-helm-chart.yml`):
- `permissions: contents: read, packages: write`
- `deploy-formbricks-cloud` (assumes AWS role using OIDC):
- `permissions: contents: read, id-token: write`
- Granting only the minimal permissions at the calling job level satisfies the reusable workflows’ requirements and adheres to least-privilege best practices.
=> fix: permissions in release workflow

packages/surveys/src/components/general/question-media.tsx, packages/surveys/src/components/icons/expand-icon.test.tsx, packages/surveys/src/components/icons/expand-icon.tsx, packages/surveys/src/components/icons/image-down-icon.test.tsx, packages/surveys/src/components/icons/image-down-icon.tsx, packages/surveys/src/components/questions/picture-selection-question.tsx
Inconsistent icon - Picture select vs. question header image
Fixes #6329
- Check the icon in the question header image
=> fix: Inconsistent icon - Picture select vs. question header image

apps/web/lib/surveyLogic/utils.ts, packages/surveys/src/lib/logic.ts
open text number question logic evaluation
Fixes https://github.com/formbricks/internal/issues/760
- Create a survey with an open-text number type question.
- Create two survey endings, ending 1 and ending 2.
- Add a logic rule to the first question: if the value is less than 10, redirect to ending 2; otherwise, redirect to ending 1.
- When the value is 0, redirect to ending 2.
=> fix: open text number question logic evaluation

apps/web/package.json, packages/database/package.json, packages/database/zod/surveys.ts, packages/types/package.json, pnpm-lock.yaml
Upgrades the Prisma version
The latest Prisma version is 6.14, but the latest `prisma-json-types-generator` only supports 6.13. It shows a warning for higher versions, so we’ve updated the version to 6.13 for now. There’s an open PR (https://github.com/arthurfiorette/prisma-json-types-generator/pull/536) in the JSON type generator to support 6.14 as well, and we’ll update the Prisma version with that.
Fixes https://github.com/formbricks/internal/issues/1005
- Everything should work fine
=> chore: upgrades prisma to latest version

.cursor/rules/database.mdc, .cursor/rules/overview.mdc
This PR introduces an always-on Cursor rule providing a concise, high-signal overview of the Formbricks monorepo and slightly refines the database rule metadata.
What’s included:
- Add `.cursor/rules/overview.mdc` (alwaysApply: true)
- Highlights: project identity, turborepo+pnpn setup, core apps & packages with purposes
- Enterprise-ready & accessibility design principles
- Full set of root `pnpm` commands for quick reference
- Essential repo context: envs, datastores, docs/ops, licensing
- Update `.cursor/rules/database.mdc` frontmatter to a clear, concise description to better match the repository’s rule usage style
Why:
- Make the most essential monorepo knowledge available in every prompt to reduce context-switching and improve developer velocity
- Keep deeper package/app details out …
=> chore(cursor): add monorepo overview rule and refine database rule metadata

packages/surveys/src/components/questions/open-text-question.tsx, packages/surveys/src/lib/i18n.ts
Adds line break support in the open-text question textarea
Fixes https://github.com/formbricks/formbricks/issues/6436
- Support for line breaks should include:
- `&#10;` → Line Feed (\n)
- `&#13;` → Carriage Return (\r)
- `\r`
- `\n`
- `\r\n` (CRLF)
=> feat: adds line break support in open text question textarea

apps/web/modules/ee/billing/api/lib/subscription-created-or-updated.ts
This pull request makes a minor change to the billing logic by removing support for the `SCALE` billing plan (deprecated) in the `handleSubscriptionCreatedOrUpdated` function.
- Removed handling for the `SCALE` billing plan in `handleSubscriptionCreatedOrUpdated` within `subscription-created-or-updated.ts`
=> chore: remove deprecated scale plan from stripe subscription update

apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/responses/components/ResponseTableColumns.tsx, apps/web/modules/ui/components/tooltip/index.test.tsx, apps/web/modules/ui/components/tooltip/index.tsx
**Problem:**
During skeleton state the tooltip showed, but after the table rendered, the tooltip appeared as an empty/blank bubble.
It affected the “Person” column header tooltip.
Fixes #6334 
1. Navigate to the Survey Responses page.
2. Hover over the “Person” help icon — a tooltip appears containing text and a link.
3. Click the “Learn more” link — it opens in a new tab.
=> fix(tooltip): wrap TooltipContent in a Portal for improved rendering

apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/responses/components/ResponseTableColumns.test.tsx, apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/responses/components/ResponseTableColumns.tsx, apps/web/modules/ui/components/data-table/components/data-table-settings-modal-item.test.tsx, apps/web/modules/ui/components/data-table/components/data-table-settings-modal-item.tsx, apps/web/modules/ui/components/data-table/components/data-table-settings-modal.tsx
Issue was response data table breaking due to conflicting column id for address question with country column and country metadata. We also improved how column names are rendered in the response data table settings modal. Previously, column names were generated manually using custom logic, but they are now automatically aligned with the headers in the response table.
Test response table column settings with address question with country field enabled
=> fix: response data table settings modal breaking

.github/actions/build-and-push-docker/action.yml, .github/workflows/release-docker-github.yml
The `release-docker-github.yml` workflow was failing on valid SemVer prerelease tags like `4.0.0-rc.1` with this error:
```
❌ Error: Invalid release tag format after extraction. Must be semver (e.g., 1.2.3, 1.2.3-alpha)
Original ref: refs/tags/4.0.0-rc.1
Extracted tag: refs/tags/4.0.0-rc.1
```
When called via `workflow_call` from the release workflow, `GITHUB_REF` contains the **branch reference** (`refs/heads/main`), not the **tag reference** (`refs/tags/4.0.0-rc.1`). The tag extraction logic `TAG=${TAG#refs/tags/}` was failing because it was trying to strip `refs/tags/` from a branch reference.
Implemented smart tag extraction that handles both contexts:
- **workflow_call** (from releases): Use `GITHUB_REF_NAME` which contains the clean tag name
- **Direct triggers**: Fallback to …
=> fix: release tag extraction in release action

apps/web/lib/constants.ts, docs/self-hosting/setup/cluster-setup.mdx, packages/storage/src/client.test.ts, packages/storage/src/client.ts
The current S3 client configuration requires both `S3_REGION` and `S3_BUCKET_NAME` to be set, which creates unnecessary friction for cloud deployments using IAM roles. Many AWS deployments only need the bucket name, as the AWS SDK can automatically:
- Default to `us-east-1` region when none is specified
- Auto-detect the correct region when making requests
- Use IAM instance profiles/roles for authentication without explicit credentials
This was causing issues in cloud setups where DevOps engineers had only configured `S3_BUCKET_NAME`.
Updated the S3 client configuration to make `S3_REGION` truly optional while maintaining backward compatibility:
1. **Relaxed Validation Logic**
- Only `S3_BUCKET_NAME` is now required
- `S3_REGION` is conditionally added to config only if provided
- Allows …
=> fix: s3 storage configured flag fails on minimum setup

apps/web/lib/jwt.test.ts, apps/web/lib/jwt.ts, apps/web/modules/auth/lib/authOptions.test.ts, apps/web/modules/email/index.tsx
🔒 Fix Critical JWT Signature Verification Vulnerability
**Severity:** Critical  
**CVE:** Missing JWT signature verification allowing authentication bypass
- **Issue:** JWT tokens were decoded using `jwt.decode()` instead of `jwt.verify()`
- **Impact:** Attackers could bypass authentication by crafting unsigned or maliciously signed tokens
- **Risk:** Complete authentication bypass, unauthorized access to user accounts
- **Attack Vector:** Manipulated JWT tokens with invalid or missing signatures
- ✅ **Replaced `jwt.decode()` with `jwt.verify()`** in all token verification functions
- ✅ **Enforced signature validation** against `NEXTAUTH_SECRET`
- ✅ **Maintained backward compatibility** for existing legacy tokens
- ✅ **Added proper error handling** and logging for verification failures
- …
=> fix: enhance JWT handling with improved encryption and decryption logic

.github/workflows/move-stable-tag.yml
This PR fixes the release pipeline validation to accept the new release tag format without the "v" prefix (e.g., `4.0.0` instead of `v4.0.0`).
- **Updated regex validation** in `.github/workflows/move-stable-tag.yml`:
- Removed requirement for "v" prefix in release tag format
- Changed from `^v[0-9]+\.[0-9]+\.[0-9]+...` to `^[0-9]+\.[0-9]+\.[0-9]+...`
- **Updated error message** to reflect new expected format (`1.2.3` instead of `v1.2.3`)
- **Updated input description** to show correct format example
Resolves the pipeline error:
```
❌ Error: Invalid release tag format. Expected format: v1.2.3, v1.2.3-alpha
Provided: 4.0.0
Error: Process completed with exit code 1.
```
The validation now accepts:
- ✅ `4.0.0` (standard release)
- ✅ `4.0.0-alpha` (prerelease)
- ✅ `4.0.0+build.1` (build …
=> fix(ci): update release tag validation to accept format without v prefix

apps/web/modules/ui/components/id-badge/components/badge-content.tsx, apps/web/modules/ui/components/id-badge/index.test.tsx
The `IdBadge` component was causing hydration issues when used inside other button elements, specifically in the `MultipleChoiceSummary` component. This occurred because the `IdBadge` component internally used a `<button>` element, which when placed inside another `<button>` creates invalid HTML structure and leads to React hydration errors.
1. Navigate to a survey summary page with multiple choice questions
2. Observe the `MultipleChoiceSummary` component where `IdBadge` is used inside a clickable button
3. Check browser console for hydration errors indicating nested button elements
4. Notice UI breakage or inconsistent behavior
- **Changed `<button>` to `<div>`**: Replaced the button element with a div that has `role="button"` in `badge-content.tsx`
- **Maintained Accessibility**: …
=> fix: replace button with div in IdBadge to prevent hydration issues

apps/web/modules/ui/components/breadcrumb/index.tsx
Problem: Multiple users couldn't find the org and project configs
Solution: Make the hover effect stronger so it's clear its clickable
=> chore: increase visibility of hover effect to indicate clickability

apps/web/modules/ee/billing/components/pricing-card.tsx
Problem: Customers couldn't find where to manage their subscription:
Changed bg to Stripe color: Purple with white text
After
=> fix: switch Manage Subscription button bg to stripe color

apps/web/modules/survey/components/question-form-input/index.tsx, apps/web/modules/survey/editor/components/matrix-question-form.test.tsx, apps/web/modules/survey/editor/components/matrix-question-form.tsx, apps/web/modules/survey/editor/components/matrix-sortable-item.tsx, apps/web/modules/survey/editor/components/multiple-choice-question-form.test.tsx, apps/web/modules/survey/editor/components/multiple-choice-question-form.tsx, apps/web/modules/survey/editor/components/question-card.tsx, apps/web/modules/survey/editor/components/question-option-choice.test.tsx, apps/web/modules/survey/editor/components/question-option-choice.tsx, apps/web/modules/survey/editor/components/ranking-question-form.test.tsx, apps/web/modules/survey/editor/components/ranking-question-form.tsx
As requested by GetUp, you can now hit ENTER when typing options in Single & Multi Select Questions. If there are empty options, it jumps to the next empty option. If there are no empty options, it creates a new one and readjusts focus.
This makes survey creation faster & smoother.
This applies to:
- Single select
- Multi select
- Ranking and
- Matrix (Cols & Rows)
Additionally, the PR removes the unused "lastQuestion" prop and fixes a few SonarQube issues in the related files.
=> feat: hit ENTER for new option

apps/web/app/api/v1/client/[environmentId]/environment/lib/environmentState.test.ts, apps/web/app/api/v1/client/[environmentId]/environment/lib/environmentState.ts, apps/web/modules/ee/contacts/api/v1/client/[environmentId]/user/lib/segments.ts
This PR reduces the cache time-to-live from **5 minutes to 1 minute** for environment state and segments endpoints used by SDKs and in-product surveys.
Improves user experience by providing faster feedback when testing surveys and integrations, reducing the delay between making changes and seeing them reflected.
- ✅ Reduced cache TTL from 5 minutes to 1 minute in `environmentState.ts`
- ✅ Updated corresponding test in `environmentState.test.ts`
- ✅ Reduced cache TTL from 5 minutes to 1 minute in `segments.ts`
This is an **experiment** to:
1. Measure the impact on server load from increased cache miss rate
2. Evaluate whether caching is necessary at these endpoints
3. Determine if the system can effectively handle increased request frequency without server-side caching
- Existing tests …
=> perf: reduce cache TTL to 1 minute for SDK environment state and segments

.github/actions/build-and-push-docker/action.yml, .github/workflows/build-and-push-ecr.yml, .github/workflows/formbricks-release.yml, .github/workflows/move-stable-tag.yml, .github/workflows/release-docker-github.yml
This PR implements conditional tagging for Docker images and Git tags based on whether a GitHub release is marked as "Set as the latest release".
```
GitHub Release Published
↓
┌─────────────────────────┐
│ check-latest-release    │ ← Queries GitHub API
│ job                     │   Compares current vs latest
└─────────────────────────┘
↓
is_latest output
↓
┌─────────────────────────┐
│ docker-build-community  │ ← Receives MAKE_LATEST
│ docker-build-cloud      │ ← Receives MAKE_LATEST  
│ move-stable-tag         │ ← Receives make_latest
└─────────────────────────┘
↓
┌─────────────────────────┐
│ build-and-push-docker  │ ← Applies conditional tagging
│ action                  │   - ECR: production tag
│                        │   - GHCR: latest tag
└─────────────────────────┘
```
- …
=> feat(ci): add conditional tagging based on 'Set as latest release' option

apps/web/next.config.mjs
Large images (10-11MB) are causing Next.js Image Optimization timeouts of 60+ seconds, resulting in CPU spikes up to 81% and CloudFront origin timeouts (30s).
This PR implements **Phase 1** image optimization improvements to reduce CPU usage and prevent timeouts:
1. **Removed 3840px device size** - Prevents expensive 4K image processing
2. **WebP-only format** - 25-35% faster encoding than JPEG/PNG with smaller file sizes
3. **Added standard image sizes** - Better optimization coverage for all use cases
4. **Minimum cache TTL of 60s** - Reduces redundant processing of the same images
5. **Security headers** - Added CSP and content disposition for user-uploaded images
- ⚡ **Faster processing:** WebP encoding is typically 25-35% faster than JPEG
- 📉 **Lower CPU usage:** Capping at 1920px …
=> perf(web): optimize Next.js image processing to prevent timeouts
