- apps/web/app/s/[surveyId]/layout.tsx
Fixes 
Change survey of status to completed/pause 
Open that survey
> fix: survey inactive layout

- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/summary/components/SummaryDropOffs.tsx
Fixes Drop off rate calculation in drop off summary
Fixes #1713
> fix: drop off rate 

- packages/lib/environment/cache.ts
- packages/lib/environment/service.ts
- packages/lib/product/service.ts
fix: cache revalidation after product was deleted
> fix: cache revalidation after product was deleted

- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/components/SurveyMenuBar.tsx
fix: send toast when delete fails in survey editor
> fix: send toast when delete fails in survey editor

- apps/web/app/global-error.tsx
chore: add global-error component
> chore: add global-error component

- docker/production.sh
Fixes incorrect placement of Installing Traefik in prod script
- Test A
- Test B
> fix: echo placement in prod script

- apps/storybook/package.json
- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/summary/components/CTASummary.tsx
- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/summary/components/ConsentSummary.tsx
- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/summary/components/DateQuestionSummary.tsx
- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/summary/components/FileUploadSummary.tsx
- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/summary/components/Headline.tsx
- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/summary/components/MultipleChoiceSummary.tsx
- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/summary/components/NPSSummary.tsx
- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/summary/components/OpenTextSummary.tsx
- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/summary/components/PictureChoiceSummary.tsx
- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/summary/components/RatingSummary.tsx
Fixes [1551](https://linear.app/formbricks/issue/FOR-1551/ui-tweaks-summary-view)
Test optional question sumary
> fix: tweaks on summary page

- apps/storybook/package.json
- apps/web/app/(app)/environments/[environmentId]/surveys/components/Modal.tsx
- apps/web/app/(app)/environments/[environmentId]/surveys/components/PreviewSurvey.tsx
- apps/web/app/(app)/environments/[environmentId]/surveys/templates/TemplateContainer.tsx
- apps/web/app/s/[surveyId]/components/MediaBackground.tsx
- packages/surveys/src/components/general/Survey.tsx
Fixes [1552](https://linear.app/formbricks/issue/FOR-1552/in-app-survey-preview-broken-top-positions)
Also fixes
https://github.com/formbricks/formbricks/assets/67850763/c5cbe32e-e8fc-4d29-9d58-53fe62c1db8a
Test in app survey mobile preview with long questions (should overflow)
Test top right and top left positions for in app surveyes (web)
> fix: preview

- apps/web/app/(app)/environments/[environmentId]/components/Navigation.tsx
Add email us CTA to the menu to offer a direct contact point:
> feat: Add "Email us" CTA to menu

- packages/js/package.json
- packages/surveys/src/components/general/Survey.tsx
> fix: fixes date picker overflowing ui

- apps/web/app/s/[surveyId]/components/VerifyEmail.tsx
> fix: Verify Email Styling

- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/components/QuestionsView.tsx
- apps/web/app/(app)/environments/[environmentId]/surveys/components/PreviewSurvey.tsx
Fixes [1579](https://linear.app/formbricks/issue/FOR-1579/deleting-question-leaves-preview-blank)
Try to delete last question
Also delete a question will, show the preview of question that is two question ahead
For example deleting first question will show the preview of third
Also corrected welcome card ID
> fix: delete question preview issue

- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/components/RecontactOptionsCard.tsx
- apps/web/app/lib/surveys/surveys.ts
- packages/lib/authOptions.ts
- packages/surveys/src/components/questions/DateQuestion.tsx
- packages/surveys/src/sideload/question-date/Question.tsx
- packages/surveys/src/sideload/question-date/index.tsx
> fix: replaces all @ts-ignore with @ts-expect-error

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .devcontainer/docker-compose.yml
- .env.example
- apps/web/next.config.mjs
Fixes GitHub Codespaces setup using devcontainers
Also defaults the email verification and password reset as off for users to not be dependent on mailhog for quick setup!
- Test A
- Test B
> fix: codespaces setup

- apps/formbricks-com/app/docs/getting-started/framework-guides/page.mdx
- apps/formbricks-com/components/home/SetupTabs.tsx
- apps/web/app/(app)/environments/[environmentId]/settings/setup/components/SetupInstructions.tsx
- apps/web/package.json
- packages/api/package.json
- packages/js/package.json
- packages/surveys/package.json
- packages/surveys/src/components/questions/DateQuestion.tsx
> chore: prepare 1.4.0 release

- apps/web/app/(app)/environments/[environmentId]/surveys/components/PreviewSurvey.tsx
> hotfix: fixes mobile preview UI

- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/summary/components/FileUploadSummary.tsx
Fixes [1595](https://linear.app/formbricks/issue/FOR-1595/bug-potentially-unsafe-external-link)
`Using rel="noopener noreferrer" with target="_blank" in anchor tags enhances security by preventing the new page from accessing the original page's context and stops the sharing of referrer information.`
- Test A
- Test B
> fix: external link issue

- apps/web/app/(app)/components/PosthogIdentify.tsx
chore: add user properties to posthog integration
> chore: add user properties to posthog integration

- .env.example
- docker-compose.yml
- package.json
fix: remove comments in env files
> fix: remove comments in env files

- packages/surveys/src/components/questions/MultipleChoiceMultiQuestion.tsx
- packages/surveys/src/components/questions/MultipleChoiceSingleQuestion.tsx
Fixes 2 issues in other option:
1. Each character in other option is treated as a new value
2. When two multi select questions with other field enabled follows each other, answer of first question is carried into second's
- Test A
- Test B
> fix: other option

- apps/web/app/(app)/environments/[environmentId]/settings/billing/components/PricingTable.tsx
- apps/web/app/(app)/environments/[environmentId]/settings/lookandfeel/page.tsx
- apps/web/app/(app)/environments/[environmentId]/settings/members/components/AddMemberModal.tsx
- apps/web/app/(app)/environments/[environmentId]/settings/members/components/EditMemberships/EditMemberships.tsx
- apps/web/app/(app)/environments/[environmentId]/settings/members/components/EditMemberships/MembersInfo.tsx
- apps/web/app/(app)/environments/[environmentId]/settings/members/components/EditMemberships/TeamActions.tsx
- apps/web/app/(app)/environments/[environmentId]/settings/members/page.tsx
- packages/ee/lib/service.ts
- packages/ui/UpgradePlanNotice/index.tsx
- Role Management is now only allowed in cloud if paid appSurvey plan is purchased
- Role Managemet is now only allowed in self hosting in enterprise license is present
- App Survey Branding can now only be removed in cloud if appSurvey plan is purchased (have also added this in our internal pricing page)
- App Survey Branding can now only be removed in self hosted if enterprise license is present
To simplify this logic,
Moved all of them under a single file for uniformity
- Test A
- Test B
> feat: role management is only allowed on paid inAppSurveys plan

- apps/web/app/layout.tsx
fix: PIN survey caused faulty layout due to background
> fix: PIN survey caused faulty layout due to background

- apps/web/app/api/cron/weekly_summary/route.ts
chore: increase batch size of weekly summary team calls
> chore: increase batch size of weekly summary team calls

- apps/web/app/(app)/environments/[environmentId]/surveys/components/Modal.tsx
- packages/surveys/src/components/questions/RatingQuestion.tsx
Scales down the preview as screen size reduces
Fixes [1605](https://linear.app/formbricks/issue/FOR-1605/bug-small-screen-in-app-preview-overflows)[
1598](https://linear.app/formbricks/issue/FOR-1598/bug-smiley-rating-not-correctly-aligned)
https://github.com/formbricks/formbricks/assets/67850763/fba091e4-2f85-45ca-a8d5-8491896269d0
- Test A
- Test B
> fix: scaling issues

- apps/web/app/(app)/environments/[environmentId]/surveys/templates/TemplateList.tsx
Fixes #1572 
Makes `environments/[environmentId]/surveys/templates` keyboard accessible
Loom Video: https://www.loom.com/share/fb11da08328f468fb60547b138efb1a3?sid=bbd9f73c-0f67-415b-bde4-5643b7d0a083
- Go to `environments/[environmentId]/surveys/templates` 
- Use keyboard to navigate and select templates
> fix: make template page keyboard accessible

- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/components/LogicEditor.tsx
Fixes Survey editor breaking when adding option to multi select question (when logics jumps are enabled)
Also fixes alignment issue of question card
https://github.com/formbricks/formbricks/assets/67850763/a04effb3-f29f-459e-a2f1-f55580272801
Open churn survey template
Try to add a new option
> fix: logic jump issues

- packages/surveys/src/components/questions/RatingQuestion.tsx
> fix: rating question alignment

- apps/web/app/s/[surveyId]/components/LegalFooter.tsx
- apps/web/app/s/[surveyId]/components/PinScreen.tsx
- apps/web/app/s/[surveyId]/page.tsx
Fixes [1613](https://linear.app/formbricks/issue/FOR-1613/media-backgrounds-dont-work-when-pin-protection-is-enabled)
- Test A
- Test B
> fix: background image issue

- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/components/SurveyMenuBar.tsx
Fixes [1616](https://linear.app/formbricks/issue/FOR-1616/bug-dialog-cta-forwarding-doesnt-work)
Click on save button
> fix: delayed survey saving

- apps/formbricks-com/lib/cleanHtml.ts
- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/components/SurveyMenuBar.tsx
- packages/lib/cleanHtml.ts
- packages/surveys/src/lib/cleanHtml.ts
Current `cleanHtml` script doesn't account for certain complex XSS attack vectors, such as embedding a script within an iframe's srcdoc attribute. So modified it to handle those cases
Fixes [1615](https://linear.app/formbricks/issue/FOR-1615/fix-xss-security-issue)
Refer to Pdf in linear
> fix: updated cleanHtml script

- apps/web/app/(auth)/auth/forgot-password/reset/components/ResetPasswordForm/index.tsx
- apps/web/app/(auth)/auth/layout.tsx
Fixes [1603](https://linear.app/formbricks/issue/FOR-1603/add-confirm-password-field-to-the-password-reset-mask-to-confirm-that)
Reset password
> feat: adds confirm password field to password reset

- apps/web/sentry.client.config.ts
- apps/web/sentry.server.config.ts
> fix: ignore NEXT_NOT_FOUND error on sentry

- apps/formbricks-com/app/docs/api/management/responses/page.mdx
> style: Fix typo in docs

- apps/web/app/(app)/environments/[environmentId]/integrations/webhooks/components/testEndpoint.tsx
> fix: Update webhook test endpoint to conform to standard webhooks

- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/summary/components/SummaryMetadata.tsx
Basically just some minor fixes. I think that, while language is subjective, the updated strings are more concise.
Let me know if you have different thoughts :)
> style: Basic refactoring, a little tooltip fix, and some small language changes

- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/components/QuestionCard.tsx
Fixes [1490](https://linear.app/formbricks/issue/FOR-1490/ux-tweak-back-button-label-get-set-for-all-questions-next-button-label)
Change next button label for a question
It will automatically update all next button label for all question where next button label value is blank
You can also change it for particular questions
> feat: automatic next button label updation

- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/components/SurveyMenuBar.tsx
updates the error messages for logic jumps for clarity
> fix: update logic jump error message for clarity

- apps/formbricks-com/pages/api/oss-friends/index.ts
Add Langfuse to OSS friends list
n/a
n/a
n/a
> docs: add Langfuse to OSS friends

- apps/web/app/(app)/environments/[environmentId]/components/Navigation.tsx
- apps/web/app/(app)/environments/[environmentId]/components/ResponseFilterContext.tsx
- apps/web/app/(app)/environments/[environmentId]/people/[personId]/components/ResponseTimeline.tsx
- apps/web/app/(app)/environments/[environmentId]/settings/components/SettingsNavbar.tsx
- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/responses/components/ResponsePage.tsx
- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/responses/components/ResponseTimeline.tsx
- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/summary/components/ShareEmbedSurvey.tsx
- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/summary/components/SummaryDropOffs.tsx
- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/summary/components/SummaryPage.tsx
- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/components/CustomFilter.tsx
- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/components/ResponseFilter.tsx
- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/components/QuestionsView.tsx
- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/components/ResponseOptionsCard.tsx
- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/components/SurveyEditor.tsx
- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/components/WhenToSendCard.tsx
- apps/web/app/(app)/environments/[environmentId]/surveys/components/PreviewSurvey.tsx
- apps/web/app/(app)/onboarding/components/Greeting.tsx
- apps/web/app/(app)/share/[sharingKey]/(analysis)/responses/components/ResponsePage.tsx
- apps/web/app/(app)/share/[sharingKey]/(analysis)/responses/components/ResponseTimeline.tsx
- apps/web/app/(app)/share/[sharingKey]/(analysis)/summary/components/SummaryPage.tsx
- apps/web/app/(app)/share/[sharingKey]/components/CustomFilter.tsx
- apps/web/app/(auth)/auth/components/AzureButton.tsx
- apps/web/app/(auth)/auth/login/components/SigninForm.tsx
- apps/web/app/s/[surveyId]/components/LinkSurvey.tsx
Fixes [1561](https://linear.app/formbricks/issue/FOR-1561/fix-warnings-in-formbricks-build-process)
`pnpm lint`
> chore: lint warnings in web

- apps/web/app/(app)/environments/[environmentId]/components/Navigation.tsx
- apps/web/app/(app)/environments/[environmentId]/settings/members/components/AddMemberModal.tsx
- apps/web/app/(app)/environments/[environmentId]/settings/members/components/EditMemberships/MemberActions.tsx
- apps/web/app/(app)/environments/[environmentId]/settings/members/components/EditMemberships/MembersInfo.tsx
- apps/web/app/(app)/environments/[environmentId]/settings/members/components/ShareInviteModal.tsx
- apps/web/playwright/team.spec.ts
- apps/web/playwright/utils/helper.ts
- apps/web/playwright/utils/mock.ts
> feat: adds e2e test for invite functionality

- apps/web/app/storage/[environmentId]/[accessType]/[fileName]/route.ts
> feat: api key auth for private files

- apps/formbricks-com/app/docs/api/client/actions/page.mdx
- apps/formbricks-com/components/shared/MetaInformation.tsx
- apps/formbricks-com/pages/blog/inaugural-batch-github-accelerator/index.mdx
- canonical links
- duplicate page titles
> fix: seo issues to improve site health

- apps/formbricks-com/app/docs/best-practices/cancel-subscription/page.mdx
- apps/formbricks-com/app/docs/best-practices/feature-chaser/page.mdx
- apps/formbricks-com/app/docs/best-practices/improve-trial-cr/page.mdx
- apps/formbricks-com/app/docs/best-practices/interview-prompt/page.mdx
- apps/formbricks-com/app/docs/best-practices/pmf-survey/page.mdx
- apps/formbricks-com/pages/blog/best-feedback-app-and-how-to-use-them/index.mdx
- apps/formbricks-com/pages/blog/best-hotjar-alternatives-2024-incl-open-source/index.mdx
- apps/web/app/(app)/environments/[environmentId]/(actionsAndAttributes)/attributes/components/HowToAddAttributesButton.tsx
fix: linked to http instead of https
> fix: linked to http instead of https

- apps/formbricks-com/components/home/SetupTabs.tsx
- apps/web/app/(app)/environments/[environmentId]/settings/setup/components/SetupInstructions.tsx
Components now use the JS version from the `packages/js` directory rather than being hardcoded, thus making them up to date everytime.
- Test A
- Test B
> fix: replace hardcoded js versions with dynamic fetching

- apps/formbricks-com/pages/api/oss-friends/index.ts
Adds Lost Pixel OSS to the OSS friends list! Thanks a lot for this awesome initiative 🙌🏼
> docs: Add Lost Pixel to open source friends

- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/components/EditWelcomeCard.tsx
Fixes 
https://github.com/formbricks/formbricks/assets/67850763/8f73829d-47ff-48f4-8bd0-5173080abbd7
Refer to video above
> fix: unrespoonsive welcome card editor

- apps/web/app/(app)/environments/[environmentId]/surveys/components/Modal.tsx
> fix: avoid scaling on mobile preview

- apps/web/app/layout.tsx
- apps/web/package.json
- pnpm-lock.yaml
- turbo.json
chore: migrate to new Vercel speed insights package
> chore: migrate to new Vercel speed insights package

- apps/web/app/(app)/environments/[environmentId]/surveys/components/PreviewSurvey.tsx
- apps/web/app/s/[surveyId]/components/MediaBackground.tsx
Fixes [1661](https://linear.app/formbricks/issue/FOR-1661/bug-animated-backgrounds-broken)
test animated background
> fix: animated background issue

- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/components/CalQuestionForm.tsx
- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/components/FileUploadQuestionForm.tsx
- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/components/QuestionCard.tsx
- packages/surveys/src/components/questions/CalQuestion.tsx
- packages/surveys/src/components/questions/DateQuestion.tsx
- packages/surveys/src/components/questions/FileUploadQuestion.tsx
Adds missing functionality for image upload in file upload and cal question and also added image field in date question
Fixes [1674](https://linear.app/formbricks/issue/FOR-1674/add-optional-image-to-file-upload-type)
Test image upload in 
1. File upload
2. Cal Question
3. Date picker
> fix: added missing functionality for image upload in file upload and cal question

- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/actions.ts
- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/components/CustomFilter.tsx
- packages/lib/response/service.ts
Right now download response only download responses that are already loaded on response page but now we fetch all responses in batches of 3000 for the same
Fixes download responses
Test Download all
> fix: download response

- apps/web/app/(app)/environments/[environmentId]/(actionsAndAttributes)/actions/components/ActionClassesTable.tsx
- apps/web/app/(app)/environments/[environmentId]/(actionsAndAttributes)/actions/components/AddActionModal.tsx
- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/components/SettingsView.tsx
- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/components/WhenToSendCard.tsx
Shows a toast when someone try to create an action with a duplicate name
Fixes #1895 
Create an action with a name that already exist for some other action
> fix: warning for duplicate action name

- apps/web/app/api/v1/(legacy)/client/responses/route.ts
- apps/web/app/api/v1/client/[environmentId]/responses/route.ts
- packages/types/responses.ts
- packages/ui/SingleResponseCard/index.tsx
Adds support to get Country ISO 2 digit character from either Vercel/Cloudflare to the response metadata and shows it in the response view just like we show the source/other metadata.
1. Added custom header and made a response
2. Visible in the DB as
3. Visible in the UI as
Where should we mention in the docs that they'd need their service on Vercel or behind Cloudflare currently to get access to the country metadata?
- Add Custom header when testing because both CF & Vercel do not add headers to local deployments.
- Test A
- Test B
> feat: add country location to response metadata

- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/summary/components/FileUploadSummary.tsx
- packages/api/src/api/client/storage.ts
- packages/lib/storage/service.ts
- packages/lib/storage/utils.ts
- packages/surveys/src/components/general/FileInput.tsx
- packages/ui/FileInput/lib/fileUpload.ts
- packages/ui/FileUploadResponse/index.tsx
> fix: fixes duplicate named file uploads

- packages/surveys/package.json
- packages/surveys/src/components/questions/DateQuestion.tsx
- packages/surveys/vite.config.ts
> fix: adds vite dev mode

- apps/formbricks-com/lib/handleFeedbackSubmit.ts
Update the endpoint & payload required in the Formbricks Docs survey to get it back working
- Test A
- Test B
> fix: formbricks docs survey endpoint

- apps/formbricks-com/app/docs/integrations/google-sheets/page.mdx
Thanks to our community member, mforsetti 🥳, for pointing out that we missed an important point of enabling the Drive API for the Google Sheets integration to work. This PR adds the point.
> fix: (docs) mention google drive api for sheets integration in self host

- .github/workflows/release-docker-github.yml
- Current arm + amd docker builds take ~ 1 hour 10 minutes
- This PR uses depot.dev which has droped it down to a significant ~ 7 minutes on my fork [here](https://github.com/ShubhamPalriwala/formbricks/actions/runs/7541315528)
> feat: integrate depot.dev for faster docker arm builds

- .github/workflows/cron-reportUsageToStripe.yml
fix: update stripe usage report times to fix conflicts
> fix: update stripe usage report times to fix conflicts

- packages/ui/QuestionFormInput/index.tsx
Fixes [1736](https://linear.app/formbricks/issue/FOR-1736/bug-image-upload-visible-twice)
First upload an image to a question with subheader
Delete subheader
Again add a subheader
> fix: duplicate image issue

- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/components/EditWelcomeCard.tsx
Fixes [1740](https://linear.app/formbricks/issue/FOR-1740/bug-welcome-card-header-doesnt-allow-adding-full-width-image)
Changes fit from `cover` to `contain`
Upload image on welcome card
> fix: full width image issue on welcome card

- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/components/EditThankYouCard.tsx
- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/components/HiddenFieldsCard.tsx
- packages/lib/utils/recall.ts
- packages/ui/QuestionFormInput/components/FallbackInput.tsx
- packages/ui/QuestionFormInput/components/RecallQuestionSelect.tsx
Fixes [1744](https://linear.app/formbricks/issue/FOR-1744/bug-z-index-conflict-between-recall-and-hidden-fields)
For z-index issue
Try to enter a fallback in thank you card when hidden fields are present
For double fallback input
Enter a recall in headline
Then enter the recall question in subheader of same question
> fix: zindex issue and fallback input issue in recall

- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/components/LogicEditor.tsx
Fixes [1724](https://linear.app/formbricks/issue/FOR-1724/bug-logic-jump-dropdown-is-empty-but-it-still-works)
Test CSAT survey
> fix: empty logic editor issue

- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/responses/components/ResponsePage.tsx
- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/summary/components/ShareSurveyResults.tsx
- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/summary/components/SummaryPage.tsx
- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/components/ResultsShareButton.tsx
- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/components/SummaryHeader.tsx
- apps/web/app/(app)/share/[sharingKey]/layout.tsx
fixes https://github.com/formbricks/formbricks/issues/1926
by separating sharing survey and sharing results:
> fix: tweak sharing results UX

- packages/ui/SingleResponseCard/components/ResponseTagsWrapper.tsx
- packages/ui/SingleResponseCard/index.tsx
Fixes [1721](https://linear.app/formbricks/issue/FOR-1721/move-the-tag-settings-icon-on-the-left-hand-side-of-the-add-tag-button)
[1692](https://linear.app/formbricks/issue/FOR-1692/ui-tweak-reduce-delay-of-tooltip-when-blocking-of-delete-response)
https://github.com/formbricks/formbricks/assets/67850763/b2adb67c-3d39-4a4c-9a36-801d367cd063
Check single response card
Tags at bottom
Try to delete response in progress
> fix: response card tweaks

- apps/web/app/s/[surveyId]/components/LegalFooter.tsx
- apps/web/app/s/[surveyId]/components/PinScreen.tsx
- apps/web/app/s/[surveyId]/page.tsx
Fixes [1733](https://linear.app/formbricks/issue/FOR-1733/add-report-survey-button-to-link-survey-footer)
https://github.com/formbricks/formbricks/assets/67850763/2854626c-a235-4da9-a48f-f298358b3d27
Check link surveys for formbricks cloud
> feat: report survey link

- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/components/AnimatedSurveyBg.tsx
- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/components/ColorSurveyBg.tsx
- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/components/ImageSurveyBg.tsx
- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/components/SurveyBgSelectorTab.tsx
Fixes [1737](https://linear.app/formbricks/issue/FOR-1737/bug-background-image-isnt-displayed-ux-tweak)
https://github.com/formbricks/formbricks/assets/67850763/cd846e97-e86f-442f-949f-f4779fe83ed4
Toggle between color / animation / bgImage for survey in survey Editor
> fix: Improved UX for survey background selection

- apps/formbricks-com/app/docs/contributing/setup/page.mdx
Clean up typos & markdown formatting
-
> docs: typos & broken markdown formatting

- packages/js/src/lib/commandQueue.ts
> fix: error wrapper

- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/components/HiddenFieldsCard.tsx
- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/components/UpdateQuestionId.tsx
- apps/web/app/s/[surveyId]/components/LinkSurvey.tsx
- apps/web/app/s/[surveyId]/components/PinScreen.tsx
- apps/web/app/s/[surveyId]/components/VerifyEmail.tsx
- apps/web/app/s/[surveyId]/lib/helpers.ts
- apps/web/app/s/[surveyId]/page.tsx
- packages/lib/jwt.ts
- packages/ui/SingleResponseCard/index.tsx
Fixes #[1684](https://linear.app/formbricks/issue/FOR-1684/add-email-from-email-verification-to-the-response)
Test email verification survey
> chore: Adds verified email to response data for email verification surveys

- apps/formbricks-com/pages/privacy-policy.mdx
chore: add c.io to privacy policy
> chore: add c.io to privacy policy

- apps/web/app/(app)/environments/[environmentId]/settings/profile/lib.ts
Fixes the updated file name not being passed in the management storage api which lead to failed private file uploads
- Test A
- Test B
> fix: management storage api

- packages/ee/billing/handlers/subscriptionCreatedOrUpdated.ts
Consider a stripe subscription only if its active (ie the payment has went through at stripe)
> fix: only consider subscriptions if they are in active state

- packages/surveys/src/components/questions/RatingQuestion.tsx
Fixes [1799](https://linear.app/formbricks/issue/FOR-1799/optional-star-question-doesnt-work)
Test optional rating question with scale as star
> fix: stars issue in rating question

- .github/workflows/ecs-deployment.yml
> fix: ECS deployment Github Action

- .github/workflows/ecs-deployment.yml
> fix: ecs-deployment.yml

- apps/web/app/(app)/environments/[environmentId]/surveys/actions.ts
- apps/web/app/(app)/environments/[environmentId]/surveys/components/SurveyStarter.tsx
- apps/web/app/(app)/environments/[environmentId]/surveys/templates/TemplateList.tsx
- apps/web/app/(app)/environments/[environmentId]/surveys/templates/actions.ts
- packages/database/migrations/20240204084813_remove_creator_cascade_delete_in_survey/migration.sql
- packages/database/schema.prisma
- packages/lib/survey/service.ts
- packages/types/surveys.ts
fix: create survey API expects creator
- Create a survey via API
- Create a survey via UI
> fix: create survey API expects creator

- apps/formbricks-com/pages/api/oss-friends/index.ts
Adds classroomio.com to OSS friends.
We just hit 200 stars 🤩 🚀  and I'd love to be amongst the other amazing OSS friends.
- Go to the /api/oss-friends
- classroomio.com should be after cal.com
> docs: add ClassroomIO to OSS Friends

- apps/web/app/api/js/route.tsx
For self-hosting users seeking an alternative to utilizing unpkg.com as a CDN for the Formbricks pixel, this pull request addresses the current manual effort required for URL changes within the pixel files. The proposed enhancement streamlines the updating process for such users, enabling them to effortlessly serve the latest version by incorporating the following script into their web pages:
`<script async="" defer="" src="https://example.com/api/js?environmentId={environmentId}"></script>`
This newly introduced endpoint facilitates automatic updates, delivering the JavaScript with the correct version. Additionally, it initializes Formbricks directly with the accurate host and environmentId, resulting in a more elegant and efficient script for seamlessly integrating Formbricks into web …
> feat: Introduce Dynamic Pixel Server for Seamless Self-Hosting

- apps/web/app/api/v1/client/[environmentId]/in-app/sync/[userId]/route.ts
- apps/web/app/api/v1/client/[environmentId]/in-app/sync/lib/posthog.ts
- apps/web/app/api/v1/client/[environmentId]/in-app/sync/route.ts
fix: posthog free limit reporting
> fix: posthog free limit reporting

- apps/web/app/(app)/environments/[environmentId]/integrations/google-sheets/components/AddIntegrationModal.tsx
Fixes [1718](https://linear.app/formbricks/issue/FOR-1718/fix-spreadsheet-selection-option-can-only-handle-several-selections)
https://github.com/formbricks/formbricks/assets/67850763/8385d4c2-b463-4d77-9c6c-d373b4b112bc
Add too many spreadsheets
> fix: gs spreadsheet scroll issue

- packages/api/README.md
Introduces a README for the `@formbricks/api` package for easier visibility here as well as on the npmjs website for users to interact with it!
- Test A
- Test B
> docs: readme for @formbricks/api

- apps/web/app/(app)/environments/[environmentId]/settings/billing/components/PricingTable.tsx
- packages/ui/BillingSlider/index.tsx
- packages/ui/PricingCard/index.tsx
chore: tweak billing page for clarity
> chore: tweak billing page for clarity

- README.md
- apps/formbricks-com/app/docs/self-hosting/enterprise/page.mdx
- apps/formbricks-com/app/docs/self-hosting/license/page.mdx
- apps/formbricks-com/components/docs/Navigation.tsx
- apps/web/app/(app)/environments/[environmentId]/settings/members/components/AddMemberModal.tsx
- packages/ee/LICENSE
Add more information about the Open Source license (AGPLv3) and enterprise license to the Formbricks docs.
> docs: add more license information

- apps/formbricks-com/pages/blog/understanding-formbricks-self-hosting/index.mdx
chore: fix formbricks-com build issues
> chore: fix formbricks-com build issues

- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/components/AnimatedSurveyBg.tsx
- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/components/SurveyMenuBar.tsx
- apps/web/app/s/[surveyId]/components/MediaBackground.tsx
- packages/ui/ColorPicker/index.tsx
Fixes [1848](https://linear.app/formbricks/issue/FOR-1848/bug-animated-background-not-loading-error-modal)
[1841](https://linear.app/formbricks/issue/FOR-1841/bug-survey-not-publishing)
- Test A
- Test B
> fix: bg animation and publish survey issue

- apps/web/app/api/cron/weekly_summary/email.ts
Fixes [1806](https://linear.app/formbricks/issue/FOR-1806/investigate-bug-weekly)
[1864](https://linear.app/formbricks/issue/FOR-1806/investigate-bug-weekly)
This issue occurs when there are surveys for an account and email is viewed on smaller devices
This issue occurs for paused surveys
> fix: weekly template

- packages/surveys/src/components/questions/CTAQuestion.tsx
- packages/surveys/src/components/questions/CalQuestion.tsx
- packages/surveys/src/components/questions/ConsentQuestion.tsx
- packages/surveys/src/components/questions/DateQuestion.tsx
- packages/surveys/src/components/questions/FileUploadQuestion.tsx
- packages/surveys/src/components/questions/MultipleChoiceMultiQuestion.tsx
- packages/surveys/src/components/questions/MultipleChoiceSingleQuestion.tsx
- packages/surveys/src/components/questions/NPSQuestion.tsx
- packages/surveys/src/components/questions/OpenTextQuestion.tsx
- packages/surveys/src/components/questions/PictureSelectionQuestion.tsx
- packages/surveys/src/components/questions/RatingQuestion.tsx
Fixes [1816](https://linear.app/formbricks/issue/FOR-1816/bug-scroll-value-does-not-reset-between-questions)
Test with consecutive scrollable single select/ multi select questions
> fix: multi select scroll issue 

- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/components/LogicEditor.tsx
- packages/surveys/src/lib/logicEvaluator.ts
Fixes #2017 
Select single select
Add logic with option `include one of`
> chore: "include one of" option for single select

- apps/web/app/(app)/environments/[environmentId]/settings/lookandfeel/components/EditBranding.tsx
fix: update Upgrade Notifier in branding removal
> fix: update Upgrade Notifier in branding removal

- apps/formbricks-com/pages/api/oss-friends/index.ts
Page: https://www.prisma.io/oss-friends
> docs: add Prisma to OSS Friends

- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/components/TargetingCard.tsx
- packages/ee/advancedTargeting/components/AdvancedTargetingCard.tsx
- packages/lib/survey/service.ts
> fix: getSyncSurveys

- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/components/TargetingCard.tsx
- packages/database/migrations/20240207041922_advanced_targeting/data-migration.ts
- packages/ee/advancedTargeting/components/AdvancedTargetingCard.tsx
- packages/ui/Targeting/LoadSegmentModal.tsx
> fix: load segment modal UI fix

- apps/web/app/s/[surveyId]/components/VerifyEmail.tsx
- packages/ui/StackedCardsContainer/index.tsx
chore: Add StackedCardsContainer component
> chore: Add StackedCardsContainer component

- apps/formbricks-com/components/home/Hero.tsx
- apps/formbricks-com/components/home/Steps.tsx
- apps/formbricks-com/pages/_document.tsx
- apps/formbricks-com/pages/pricing.tsx
> fix: lp fixes and updates

- .github/workflows/ecs-deployment.yml
The value assigned to  image_tag_sha `image_tag_sha: ${{ steps.meta.outputs.tags }}` is inconsistent. It could either be latest or image SHA. If value is latest it doesn't allow for image being used inside the container to be identified. For now we will stick with SHA as the only tag to make debugging easier.
> fix: ECS Github Action

- apps/web/vercel.json
chore: reduce vercel memory usage
> chore: reduce vercel memory usage

- apps/formbricks-com/components/docs/Button.tsx
- apps/formbricks-com/components/docs/Libraries.tsx
> fix: (docs) dark mode hover states

- README.md
> chore: Add new logos to readme

- apps/web/app/storage/[environmentId]/[accessType]/[fileName]/lib/getFile.ts
Serving local files directly through Formbricks can lead to performance issues such as server overload and bandwidth congestion, especially as traffic increases. This can negatively impact user experience and scalability.
This PR introduces caching for the local file endpoint with a duration of 20 minutes. This means that frequently accessed files will be stored temporarily on intermediary servers or user devices, reducing the need to fetch them from the origin server every time.
- serve local file and check cache header
> feat: add Cache-Control header to public file serving

- apps/web/app/api/v1/client/[environmentId]/in-app/sync/[userId]/route.ts
- packages/js/src/lib/person.ts
hide attributes from sync endpoint
- Test A
- Test B
> fix: hide attributes from sync endpoint

- packages/ui/SurveysList/components/SurveyCard.tsx
fix: adjust name size in survey card
> fix: adjust name size in survey card

- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/components/EditWelcomeCard.tsx
- apps/web/next.config.mjs
- packages/lib/storage/service.ts
- packages/lib/storage/utils.ts
- packages/types/user.ts
For people self hosting formbricks and using the local storage (`uplaoads` directory) for file uploads, the next/image package throws errors about not being able to load the image because of an unrecognized url domain for the image. This happens because the next config is not able to add the domains for `WEB_APP_URL` at the runtime. 
This PR fixes the error for the local storage urls / images by transforming the local urls to use a relative path.
- Upload any image without S3 config, avatar or welcome card for example.
- Image should be rendered with the next/image package
> fix: adds relative image url path for self hosters without s3

- .github/workflows/release-docker-github-data-migration.yml
- packages/database/Dockerfile
- packages/database/package.json
- pnpm-lock.yaml
Add database migration dockerfile and github action to build it
> chore: Add database migration dockerfile

- .github/actions/dangerous-git-checkout/action.yml
- .github/workflows/build-web.yml
- .github/workflows/e2e.yml
- .github/workflows/lint.yml
- .github/workflows/pr.yml
- .github/workflows/test.yml
- README.md
> fix: github action

- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/components/EditWelcomeCard.tsx
- packages/surveys/src/components/general/HtmlBody.tsx
- packages/ui/Editor/components/ToolbarPlugin.tsx
Fixes [1890](https://linear.app/formbricks/issue/FOR-1890/bug-welcome-card-textarea-adds-new-line-on-every-render-open-links-in)
- Test A
- Test B
> fix: welcome card fixes

- apps/web/app/api/pipeline/lib/handleIntegrations.ts
Fixes google sheet integration readability issue for multiple file uploads
Test file upload question with multiple files allowed
> fix: gs readability issue for multiple file uploads

- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/components/LogicEditor.tsx
- packages/lib/utils/recall.ts
Fixes 
Use logic editor with recall questions
> fix: unformatted recall question in logic editor

- apps/web/app/(app)/environments/[environmentId]/settings/billing/unlimited99/page.tsx
- packages/ee/billing/handlers/checkoutSessionCompleted.ts
- packages/ee/billing/handlers/subscriptionCreatedOrUpdated.ts
- packages/ee/billing/lib/constants.ts
> feat: 99 unlimited plan

- apps/web/app/(app)/environments/[environmentId]/settings/billing/layout.tsx
- apps/web/app/(app)/environments/[environmentId]/settings/billing/page.tsx
- apps/web/app/(app)/environments/[environmentId]/settings/billing/unlimited/page.tsx
- apps/web/app/(app)/environments/[environmentId]/settings/billing/unlimited99/page.tsx
Check for authorization for the user to access any of the billing pages by moving the logics to the respective layout itself
- Test A
- Test B
> fix: authorization checks across all billing pages

- apps/web/app/api/v1/client/[environmentId]/in-app/sync/[userId]/route.ts
- packages/database/migrations/20240228180201_update_action_indexes/migration.sql
- packages/database/schema.prisma
- packages/lib/action/service.ts
- packages/lib/person/cache.ts
- packages/lib/person/service.ts
The read operations involving actions in Formbricks are very slow at the moment. This improvements to the sync endpoint and the database indexes of the action model should solve these issues.
> fix: update action indexes for faster query processing

- apps/formbricks-com/pages/api/oss-friends/index.ts
Fixes a typo in the OSS friends list.
> fix: Typo in OSS Friends API

- apps/web/app/(app)/environments/[environmentId]/settings/members/components/AddMemberModal.tsx
> fix: isCloud condition

- apps/web/vercel.json
fix: vercel-config failing on Vercel
> fix: vercel-config failing on Vercel

- packages/database/migrations/20240229141200_add_attribute_class_indexes/migration.sql
- packages/database/schema.prisma
- packages/lib/person/service.ts
improve person & attribute query performance by adding new indexes to attribute classes
> chore: improve person & attribute query performance

- apps/web/app/(app)/environments/[environmentId]/surveys/components/PreviewSurvey.tsx
- apps/web/app/s/[surveyId]/page.tsx
- packages/surveys/src/components/general/CalEmbed.tsx
- packages/surveys/src/components/questions/MultipleChoiceMultiQuestion.tsx
- packages/surveys/src/components/questions/MultipleChoiceSingleQuestion.tsx
- packages/surveys/src/components/questions/PictureSelectionQuestion.tsx
> fix: height issue

- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/components/SurveyMenuBar.tsx
> fix: remove naviate from save

- packages/lib/survey/service.ts
Fixes a bug which leads to an error when deleting a saved action. 
https://discord.com/channels/979077669410979880/1212792622901628968
https://github.com/formbricks/formbricks/assets/54475686/b545cc7b-4a19-47b1-bf65-afa4b0856dea
- Delete a saved action from a survey from the survey editor and click save
- The action should be deleted
> fix: saved actions

- apps/web/app/(app)/environments/[environmentId]/integrations/webhooks/components/AddWebhookModal.tsx
- apps/web/app/(app)/environments/[environmentId]/integrations/webhooks/components/WebhookSettingsTab.tsx
A webhook cannot be added if the test endpoint functionality fails! Currently we do not give the user the specific error message that caused it! This changes that by logging that as an error message in the client browser console for easier debigging!
> feat: show error on browser console for easier debugging for webhook test endpoint

- packages/lib/survey/service.ts
> fix: fixes duplicate survey segment

- apps/web/app/(app)/onboarding/components/PathwaySelect.tsx
- apps/web/app/(app)/onboarding/components/inapp/ConnectWithFormbricks.tsx
- apps/web/app/(app)/onboarding/components/inapp/InviteTeamMate.tsx
- apps/web/app/(app)/onboarding/components/inapp/SetupInstructions.tsx
- apps/web/app/(app)/onboarding/components/inapp/SurveyObjective.tsx
- apps/web/app/(app)/onboarding/components/inapp/SurveyRole.tsx
- apps/web/app/(app)/onboarding/components/link/CreateFirstSurvey.tsx
- packages/ui/OptionCard/index.tsx
chore: add css ids to onboarding
> chore: add css ids to onboarding

- packages/ui/SingleResponseCard/index.tsx
Fixes 
Before 
after 
Add a multi line response in open text question
> fix: break lines at new line character in single response card

- apps/web/app/(app)/environments/[environmentId]/surveys/page.tsx
Only get first page of surveys for survey list to fix issue for people having trouble to login or render their survey list when too many surveys are in the account.
We are working on a better solution to add server-side pagination to the surveys list.
> fix: only get first page of surveys for survey list

- packages/surveys/src/components/questions/RatingQuestion.tsx
fixes rating icon bug in safari
> fix: rating icon bug in safari

- packages/database/migrations/20240305135128_add_segment_id_index_to_surveys/migration.sql
- packages/database/schema.prisma
- packages/ee/advancedTargeting/lib/actions.ts
- packages/lib/segment/service.ts
- packages/lib/survey/service.ts
improve db indexes with segmentId index
> chore: improve db indexes with segmentId index

- apps/web/app/(app)/onboarding/components/inapp/ConnectWithFormbricks.tsx
- apps/web/app/(app)/onboarding/components/inapp/InviteTeamMate.tsx
- apps/web/app/(app)/onboarding/components/onboarding.tsx
fix: onboarding skips + track sdk setup success
> fix: onboarding skips + track sdk setup success

- apps/formbricks-com/app/docs/getting-started/framework-guides/page.mdx
- apps/web/app/(app)/environments/[environmentId]/settings/setup/components/SetupInstructions.tsx
- apps/web/app/api/js/route.tsx
- packages/js/index.html
Removes the old uncached `debug: true` method from docs!
> docs: remove old debug functionality

- apps/web/app/share/[sharingKey]/(analysis)/responses/components/ResponsePage.tsx
- apps/web/app/share/[sharingKey]/(analysis)/responses/page.tsx
- apps/web/app/share/[sharingKey]/(analysis)/summary/components/SummaryPage.tsx
- apps/web/app/share/[sharingKey]/(analysis)/summary/page.tsx
- apps/web/app/share/[sharingKey]/action.ts
- packages/lib/survey/service.ts
fixes unauthorized server actions
- can be tested by mocking the API call with invalid sharing key
> fix: added checks on unauthorized server actions

- packages/surveys/src/components/questions/RatingQuestion.tsx
rating question options size
Fixes
star and smileys size in rating question
> fix: rating question options size

- packages/surveys/src/components/questions/RatingQuestion.tsx
rating quese style hotfix
Fixes
> fix: rating quese style hotfix

- apps/formbricks-com/app/docs/self-hosting/external-auth-providers/page.mdx
Adds doucmentation for Azure SSO Integration with Formbricks
Fixes #1994
> docs: azure sso integration

- apps/web/Dockerfile
Use Supercronic from `apk` for auto detection of architecture rather than cURL for hardcoded package
- Test A
- Test B
> feat: support for supercronic in arm images

- apps/web/app/(app)/environments/[environmentId]/surveys/components/PreviewSurvey.tsx
- packages/surveys/src/components/general/AutoCloseProgressBar.tsx
- packages/surveys/src/components/wrappers/AutoCloseWrapper.tsx
- packages/surveys/src/styles/global.css
Fixes [1879](https://linear.app/formbricks/issue/FOR-1879/bug-auto-close-preview-is-not-working)
Also, current autoclose does not work outside preview as well (progressbar get stuck)
https://github.com/formbricks/formbricks/assets/67850763/92d08a80-12c9-4c27-a063-edb933217db0
Also refactored the progress logic, initially we were doing some calculations to derive progress value, changed it to use simple css animation
After fix:
https://github.com/formbricks/formbricks/assets/67850763/8c1bd0f1-e1d6-43f5-8152-a519aea36cec
Test preview with close on inactivity turned on
> fix: Autoclose issue

- apps/web/playwright/api/management/survey.spec.ts
- packages/lib/survey/service.ts
Fixes Incorrect created_at value while duplicating a survey
Created at value was copied from the original survey
Duplicate a survey
> fix: Incorrect created_at value while duplicating a survey

- packages/surveys/src/components/questions/MultipleChoiceMultiQuestion.tsx
- packages/surveys/src/components/questions/MultipleChoiceSingleQuestion.tsx
Fixes [1988](https://linear.app/formbricks/issue/FOR-1988/tweak-scroll-all-the-way-down-if-people-hit-other)
https://github.com/formbricks/formbricks/assets/67850763/993ab62b-46f8-43f2-8972-d0ed7be47ed1
https://github.com/formbricks/formbricks/assets/67850763/c3a13b6a-e488-4243-b4ba-9947926a7d1e
Select other option in multi select question
> fix: scroll to bottom when other option is selected

- apps/formbricks-com/pages/api/oss-friends/index.ts
> chore: update Requestly url in OSS Friends

- apps/web/app/api/v1/og/route.tsx
chore: add cache headers to og endpoint
> chore: add cache headers to og endpoint

- apps/formbricks-com/pages/open-source-form-builder/index.tsx
fix: remove duplicate text on link survey
> fix: remove duplicate text

- apps/web/playwright/js.spec.ts
- apps/web/playwright/survey.spec.ts
- apps/web/playwright/utils/helper.ts
> fix: fixes e2e tests

- packages/js/package.json
- packages/js/src/lib/noCodeActions.ts
fixes https://github.com/formbricks/formbricks/issues/2255
Fixes #2255
- Test A
- Test B
> fix: fix on-the-fly url trigger always triggering IMPORTANT

- apps/web/app/(app)/environments/[environmentId]/components/PosthogIdentify.tsx
- packages/lib/user/service.ts
- packages/types/user.ts
Adds the `role` & `objective` to the user properties in posthog!
- Test A
- Test B
> feat: add onboarding responses to user profiling in posthog

- .github/workflows/kamal.yml
- kamal/deploy.yml
chore: prepare kamal for production
> chore: prepare kamal for production

- .github/workflows/kamal.yml
- kamal/deploy.yml
> fix: add nextauth url to kamal

- packages/database/migrations/20240318050527_add_languages_and_survey_languages/data-migration.ts
fix: Increase multilanguage data migration timeout and merge both operations into one transaction
> fix: Increase multilanguage data migration timeout

- packages/lib/constants.ts
chore: change caching revalidation interval to 30minutes
> chore: change caching revalidation interval to 30minutes

- apps/web/app/s/[surveyId]/components/LinkSurvey.tsx
- apps/web/app/s/[surveyId]/components/VerifyEmail.tsx
Fixes Verify email issues #2287
Create email verification survey
> fix: verify email issues

- apps/web/app/(app)/environments/[environmentId]/(actionsAndAttributes)/attributes/components/AttributeClassesTable.tsx
- apps/web/app/(app)/environments/[environmentId]/(actionsAndAttributes)/attributes/components/AttributeDetailModal.tsx
- apps/web/app/(app)/environments/[environmentId]/(actionsAndAttributes)/attributes/components/AttributeRowData.tsx
- apps/web/app/(app)/environments/[environmentId]/(actionsAndAttributes)/attributes/components/AttributeTableHeading.tsx
- apps/web/app/(app)/environments/[environmentId]/(actionsAndAttributes)/attributes/components/HowToAddAttributesButton.tsx
- apps/web/app/(app)/environments/[environmentId]/(actionsAndAttributes)/attributes/components/UploadAttributesModal.tsx
- apps/web/app/(app)/environments/[environmentId]/(actionsAndAttributes)/attributes/page.tsx
Fixes [2048](https://linear.app/formbricks/issue/FOR-2048/bug-attribute-list-always-shows-archived-even-if-toggled-off)
Add more than 3 attributes
Archive some of them
Click on them when show archive toggle is off
> fix: archived attribute issue

- packages/surveys/vite.config.ts
fix: pull surveys package from formbricks cloud as a hotfix
> fix: pull surveys package from formbricks cloud as a hotfix

- apps/web/app/(app)/environments/[environmentId]/integrations/notion/components/AddIntegrationModal.tsx
- apps/web/app/s/[surveyId]/lib/prefilling.ts
integration and prefiling bug fix
Fixes 
- fixes prefiling bug
- fixes notion integration bug
- prefiling should work fine(especially for multi choice single select question)
- notion integration should work
> fix: integration and prefiling bug fix

- packages/lib/actionClass/service.ts
fix: unable to create actionClass due to caching issue
> fix: unable to create actionClass due to caching issue

- packages/database/migrations/20240318050527_add_languages_and_survey_languages/data-migration-range-fix.ts
- packages/database/package.json
> fix: added migration script to fix range in rating question

- apps/formbricks-com/components/salespage/HeaderLight.tsx
- apps/formbricks-com/components/shared/EnterpriseEditionInfo.tsx
- apps/formbricks-com/components/shared/OpenSourceInfo.tsx
- apps/formbricks-com/components/shared/PricingGetStarted.tsx
- apps/formbricks-com/components/shared/PricingTable.tsx
- apps/formbricks-com/pages/pricing.tsx
> fix: increase pricing clarity

- apps/formbricks-com/pages/vs-ohmyform.mdx
> fix: blog post - formbricks is actively developed

- apps/web/app/(app)/components/FormbricksClient.tsx
fix: add route change listener to formbricks integration
Fixes FOR-1647
> fix: add route change listener to formbricks integration

- apps/formbricks-com/components/shared/Footer.tsx
The Footer link pointed to /blog before.
- Test A
- Test B
> fix: Docs footer link points to blog

- apps/web/app/(app)/environments/[environmentId]/integrations/webhooks/page.tsx
fix: webhooks page breaking with too many surveys in the env
> fix: webhooks page breaking with too many surveys in the env

- packages/lib/constants.ts
chore: increase service caching period to 3 hours
> chore: increase service caching period to 3 hours

- packages/ui/Editor/components/ToolbarPlugin.tsx
Fixes [1708](https://linear.app/formbricks/issue/FOR-1706/fix-rich-text-editor-shouldnt-take-formatting)
Before:
https://github.com/formbricks/formbricks/assets/67850763/1a2997b9-1c41-482c-9b60-fd1ef83a84e8
After:
https://github.com/formbricks/formbricks/assets/67850763/e03fc785-d2c6-4acb-9e93-098be3d48d8e
Try to paste a formatted text in editor (thank you card, consent, cta)
> fix: discard formatting on paste in Lexical Editor

- packages/lib/response/util.ts
fix: question header in csv export
> fix: question header in csv export

- apps/formbricks-com/pages/blog/why-open-source-no-code-is-the-future-of-enterprise-gov-software/index.mdx
> chore: add link

- packages/js/src/lib/actions.ts
- packages/js/src/lib/noCodeActions.ts
- packages/js/src/lib/widget.ts
fix: displayPercentage not working for inline-triggers
Fixes https://github.com/formbricks/formbricks/issues/2264
> fix: displayPercentage not working for inline-triggers

- apps/demo/pages/app/index.tsx
- apps/web/app/(app)/environments/[environmentId]/surveys/templates/templates.ts
- apps/web/app/api/v1/client/[environmentId]/in-app/sync/[userId]/route.ts
- apps/web/app/api/v1/client/[environmentId]/in-app/sync/route.ts
- packages/database/schema.prisma
- packages/lib/action/service.ts
- packages/lib/person/cache.ts
- packages/lib/survey/service.ts
- packages/lib/team/service.ts
optimize sync endpoint performance by adding fast failing and more indexes based on the most used queries
> chore: optimize sync endpoint performance

- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/summary/lib/emailTemplate.tsx
- apps/web/app/s/[surveyId]/lib/prefilling.ts
- packages/surveys/src/components/general/QuestionConditional.tsx
- packages/surveys/src/components/questions/MultipleChoiceSingleQuestion.tsx
- added others option in share embed survey
- added new cal question preview in embed modal
- added file upload question preview in embed modal 
https://github.com/formbricks/formbricks/assets/56182734/e010e1a0-596b-4d05-9609-30ea9958ddff
Fixes 
https://linear.app/formbricks/issue/FOR-2056/fix-first-question-preview-in-share-embed-modal
> fix: first question preview in share embed modal

- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/responses/components/ResponsePage.tsx
- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/responses/components/ResponseTimeline.tsx
- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/responses/page.tsx
- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/summary/components/SummaryList.tsx
- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/summary/components/SummaryPage.tsx
- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/summary/page.tsx
- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/components/QuestionFilterComboBox.tsx
- apps/web/app/lib/surveys/surveys.ts
- apps/web/app/share/[sharingKey]/(analysis)/responses/components/ResponsePage.tsx
- apps/web/app/share/[sharingKey]/(analysis)/responses/components/ResponseTimeline.tsx
- apps/web/app/share/[sharingKey]/(analysis)/responses/page.tsx
- apps/web/app/share/[sharingKey]/(analysis)/summary/components/SummaryPage.tsx
- apps/web/app/share/[sharingKey]/(analysis)/summary/page.tsx
- packages/ui/EmptySpaceFiller/index.tsx
- packages/ui/SkeletonLoader/index.tsx
No responses due to filter state
Added:
- loading and empty state on summary page
- loading and empty state on response page
Fixes
https://linear.app/formbricks/issue/FOR-1933/no-responses-due-to-filter-state
- try adding different set of filters on the analysis pages(summary and response)
> feat: No responses due to filter state

- apps/formbricks-com/app/docs/self-hosting/migration-guide/page.mdx
fix: migration image name in migration docs
> fix: migration image name in migration docs

- apps/web/next.config.mjs
- apps/web/package.json
- pnpm-lock.yaml
fix: packages api endpoint on vercel
> fix: packages api endpoint on vercel

- packages/lib/i18n/reverseTranslation.ts
- packages/lib/i18n/utils.ts
- packages/lib/survey/service.ts
- packages/types/surveys.ts
> fix: hotfix for sync validation errors

- packages/ui/ColorPicker/index.tsx
> chore: cleanup css console log

- .github/workflows/kamal-setup.yml
GitHub action that needs to be called manually to setup/restart the accessories in Kamal
- Test A
- Test B
> feat: kamal setup workflow

- apps/web/app/api/v1/client/[environmentId]/responses/route.ts
- packages/js-core/src/lib/actions.ts
- packages/js-core/src/lib/widget.ts
- packages/types/responses.ts
- packages/ui/SingleResponseCard/index.tsx
- pnpm-lock.yaml
Includes the action name which triggered a survey in the response create meta object.
- Trigger a survey by performing an action (in-app survey) and submit a response
- The action name should be visible in the dashboard
> fix: adds action to response meta

- packages/surveys/src/components/general/Survey.tsx
Fixes #2338 
Recall answer from first question into second and pre-fill first question
> fix: recall not working with prefilled answer

- apps/formbricks-com/app/docs/api/management/surveys/page.mdx
- apps/web/app/(app)/environments/[environmentId]/surveys/templates/templates.ts
- apps/web/app/lib/questions.ts
- packages/surveys/src/components/general/FileInput.tsx
- packages/surveys/src/components/general/Headline.tsx
- packages/surveys/src/components/general/QuestionConditional.tsx
- packages/surveys/src/components/questions/NPSQuestion.tsx
- packages/surveys/src/components/questions/RatingQuestion.tsx
- packages/surveys/src/styles/preflight.css
- packages/ui/RatingResponse/index.tsx
Fixes following issues:
1. default NPS quesiton:
-----
2. CTA question doesn't have a text by default
-------
3. Unusual red frame for file upload
4. replace color with styled color
5. replace with filled star  (not only outline). It's ok to custom SVG component for this this lucide doesnt provide
-------
Test above mentioned issues
> fix: Survey editor tweaks

- kamal/deploy.yml
chore: remove REDIS_CLIENT_URL from kamal
> chore: remove REDIS_CLIENT_URL from kamal

- package.json
- packages/database/package.json
- turbo.json
Removes existence of `db:migrate:proxy`
- Test A
- Test B
> fix: use MIGRATE_DB_URL if present else fallback to DB_URL in migrate:deploy

- apps/web/app/s/[surveyId]/loading.tsx
fix: responsiveness of loading skeleton on link survey
> fix: responsiveness of loading skeleton on link survey

- apps/web/app/(app)/environments/[environmentId]/surveys/components/SurveyStarter.tsx
- apps/web/app/(app)/environments/[environmentId]/surveys/templates/TemplateList.tsx
solves https://github.com/formbricks/formbricks/issues/2360
> chore: remove auto capping surveys

- kamal/deploy.yml
increase kamal pgbouncer connection pool to avoid
fixes formbricks/internal#33
> chore: increase kamal pgbouncer connection pool

- apps/formbricks-com/app/docs/api/management/surveys/page.mdx
Curl was POST but method is PUT - changed it to be what is needed
n/a small docs change
> fix: curl example message for `update survey by id`

- apps/web/next.config.mjs
Allows Link Survey Embeddings on non Formbricks webpages
- Test A
- Test B
> fix: allow survey embeddings on other webpages

- .github/actions/cache-build-web/action.yml
The GitHub actions now cache & reuse builds across the repo
- Test A
- Test B
> feat: web builds across GitHub Action are cross branch now

- .github/workflows/kamal-deploy.yml
> feat: allow manual trigger of kamal deploy

- apps/web/app/middleware/rateLimit.ts
- packages/lib/constants.ts
> fix: constants timeframe in seconds

- apps/formbricks-com/app/docs/integrations/slack/page.mdx
- apps/web/app/(app)/environments/[environmentId]/integrations/slack/components/Home.tsx
fix: ui tweaks slack integration
> fix: ui tweaks slack integration

- kamal/deploy.yml
increase kamal pgbouncer pool size to 100 to handle db peaks
> chore: increase kamal pgbouncer pool size to 100

- packages/lib/constants.ts
increase service revalidation interval to 24 hours to reduce the number of cache refreshes.
the service revalidation interval is only a fallback, if the revalidation on data edit isn't working for some reason. since it's working well we are slowly increasing the limit.
- Test A
- Test B
> chore: increase service revalidation interval to 24 hours

- apps/web/next.config.mjs
move cacheHandler to a conditional import to make it easier to read and avoid edge cases with undefined values
> chore: move cacheHandler to a conditional import

- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/responses/components/ResponsePage.tsx
- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/summary/components/SummaryPage.tsx
- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/components/CustomFilter.tsx
- apps/web/app/s/[surveyId]/lib/prefilling.ts
- fixes single survey card rerenders on tag add or delete
Fixes #2384 
https://github.com/formbricks/formbricks/assets/56182734/0cc01730-d08a-40b1-9f64-5081b386db62
- Add or delete tags from the response, it shouldn't rerender
> fix: single survey card rerenders on tag add or delete

- apps/formbricks-com/pages/privacy-policy.mdx
chore: add Google disclosure to privacy policy to get Google Sheets app verified
> chore: add Google disclosure to privacy policy

- apps/web/app/[shortUrlId]/page.tsx
fixes this sentry bug which was seen the most number of times in the last 30 days:
https://formbricks.sentry.io/issues/5162808027/?query=is%3Aunresolved&referrer=issue-stream&sort=freq&statsPeriod=30d&stream_index=0
- Test A
- Test B
> fix: fixes `shortUrl` not defined in metadata

- apps/formbricks-com/mdx/rehype.mjs
- apps/formbricks-com/package.json
- pnpm-lock.yaml
fix formbricks-com build errors caused by recent npm updates
> fix: formbricks-com build errors

- packages/ui/SingleResponseCard/components/ResponseTagsWrapper.tsx
- packages/ui/SingleResponseCard/index.tsx
- packages/ui/Tag/index.tsx
Added logic to show tags for viewer role
Fixes #2415 
- Check the response sharing page of any survey, response tags should be visible
> feat: added logic to show tags for viewer role

- apps/web/app/(app)/environments/[environmentId]/integrations/airtable/components/AddIntegrationModal.tsx
> fix: rename airbase to airtable

- packages/lib/utils/validate.ts
chore: improve validation error logging
> chore: improve validation error logging

- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/summary/actions.ts
The `to` user must have an active session to receive the preview email
- Test A
- Test B
> fix: email previews to only be sent to the session user

- apps/formbricks-com/app/docs/getting-started/framework-guides/page.mdx
- apps/web/app/(app)/environments/[environmentId]/settings/setup/components/SetupInstructions.tsx
- apps/web/app/(app)/onboarding/components/inapp/SetupInstructions.tsx
fix: remove the --save flag because deprecated
> fix: remove the --save flag because deprecated

- apps/web/app/s/[surveyId]/components/LegalFooter.tsx
- apps/web/app/s/[surveyId]/components/LinkSurvey.tsx
- apps/web/app/s/[surveyId]/page.tsx
fix: legal footer overlaying buttons on smaller screens
> fix: legal footer overlaying buttons on smaller screens

- apps/web/app/s/[surveyId]/components/LinkSurvey.tsx
> fix: fix-logo

- apps/web/app/(auth)/auth/signup/components/SignupForm.tsx
Fixes [this](https://formbricks.sentry.io/issues/4595309995/?project=4505622920560640&query=is%3Aunresolved&referrer=issue-stream&sort=freq&statsPeriod=30d&stream_index=2) sentry issue where the `formRef.current.requestSubmit` function is not working as it is not supported by safari. This change introduces two buttons, one for just the continue which updates the state and another for submitting the form.
- Go to the signup form and choose continue with email
- It should work on safari!
> fix: fixes form submission

- .github/workflows/kamal-deploy.yml
- .github/workflows/kamal-setup.yml
- kamal/README.md
- kamal/deploy.yml
Draft: still under development & testing
run kamal setup behind load balancer with multiple instances
> chore: run kamal setup behind load balancer with multiple instances

- apps/formbricks-com/app/[surveyId]/route.ts
- apps/formbricks-com/next.config.mjs
fixing legacy survey redirect links from formbricks.com. Replacing old rewrite with a dynamic redirect.
> fix: legacy survey redirect links from formbricks.com

- packages/js/src/index.ts
Fixes [this](https://formbricks.sentry.io/issues/5146493463/?query=is%3Aunresolved&referrer=issue-stream&sort=freq&statsPeriod=30d&stream_index=6) sentry issue where the `apiHost` is not available in the method that the proxy calls, this happens when some method on the formbricks SDK is called before calling `formbricks.init`. This change checks both if the method is not `init` and if the `apiHost` isn't available.
- From the demo app for example, call any other formbricks function before the init function
- No errors should be thrown, instead an error should be logged to the console.
> fix: fixes js package proxy

- .github/workflows/cron-reportUsageToStripe.yml
- .github/workflows/cron-surveyStatusUpdate.yml
- .github/workflows/cron-weeklySummary.yml
deactivate github action crons (since this is not needed in the kamal setup for now)
> chore: deactivate github action crons

- apps/web/app/(app)/environments/[environmentId]/components/Navigation.tsx
fix: remove double team switch, update route
> fix: remove double team switch, update route

- kamal/deploy.yml
chore: add forth instance to kamal
> chore: add forth instance to kamal

- apps/formbricks-com/app/docs/api/management/api-key-setup/page.mdx
fix: A bug fix
It was a escape error in the
`formbricks/apps/formbricks-com/app/docs/api/management/api-key-setup/page.mdx` line no `35`
Fixes #2497
- Test A
the frameworks.com site should be compiled to see the change.
- Test B
> docs: Missing new line in management API docs

- kamal/deploy.yml
> chore: scale kamal instance

- apps/web/app/api/v1/(legacy)/js/sync/lib/sync.ts
fixes backwards compatibility for a very old sync endpoint, that still fetches "web" surveys. Changes it to fetch either "app" or "website" surveys.
- Test A
- Test B
> fix: Backwards compatibility for js/sync endpoint

- packages/surveys/src/components/questions/PictureSelectionQuestion.tsx
Fixes https://github.com/formbricks/internal/issues/107
https://github.com/formbricks/formbricks/assets/67850763/42563772-3c6b-455c-bb32-c390015febaa
We already had code to show the expand icon on hover, but the parent was missing the class `group/image` , due to which it wasn't really working
Hover on images in picture select question
> fix: picture select grow icon opacity issue

- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/components/SurveyMenuBar.tsx
fixes a bug in which a segment is not getting saved with a survey.
https://github.com/formbricks/formbricks/assets/54475686/1cabad79-8b61-43e6-9065-c88271a9bb06
- Create an inline segment
- Save the survey
> fix: fixes segment not getting saved bug

- packages/lib/attribute/service.ts
> fix: attribute service not filtering by environmentId

- packages/lib/attribute/service.ts
use attributeClass service in updateAttributes method to optimize query performance and reduce database calls since the service is cached.
> chore: use attributeClass service in updateAttributes function

- apps/formbricks-com/app/docs/self-hosting/enterprise/page.mdx
> fix: update EE docs

- packages/ui/SingleResponseCard/index.tsx
> chore: increase tooltip area

- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/components/SurveyMenuBar.tsx
Fixes the current survey switching bug that's on production right now. 
- Test A
- Test B
> fix: survey switch

- apps/web/app/api/v1/client/[environmentId]/app/sync/[userId]/route.ts
Fixes an internal server error, because of a validation error in the app sync route, this fixes it by removing that old code, which is not relevant to the app surveys anymore.
- Make a new product, so that a new environment is created (or sign up 🤓 )
- Connect the new environment to the demo app, it should not throw an internal server error  in the sync route.
> fix: app surveys internal server error

- packages/js-core/app.vite.config.ts
- packages/js-core/website.vite.config.ts
- packages/js/vite.config.ts
- packages/surveys/vite.config.ts
Inlines the api package type declarations in the js-core package, using the `bundledPackages` option in the vite-plugin-dts options.
- Test A
- Test B
> fix: bundles api package with js-core

- apps/formbricks-com/components/home/Hero.tsx
- apps/formbricks-com/components/salespage/LogoBar.tsx
- apps/formbricks-com/tailwind.config.ts
> chore: made logos move

- packages/lib/survey/service.ts
Fixes an issue where a survey with no filters was not getting fetched from the sync endpoint, because the `evaluateSegment` method was getting called with empty filters and it returned false.
- Test A
- Test B
> fix: segment filtering

- apps/web/app/s/[surveyId]/components/MediaBackground.tsx
moved the img in the media background to next Image. The idea is to load it from Unsplash on our server for better privacy.
> chore: replace img with next Image

- packages/surveys/src/components/wrappers/Modal.tsx
Adds `z-index` to the modal close button in the survey modal component, fixes the bug that the close button was not clickable.
- Test A
- Test B
> fix: adds z-index to modal close button

- packages/ui/QuestionFormInput/utils.ts
Fixes #2575
Add logo on welcome card
> fix: image uploader on welcome card

- packages/ui/QuestionFormInput/index.tsx
Fixes https://github.com/formbricks/internal/issues/143
Try to add recall question on ty card
> fix: recall not working on thank you card

- apps/docs/components/Navigation.tsx
fix: docs hover color dark mode
> fix: docs hover color dark mode 

- packages/surveys/src/components/questions/MultipleChoiceMultiQuestion.tsx
Fixes other option not working in multiSelect multi question
Test other option in multi select multi question
> fix: other option not working in multiSelect multi question

- apps/web/app/(app)/(survey-editor)/environments/[environmentId]/surveys/templates/components/TemplateContainer.tsx
Fixes blank preview issue
Check Survey template page
https://github.com/formbricks/formbricks/assets/67850763/da37003e-68dd-437e-9ad5-3a0e014fda38
> fix: blank preview issue

- packages/ui/SingleResponseCard/index.tsx
Fixes https://github.com/formbricks/internal/issues/176
Hover on single response card user profile
> fix: zindex issue on respone page

- apps/web/app/(app)/onboarding/components/inapp/SetupInstructions.tsx
update setup instructions in onboarding for formbricks 2.0
> fix: update setup instructions in onboarding for formbricks 2.0

- apps/docs/app/self-hosting/migration-guide/page.mdx
chore: add upgrade hint in docs
> chore: add upgrade hint in docs

- packages/ui/Modal/index.tsx
Fixes the z-index issue with the new modal component leading to issues like the delete response modal being below the response card.
- Test A
- Test B
> fix: modal z-index

- docker/docker-compose.yml
A New Postgres Instance failed to start because of a missing Postgres superuser Password environment variable. This PR sets it and adds a comment for the user to change it.
- Test A
- Test B
> fix: define postgres super user password for v2 runs

- apps/docs/app/developer-docs/integrations/airtable/page.mdx
- apps/docs/app/developer-docs/integrations/google-sheets/page.mdx
- apps/docs/app/developer-docs/integrations/make/page.mdx
- apps/docs/app/developer-docs/integrations/n8n/page.mdx
- apps/docs/app/developer-docs/integrations/notion/page.mdx
- apps/docs/app/developer-docs/integrations/slack/page.mdx
- apps/docs/app/self-hosting/integrations/page.mdx
- apps/web/app/(app)/environments/[environmentId]/integrations/airtable/components/Connect.tsx
- apps/web/app/(app)/environments/[environmentId]/integrations/google-sheets/components/Connect.tsx
- apps/web/app/(app)/environments/[environmentId]/integrations/notion/components/Connect.tsx
- apps/web/app/(app)/environments/[environmentId]/integrations/slack/components/Connect.tsx
fix: update links for integrations
> fix: update links for integrations

- apps/docs/components/Layout.tsx
- apps/docs/components/MobileNavigation.tsx
- apps/docs/components/Navigation.tsx
- On mobile: On clicking a group in navbar, the drop down opens and a user can select a page
- On PC: On clicking a group, the first page opens
Also now, only the selected group's list is opened and not all
Fixes https://github.com/formbricks/internal/issues/162
> fix: navbar on mobile docs for grouped features

- apps/web/app/(app)/environments/[environmentId]/(people)/people/[personId]/components/AttributesSection.tsx
- packages/surveys/src/components/questions/RatingQuestion.tsx
Fixes rating question lower and upper always being displayed in default language
Check rating question in multi language
> fix: rating question and updated attribute labels on person page

- apps/docs/app/developer-docs/integrations/airtable/page.mdx
- apps/docs/app/developer-docs/integrations/google-sheets/page.mdx
- apps/docs/app/developer-docs/integrations/notion/page.mdx
- apps/docs/app/developer-docs/integrations/overview/page.mdx
- apps/docs/app/developer-docs/integrations/slack/page.mdx
fix: fix links to integrations on docs
> fix: fix links to integrations on docs

- apps/web/app/api/v1/(legacy)/client/responses/route.ts
- apps/web/app/api/v1/client/[environmentId]/responses/route.ts
Fixes https://github.com/formbricks/formbricks/issues/2674
- check device type for response made from a desktop device
- Test B
> fix: set "desktop" as default device type

- apps/docs/app/self-hosting/docker/page.mdx
docs: update advanced docker update steps
> docs: update advanced docker update steps

- packages/surveys/src/components/wrappers/ScrollableContainer.tsx
- packages/surveys/src/components/wrappers/StackedCardsContainer.tsx
- packages/surveys/src/styles/global.css
- packages/ui/SurveysList/components/SurveyCard.tsx
Fixes 
https://github.com/formbricks/internal/issues/121
https://github.com/formbricks/formbricks/assets/67850763/0c2734cc-69f7-4b20-a492-41df683d4991
Adds truncate to very long Survey name on survey list 
Simple card arrangement breaking
Test above mentioned issues
> fix: ui issues

- apps/web/app/api/v1/(legacy)/client/[environmentId]/people/[userId]/route.ts
- packages/api/src/api/client/attribute.ts
- packages/js-core/src/app/lib/attributes.ts
- packages/types/attributes.ts
fix: convert number attributes to strings automatically
> fix: convert number attributes to strings automatically

- packages/lib/utils/recall.ts
- packages/ui/QuestionFormInput/components/RecallQuestionSelect.tsx
We recently made a change, where we now allow `-` and `_` in questionId but that was not supported in recall functionality. As a result survey editor gets stuck. Extended recall functionality to support them as well
For the z-index issue, instead of setting z-index, height of recall question select dropdown is restricted, so that it does not looks broken.
Try to recall from question whose id consist of `-` or `_`
> fix: recall issues

- apps/web/next.config.mjs
chore: cache improvements 
- setting stale time for dynamic cache to 0
- comment out instrumentation for now as it is not used
> chore: cache improvements

- apps/docs/app/self-hosting/license/page.mdx
- apps/web/app/(app)/(survey-editor)/environments/[environmentId]/surveys/[surveyId]/edit/components/TargetingCard.tsx
- apps/web/app/(app)/environments/[environmentId]/(people)/people/[personId]/components/ActivityTimeline.tsx
- apps/web/app/(app)/environments/[environmentId]/(people)/segments/components/BasicCreateSegmentModal.tsx
- apps/web/app/(app)/environments/[environmentId]/(people)/segments/components/BasicSegmentSettings.tsx
- apps/web/app/(app)/environments/[environmentId]/components/MainNavigation.tsx
- apps/web/app/(app)/environments/[environmentId]/settings/(team)/enterprise/page.tsx
- apps/web/app/(app)/environments/[environmentId]/settings/(team)/members/components/IndividualInviteTab.tsx
- packages/ee/multiLanguage/components/MultiLanguageCard.tsx
chore: setup EE license funnel with infos on 30 day trial
> chore: EE license trial info on settings etc.

- apps/web/app/(app)/environments/[environmentId]/settings/(team)/members/components/EditMemberships/TeamActions.tsx
- apps/web/next.config.mjs
- packages/surveys/src/styles/date-picker.css
Fixes alignment and bg color for the selected date
Before 
After 
Also fixes alignment of button on team invite page
test above mentioned issues
> fix: date picker tweaks

- .github/workflows/release-docker-github.yml
- .github/workflows/release-docker.yml
- apps/docs/app/self-hosting/migration-guide/page.mdx
fix: docker release github action not adding latest tag
> fix: docker release github action not adding latest tag

- apps/web/vercel.json
Increase maxDuration for cron functions to 180 seconds
- Test A
- Test B
> chore: Increase maxDuration for cron functions to 180 seconds

- apps/docs/app/link-surveys/data-prefilling/page.mdx
Adds skipPrefilled docs
Fixes 
https://github.com/formbricks/internal/issues/200
- Test A
- Test B
> docs: adds skipPrefilled docs

- packages/surveys/src/components/wrappers/StackedCardsContainer.tsx
Fixes https://github.com/formbricks/internal/issues/212
initially we used to render all the questions at once but now we only render the current question and 3 neighbouring questions
Survey with 300 questions 
https://github.com/formbricks/formbricks/assets/67850763/90fe6e18-d76c-4e89-8734-c1ca11560d62
Test survey with too many questions
> chore: optimized survey card animation

- apps/docs/app/self-hosting/custom-ssl/page.mdx
- apps/docs/lib/navigation.ts
docs: add tutorial for custom SSL certificates
> docs: add tutorial for custom SSL certificates

- apps/web/app/(app)/environments/[environmentId]/integrations/notion/components/AddIntegrationModal.tsx
- apps/web/app/(app)/environments/[environmentId]/integrations/notion/constants.ts
- apps/web/app/api/pipeline/lib/handleIntegrations.ts
Fixes : Application crashes when we try to add a date question in notion integration due to lack for support for new question types
Also adds a more descriptive warning if type of selected question is not compatible with select notion column
Before
After 
Now we also tell, what should be the target column instead of just showing the warning
Test date, matrix and address question
> fix: added support for date, matrix, address and cal question to notion integration

- .github/workflows/release-docker-github-experimental.yml
- packages/ee/lib/service.ts
- packages/ee/package.json
- pnpm-lock.yaml
The ee license check is currently not working when Formbricks is used behind a proxy.
This PR introduces a switch from fetch to axios to respect the proxy settings set via environment variables `HTTP_PROXY` & `HTTPS_PROXY`.
> fix: ee server not reachable behind a proxy

- packages/email/index.tsx
> fix: modified IS_SMTP_CONFIGURED to only check for port and host

- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/summary/components/RatingSummary.tsx
Adds average rating to rating question
Fixes #2643 
- Test A
- Test B
> feat: adds average rating to rating question

- apps/web/app/(app)/(survey-editor)/environments/[environmentId]/surveys/[surveyId]/edit/components/LogicEditor.tsx
- packages/surveys/src/components/questions/OpenTextQuestion.tsx
Before 
After
Fixes 
test above mentioned issues
> fix: UX improvement for logic jump settings

- apps/web/app/(auth)/invite/page.tsx
fixes: Invite can't handle + sign in emails
Fixes
https://github.com/formbricks/internal/issues/225
- Test A
- Test B
> fix: email url encoding in invite link

- apps/web/app/share/[sharingKey]/(analysis)/responses/page.tsx
- apps/web/app/share/[sharingKey]/(analysis)/summary/page.tsx
- packages/ui/SecondaryNavigation/index.tsx
Fixes response publish issue
initially on opening the share page after publishing, app crashes because we tries to access `environmentId` from params that does not exist
Test response publish page (summary and responses)
> fix: responses publish

- apps/web/app/(app)/(survey-editor)/environments/[environmentId]/surveys/[surveyId]/edit/components/CreateNewActionTab.tsx
- packages/ui/TabToggle/index.tsx
- packages/ui/organisms/NoCodeActionForm/components/PageUrlSelector.tsx
- packages/ui/organisms/NoCodeActionForm/index.tsx
Tab toggle component structure
- Test A
- Test B
> fix: tab toggle component structure

- packages/ee/package.json
- pnpm-lock.yaml
fix: add missing dependency in ee package
> fix: add missing dependency in ee package

- apps/web/app/s/[surveyId]/components/LinkSurvey.tsx
- packages/surveys/src/components/general/Survey.tsx
- packages/types/formbricksSurveys.ts
- packages/ui/QuestionFormInput/components/RecallItemSelect.tsx
- packages/ui/QuestionFormInput/index.tsx
**Some of the changes made in `feat: recall from hidden fields` were somehow reverted**
Fixes recall from hidden field not working and recall question highlight
Test recall from hidden fileds
> fix: recall from hidden fields

- apps/web/app/s/[surveyId]/components/LegalFooter.tsx
- packages/surveys/src/components/general/Survey.tsx
fixes top padding
links Report Survey to this one: https://app.formbricks.com/s/clxbivtla014iye2vfrn436xd
> fix: survey padding and add report survey

- apps/web/app/api/v1/users/route.ts
- packages/lib/product/service.ts
product creation bug
- Test A
- Test B
> fix: product creation bug

- packages/lib/organization/service.ts
fixes the `getMonthlyActiveOrganizationPeopleCount` service for now
- Test A
- Test B
> fix: getPersonCount

- apps/web/app/(app)/(survey-editor)/environments/[environmentId]/surveys/[surveyId]/edit/components/QuestionsStylingSettingsTabs.tsx
- apps/web/playwright/js.spec.ts
- apps/web/playwright/survey.spec.ts
- apps/web/playwright/utils/helper.ts
fixes e2e tests
- Test A
- Test B
> fix: e2e tests

- packages/surveys/src/styles/global.css
- packages/ui/Editor/stylesEditorFrontend.css
Fixes 
After 
Test editor text with different question color settings
> fix: editor text color

- packages/ui/PricingCard/index.tsx
fix: orange css for offer price
> fix: orange css for offer price

- apps/web/app/layout.tsx
- packages/surveys/src/components/general/ThankYouCard.tsx
- packages/surveys/src/components/general/WelcomeCard.tsx
fixes google translate issue
Fixes
https://github.com/formbricks/formbricks/issues/2776
- Test A
- Test B
> fix: google translate issue

- apps/web/app/(app)/(survey-editor)/environments/[environmentId]/surveys/[surveyId]/edit/components/HowToSendCard.tsx
null channel survey type bug
Fixes
- Test A
- Test B
> fix: null channel survey type bug

- apps/web/app/(app)/environments/[environmentId]/(people)/people/components/PeopleSecondaryNavigation.tsx
Removes attributes from loading skeleton
Fixes
https://github.com/formbricks/internal/issues/254
- Test A
- Test B
> fix: remove attributes from loading skeleton

- apps/web/next.config.mjs
Removes poweredByHeader
Fixes 
https://github.com/formbricks/internal/issues/260
- Test A
- Test B
> fix: removes poweredByHeader

- .env.example
- apps/web/app/(app)/environments/[environmentId]/product/(setup)/app-connection/page.tsx
- apps/web/app/(app)/environments/[environmentId]/product/(setup)/components/SetupInstructions.tsx
- apps/web/app/(app)/environments/[environmentId]/product/(setup)/website-connection/page.tsx
- apps/web/app/(app)/environments/[environmentId]/product/general/page.tsx
- apps/web/app/api/v1/og/route.tsx
- apps/web/app/setup/organization/[organizationId]/invite/components/InviteMembers.tsx
- apps/web/cache-handler.mjs
- apps/web/next.config.mjs
- apps/web/package.json
- packages/ui/SettingsId/index.tsx
Updating the cache-handler using the [official example](https://caching-tools.github.io/next-shared-cache/redis) to avoid performance issue when using Redis cache.
> fix: update cache handler based on official example

- apps/docs/app/developer-docs/contributing/page.mdx
Fixes #2809 2809
- Go [docs](https://formbricks.com/docs/developer-docs/contributing#git-pod)
- Click __Open in Gitpod__ button
> docs: fix gitpod url

- apps/web/app/(app)/(survey-editor)/environments/[environmentId]/surveys/[surveyId]/edit/components/LogicEditor.tsx
- apps/web/app/(app)/(survey-editor)/environments/[environmentId]/surveys/[surveyId]/edit/components/QuestionCard.tsx
- apps/web/app/(app)/(survey-editor)/environments/[environmentId]/surveys/[surveyId]/edit/components/QuestionsDroppable.tsx
- apps/web/app/(app)/(survey-editor)/environments/[environmentId]/surveys/[surveyId]/edit/components/QuestionsView.tsx
- apps/web/app/(app)/(survey-editor)/environments/[environmentId]/surveys/[surveyId]/edit/components/SurveyEditor.tsx
Fixes 
Before fix 
https://github.com/formbricks/formbricks/assets/67850763/dc1edfd6-2842-4555-83ab-9008a5580636
After fix 
Test question form cards with logic (check churn survey)
> fix: question form card width issue

- apps/web/app/(app)/environments/[environmentId]/product/look/components/EditLogo.tsx
- apps/web/app/(app)/environments/[environmentId]/settings/(account)/profile/components/EditProfileAvatarForm.tsx
restricted svg upload in profile image and brand logo
Fixes
https://github.com/formbricks/formbricks/issues/2804
- Test A
- Test B
> fix: restricted svg upload in profile image and brand logo

- packages/ui/DeleteDialog/index.tsx
Fixes https://github.com/formbricks/internal/issues/266
Check delete product modal
> fix: spacing in delete dialog

- packages/surveys/src/components/questions/NPSQuestion.tsx
Improve NPSQuestion component styling
Fixes
- Test A
- Test B
> chore: improve NPSQuestion component styling

- apps/web/app/(app)/environments/[environmentId]/settings/(organization)/billing/components/PricingTable.tsx
- packages/ee/billing/lib/constants.ts
- packages/ui/PricingCard/index.tsx
> fix: remove deal cloud

- apps/web/app/(app)/(onboarding)/organizations/[organizationId]/layout.tsx
- packages/lib/posthogServer.ts
fixing an issue where we see unidentified users in Posthog in the product onboarding.
> fix: identify Posthog users in product onboarding

- apps/docs/app/self-hosting/docker/page.mdx
> docs: Fix documentation link

- .github/actions/cache-build-web/action.yml
- .github/workflows/build-web.yml
- .github/workflows/e2e.yml
- .github/workflows/lint.yml
- .github/workflows/test.yml
fixes github actions failing because of pnpm/action-setup action. More info:
https://github.com/pnpm/action-setup/issues/135
- actions should run
> fix: pnpm github action version

- packages/lib/templates.ts
- packages/surveys/src/components/wrappers/StackedCardsContainer.tsx
- packages/ui/PreviewSurvey/components/Modal.tsx
- packages/ui/PreviewSurvey/lib/utils.ts
Fixes #2847
Test survey preview (top left and top right) on safari
Also fixes card width issue for simple card arrangement
> fix: survey card issues

- apps/web/app/(auth)/invite/page.tsx
- apps/web/app/page.tsx
Fixes invite issue
Send invitation to an account
Accept the invitation and create an account using google/github
You are thrown to Invite not found screen (even though it is accepted)
It occurred due failing of updateUser service which was a result of failing zod input validation
> fix: invite functionality for providers

- README.md
update local setup links in README.md
Fixes 
https://github.com/formbricks/formbricks/issues/2855
- Test A
- Test B
> chore: update local setup links in README.md

- packages/types/surveys/types.ts
fixes the zod validation for button URL in the CTA question type
- Click on the button to external link button in a CTA question
- dont add any link, the validation would fail
- go back to regular button, validation wouldn't fail
> fix: CTA button URL fix

- packages/ui/ResetProgressButton/index.tsx
Fixes #2882 
Type property was missing from button and hence it showed the default submit behaviour
Test reset progress button on Theme styling preview
> fix: Added type to ResetProgressButton

- apps/web/app/(app)/environments/[environmentId]/integrations/page.tsx
Fixes 404 on js integration connect page
When product channel is website, we get a 404 on clicking connect on js integration card because it always redirected to ` /product/app-connection`, which is not available when product channel is website.
Also removed the js integration card when product channel is link
Create a product with channel `website`
Open integrations section
Click on `connect` for js integration
> fix: 404 on js integration connect page

- packages/surveys/src/components/general/Survey.tsx
- packages/surveys/src/components/general/WelcomeCard.tsx
Fixes https://github.com/formbricks/internal/issues/301
Test recall in welcome card
> fix: recall in welcome card

- .env.example
- docker/docker-compose.yml
A small fix of the code comments. Resolving my confusion about CRON_SECRET’ new purpose.
- Test A
- Test B
> docs: unify CRON_SECRET descriptions

- apps/web/app/(app)/(onboarding)/organizations/[organizationId]/products/new/industry/page.tsx
> fix: typo in onboarding

- packages/js-core/src/app/lib/widget.ts
- packages/js-core/src/website/lib/widget.ts
- packages/surveys/src/components/general/SurveyModal.tsx
- packages/ui/QuestionFormInput/components/RecallItemSelect.tsx
Fixes https://github.com/formbricks/internal/issues/300
Test recall from hidden fields of in-app surveys
> fix: recall from hidden fields of in-app surveys

- apps/web/app/(app)/(survey-editor)/environments/[environmentId]/surveys/[surveyId]/edit/components/CalQuestionForm.tsx
Fix styling inconsistency in schedule a call-question form. It was a checkbox before, now a toggle.
Fixes #2923 
- Did some console logs
> style: Use AdvancedOptionToggle in schedule a call form

- packages/ee/advanced-targeting/components/add-filter-modal.tsx
fix: remove deprecated actions from segments `All` list
> fix: remove deprecated actions from segments all list

- packages/ui/Label/stories.tsx
Adds Label component to storybook
#2894 
https://github.com/user-attachments/assets/163f3e5d-3a6c-49ea-9689-664934136673
-Run Storybook using` pnpm storybook`
- Inspect Storybook on `http://localhost:6006/`
> feat: add storybook for Label component

- apps/web/app/api/v1/client/[environmentId]/app/sync/[userId]/route.ts
- apps/web/app/api/v1/client/[environmentId]/website/sync/route.ts
chore: send setup completed event to posthog
> chore: send setup completed event to posthog

- packages/lib/actionClass/service.ts
fixes https://github.com/formbricks/formbricks/issues/2916
- Capture a new action from the survey
- Edit the action and the survey's trigger should be updated
> fix: action update cache

- apps/web/app/(app)/(survey-editor)/environments/[environmentId]/surveys/[surveyId]/edit/components/CalQuestionForm.tsx
- apps/web/app/lib/questions.tsx
- packages/types/surveys/types.ts
fix: calHost UX and validation in cal question
> fix: calHost UX and validation in cal question

- docker-compose.yml
The identation for the `x-cron-secret` is incorrect so fixed the identation of the file
Fixes #2947 
Screenshot
NA
- Test A
- Test B
> fix: identation for docker-compose.yml

- packages/lib/templates.ts
- packages/ui/ErrorComponent/index.tsx
fixes two small typos
- Test A
- Test B
> fix: fix typos

- packages/lib/environment/service.ts
add `environment created` posthog event
> chore: add environment created posthog event

- apps/web/app/(app)/(onboarding)/organizations/[organizationId]/products/new/channel/page.tsx
- apps/web/app/(app)/environments/[environmentId]/components/MainNavigation.tsx
before
after
- added the icon
- updated the "product" text to the channel
- matched font with other dropover
- fixed truncation
> chore: tweaking product toggle

- packages/lib/survey/service.ts
fixes a bug on prod which stopped the saving of link surveys.
- Make an App survey in an App product
- Change the survey type to Link, should work on save / publish
> fix: segment delete fix

- packages/database/schema.prisma
- packages/lib/actionClass/service.ts
renames `surveys` to `surveyTriggers` in the `ActionClass` table
Fixes https://github.com/formbricks/internal/issues/305
> fix: rename surveys to surveyTriggers

- apps/web/app/(app)/environments/[environmentId]/components/MainNavigation.tsx
fix: add products with channel null to list
> fix: add products with channel null to list

- apps/web/app/(app)/(survey-editor)/environments/[environmentId]/surveys/[surveyId]/edit/components/QuestionsView.tsx
- packages/ee/multi-language/components/multi-language-card.tsx
- packages/lib/i18n/utils.ts
fix: mls labels not set properly on question create and adding a new language
> fix: mls labels not set properly on question create

- apps/docs/components/Header.tsx
This PR updates the link components to ensure that external links open in a new tab or window. This change improves user experience by preventing users from losing their current page.
Fixes #2994 
- Ensure that clicking on the "Star us on GitHub" and "Join us on Discord" links opens the respective pages in a new tab or window.
- Verify that the links do not break any existing functionality or layout.
> fix: Open external links in a new tab #2994

- docker/formbricks.sh
- Removes input case sensitivity
- Removed escape character, causing an error for a few users.
- Test A
- Test B
> fix: setup shell script, removes input case sensitivity

- packages/email/components/auth/forgot-password-email.tsx
- packages/email/components/auth/password-reset-notify-email.tsx
- packages/email/components/auth/verification-email.tsx
- packages/email/components/general/email-button.tsx
- packages/email/components/general/email-footer.tsx
- packages/email/components/general/email-template.tsx
- packages/email/components/invite/invite-accepted-email.tsx
- packages/email/components/invite/invite-email.tsx
- packages/email/components/invite/onboarding-invite-email.tsx
- packages/email/components/survey/embed-survey-preview-email.tsx
- packages/email/components/survey/link-survey-email.tsx
- packages/email/components/survey/preview-email-template.tsx
- packages/email/components/survey/response-finished-email.tsx
- packages/email/components/weekly-summary/create-reminder-notification-body.tsx
- packages/email/components/weekly-summary/live-survey-notification.tsx
- packages/email/components/weekly-summary/no-live-survey-notification-email.tsx
- packages/email/components/weekly-summary/notification-footer.tsx
- packages/email/components/weekly-summary/notification-header.tsx
- packages/email/components/weekly-summary/notification-insight.tsx
- packages/email/components/weekly-summary/weekly-summary-notification-email.tsx
- packages/email/index.tsx
- packages/email/lib/utils.ts
Fixes linting warnings in email package
Before 
After 
Check linting for email package
> fix: linting warnings in email package

- packages/lib/authOptions.ts
Adds default weekly summary notification value in signin
Fixes https://discord.com/channels/979077669410979880/1268896182353268768/1270159906934100000
- Test A
- Test B
> fix: adds default weekly summary notification value in signin

- apps/web/app/api/pipeline/lib/handleIntegrations.ts
- apps/web/app/api/pipeline/route.ts
- packages/lib/airtable/service.ts
Fixes https://github.com/formbricks/internal/issues/297
- throw an error from an integration
- the error should be logged on the console but not thrown
> fix: catching errors in integrations

- apps/web/app/s/[surveyId]/components/LinkSurveyWrapper.tsx
- apps/web/app/s/[surveyId]/components/SurveyLoadingAnimation.tsx
- packages/ui/MediaBackground/index.tsx
On Formbricks cloud with no so good internet connection I just had the issue that first the loading animation came, then then the survey showed and the background took a few more seconds to load
Test surveys with larger backgrounds
> fix: wait for background to load in survey loading indicator

- apps/web/tailwind.config.js
- packages/config-tailwind/tailwind.config.js
fix: styles get overwritten by loading indicator changes
> fix: styles get overwritten by loading indicator changes

- packages/database/migrations/20240815084351_adds_relation_between_display_and_response/migration.sql
- packages/database/schema.prisma
fix: remove failing prisma migration from #2986
> fix: remove failing prisma migration

- packages/ui/ColorPicker/stories.tsx
- Added ColorPicker component to Storybook
[ColorPicker component.webm](https://github.com/user-attachments/assets/3c095233-0721-4efc-bf69-f817be5fd79a)
Fixes #2892
Run Storybook using pnpm storybook
Inspect Storybook on [http://localhost:6006/](http://localhost:6006/)
> feat: Added ColorPicker component to Storybook

- packages/database/data-migrations/20240807120500_cta_consent_dismissed_inconsistency/data-migration.ts
dismissed inconsistency data migration fails with many database entries due to inconsistent use of the existing prisma transaction.
> fix: dismissed inconsistency data migration fails with many entries

- packages/ee/billing/lib/create-subscription.ts
add address collection and optional VAT to stripe checkout on Formbricks Cloud
> chore: add address collection to stripe checkout

- apps/web/app/(app)/(survey-editor)/environments/[environmentId]/surveys/[surveyId]/edit/components/EditorCardMenu.tsx
Fixes #2948 
Check Add question below menu in a question card
Question of same type will be missing
> fix: missing question type in Add question below menu

- packages/lib/display/service.ts
Fixes an issue with the display creation where, display object was missing the response Id and due to which response creation and deletion threw the following errors 
Create and delete response
> fix: display creation

- packages/ee/multi-language/components/localized-editor.tsx
- packages/ui/Editor/components/ToolbarPlugin.tsx
Fixes #3039 
Test link in welcome card/ consent/ cta
> fix: open outbound links in new tab

- packages/react-native/package.json
chore: increase react-native version number to 1.0.0
> chore: increase react-native version number to 1.0.0

- apps/web/app/(app)/(survey-editor)/environments/[environmentId]/surveys/[surveyId]/edit/components/EditEndingCard.tsx
- apps/web/app/(app)/(survey-editor)/environments/[environmentId]/surveys/[surveyId]/edit/components/EditWelcomeCard.tsx
- apps/web/app/(app)/(survey-editor)/environments/[environmentId]/surveys/[surveyId]/edit/components/HiddenFieldsCard.tsx
- packages/ui/SurveysList/index.tsx
Replaces emojis in the survey editor and surveys overview with appropriate/similar Lucide icons. Please feel free to change icons if wanted.
Fixes #3001 
**Changes in survey editor**
* Welcome card: Hand emoji replaced with hand icon
* Thank you card: Pray emoji replaced with handshake icon and redirect emoji replaced with undo2 icon (turned upside down)
* Hidden fields: Ninja emoji replaced with eye off icon
**Changes in surveys overview**
* Detective emoji replaced with search icon
Only UI changes
> feat: replace emojis in survey editor and survey fetching

- packages/api/package.json
- packages/api/src/api/client/storage.ts
- packages/api/vite.config.js
- packages/lib/storage/service.ts
- pnpm-lock.yaml
fixes file uploads for S3 that are broken rn after the react native changes went live
- Upload a file on S3 using the file upload question
- It should work
> fix: s3 file upload

- packages/js/package.json
increase version number of `@formbricks/js` to 2.2.0 and release package
> chore: release js 2.2.0

- apps/docs/app/developer-docs/contributing/get-started/page.mdx
fix: build errors on docs page
> fix: build errors on docs page

- apps/web/app/(app)/(survey-editor)/environments/[environmentId]/surveys/templates/page.tsx
- apps/web/app/(app)/environments/[environmentId]/components/EnvironmentLayout.tsx
- apps/web/app/(app)/environments/[environmentId]/components/TopControlBar.tsx
- apps/web/app/(app)/environments/[environmentId]/components/TopControlButtons.tsx
- apps/web/app/(app)/environments/[environmentId]/surveys/page.tsx
fixes new survey button visible to viewers
Fixes https://github.com/formbricks/formbricks/issues/3062
- create survey button shouldn't be visible to the viewer role user
- viewer role user shouldn't be able to land on the templates page; must get redirected to the survey listing page
> fix: new survey button visible to viewers

- apps/web/app/s/[surveyId]/components/LinkSurvey.tsx
- apps/web/app/s/[surveyId]/components/LinkSurveyWrapper.tsx
- packages/surveys/src/components/general/Survey.tsx
- packages/types/formbricks-surveys.ts
Fixes https://github.com/formbricks/internal/issues/346
Test reset button for link survey preview
> fix: reset survey button

- apps/web/app/lib/questions.tsx
fix: change question type CTA wording
> fix: change question type CTA wording

- apps/web/app/(app)/environments/[environmentId]/product/languages/page.tsx
- apps/web/app/lib/questions.tsx
- apps/web/playwright/utils/helper.ts
- packages/ee/multi-language/components/edit-language.tsx
- packages/ee/multi-language/lib/actions.ts
- packages/lib/language/service.ts
- packages/lib/language/tests/language.unit.ts
Fixes https://github.com/formbricks/internal/issues/318
Test language services and caching
> chore: removed environmentId from language services

- packages/lib/survey/cache.ts
- packages/lib/survey/service.ts
Fixes #3048
Publish a survey result
Visit published link
UnPublish Result
Again visit published link
> fix: caching issue for resultShareKey

- apps/docs/app/developer-docs/contributing/get-started/page.mdx
Fixes build error in docs app
- Test A
- Test B
> fix: docs app build

- apps/web/app/s/[surveyId]/components/SurveyLoadingAnimation.tsx
- packages/lib/responses.ts
Fixes #3079 
Also email were breaking too
Before fix, if we had a response where answer to NPS is 0, then it was not included in the response finished email
After fix 
Download CSV for survey containing NPS question with responses equal to 0
> fix: NPS response exported as empty string

- apps/docs/app/self-hosting/migration-guide/page.mdx
- apps/web/package.json
- packages/api/package.json
- packages/database/package.json
adds data migration guide for formbricks 2.5 release
- Test A
- Test B
> docs: adds data migration guide for formbricks 2.5 release

- apps/docs/app/self-hosting/migration-guide/page.mdx
- packages/database/data-migrations/20240807120500_cta_consent_dismissed_inconsistency/data-migration.ts
- packages/ui/SingleResponseCard/components/RenderResponse.tsx
final bugs in release 2.5
- Test A
- Test B
> fix: final bugs in release 2.5

- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/responses/components/ResponseCardModal.tsx
- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/responses/components/ResponseTable.tsx
- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/responses/components/ResponseTableColumns.tsx
Fixes #3086 
Check hidden fields in response table
> fix: hidden fields in data table

- packages/lib/response/service.ts
- packages/lib/response/utils.ts
Fixes #3074 
Export response for survey with email verification enabled
> fix: verified email to exports

- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/responses/components/ResponseTableColumns.tsx
- packages/ui/SingleResponseCard/components/RenderResponse.tsx
Decreased width of status and date column
Fixed multiple choice response cell view
https://github.com/user-attachments/assets/32cb0c83-0fed-4607-8eb5-7f413785bff3
- Test A
- Test B
> fix: data table tweaks

- apps/web/app/(app)/(survey-editor)/environments/[environmentId]/surveys/[surveyId]/edit/components/EndScreenForm.tsx
- apps/web/app/(app)/(survey-editor)/environments/[environmentId]/surveys/[surveyId]/edit/components/RedirectUrlForm.tsx
- packages/lib/i18n/i18n.mock.ts
- packages/lib/response/tests/__mocks__/data.mock.ts
- packages/lib/templates.ts
> fix: update link to landing page

- .github/ISSUE_TEMPLATE/oss-gg-hack-submission.yml
feat: add new template to GitHub
> feat: add new template to GitHub

- apps/demo-react-native/src/app.tsx
- packages/js-core/src/app/lib/attributes.ts
- packages/react-native/src/lib/attributes.ts
- packages/react-native/src/lib/initialize.ts
fixes an error that leads to failing of `setAttribute` calls in `@formbricks/js` package.
- load the sdk in an app, for example the demo app
- invoke `formbricks.setAttribute`, it should work properly
> fix: setAttribute error in the js package

- apps/web/app/(app)/environments/[environmentId]/components/EnvironmentSwitch.tsx
- apps/web/app/(app)/environments/[environmentId]/components/TopControlBar.tsx
- apps/web/app/(app)/environments/[environmentId]/components/TopControlButtons.tsx
Fixes https://github.com/formbricks/internal/issues/350
For product with channel "link"
For product with channel "app" or "website"
Test env switch
> style: tweak environment switch

- packages/lib/response/service.ts
Creating response via API can change created and updated at
Fixes https://discord.com/channels/979077669410979880/1011351796507213874/1280790454866280458
- Test A
- Test B
> fix: create response via api can change created and updated at

- apps/web/package.json
> release 2.5.1

- apps/web/app/s/[surveyId]/components/SurveyLoadingAnimation.tsx
Fixes https://github.com/formbricks/internal/issues/353
As per the new modifications made in approach, we now do wait for survey package to load, but wait for media to load for 3 seconds max. If any of the media throws an error while loading, we set isMediaLoaded to true and hide the loading animation
Add an image to a survey card
Delete it from your storage
> fix: infinite loading in survey animation

- apps/web/app/lib/questions.tsx
- apps/web/playwright/survey.spec.ts
- apps/web/playwright/utils/mock.ts
- packages/lib/templates.ts
- packages/surveys/src/components/questions/MatrixQuestion.tsx
fix: remove description from new questions
> fix: remove description from new questions

- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/responses/components/ResponseDataView.tsx
- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/responses/components/ResponseTableColumns.tsx
- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/responses/components/ResponseTableHeader.tsx
- apps/web/playwright/survey.spec.ts
- apps/web/playwright/utils/helper.ts
- packages/types/responses.ts
Fixes https://github.com/formbricks/internal/issues/357
Look for Person column in data table
> fix: added people column to data table

- apps/web/app/(app)/(survey-editor)/environments/[environmentId]/surveys/[surveyId]/edit/actions.ts
- packages/lib/constants.ts
SSRF vulnerability in Unsplash image fetching
Fixes https://github.com/formbricks/internal/issues/358
- Test A
- Test B
> fix: SSRF vulnerability in unsplash image fetching

- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/summary/components/SummaryMetadata.tsx
- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/summary/components/SummaryPage.tsx
- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/summary/loading.tsx
- packages/ui/SkeletonLoader/index.tsx
This pr will add the loading.tsx in summary page in survey 
#3085
[364928629-5fb65d05-b02e-47e4-8fd1-b282c1a0ec4c.webm](https://github.com/user-attachments/assets/4fe44cfa-29e4-4e20-86a0-73a5c71ae07b)
> fix: Loading Skeleton for survey summary page

- apps/web/app/(app)/(survey-editor)/environments/[environmentId]/surveys/[surveyId]/edit/components/SurveyMenuBar.tsx
Fixes #3122  (issue)
- Test A
- Test B
> fix: trigger

- packages/types/displays.ts
- packages/types/js.ts
- packages/types/storage.ts
Formbricks uses cuid2 and not cuid. This PR makes sure that during validation it validates for cuid2 (in most places it already uses cuid2 validation)
Fixes #3128
Test this request
```
curl --request POST \
--url http://localhost:3000/api/v1/client/cm0xtgl0u000008jv560ed7qq/displays \
--data '{"surveyId":"ign1eyhugb9xouy1986peg0m"}'
```
> fix: cuid validation 🚨

- packages/ui/SingleResponseCard/components/SingleResponseCardHeader.tsx
Limits width of tooltip rows and adds the full info as a title attribute (visible on hover)
Fixes #3134
- View URL from long URL (e.g. http://localhost:3002/app?formbricksDebug=true&loooooooooooooooooooooooongstring=loooooooooooooooooooooooongstring&looooooooooooooooooooooooooooooooongstring2=looooooooonoooooooooooooooooooooooogstring2&looooooooooooooooooooooooooooooooongstring3=looooooooooooooooooooooooooooooooongstring3&alooooooooooooooooooooooooooooooooongstring3=looooooooooooooooooooooooooooooooongstring3&blooooooooooooooooooooooooooooooooongstring3=looooooooooooooooooooooooooooooooongstring3&clooooooooooooooooooooooooooooooooongstring3=looooooooooooooooooooooooooooooooongstring3)
> fix: Device Info Overflowing for Long URLs

- apps/web/app/(app)/(survey-editor)/environments/[environmentId]/surveys/[surveyId]/edit/components/AddActionModal.tsx
- apps/web/app/(app)/(survey-editor)/environments/[environmentId]/surveys/[surveyId]/edit/components/CreateNewActionTab.tsx
- apps/web/app/(app)/(survey-editor)/environments/[environmentId]/surveys/[surveyId]/edit/components/TargetingCard.tsx
- packages/ui/organisms/NoCodeActionForm/components/PageUrlSelector.tsx
> fix: tweak action UI

- apps/web/package.json
bump apps/web version number
- Test A
- Test B
> fix: release 2.5.3

- apps/web/app/(app)/environments/[environmentId]/settings/(organization)/components/OrganizationSettingsNavbar.tsx
- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/responses/components/ResponseTableColumns.tsx
- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/responses/components/ResponseTableHeader.tsx
Fixes https://github.com/formbricks/internal/issues/321
also fixes 
Test billing tab visibility (should be only visible to owners and admins)
> fix: billing tab

- apps/web/next.config.mjs
Removes rewrites from the next config which was added for backwards compatibility
- Test A
- Test B
> fix: removes rewrites from next config

- packages/js/README.md
This pull request includes a simplification of the `README.md` file for the `@formbricks/js` package by consolidating the initialization examples for `Website` and `App` surveys into a single example.
Documentation updates:
* [`packages/js/README.md`](diffhunk://#diff-3d2e4fcf1e9d3df5d7a2440a6295a49e2d298c8a0509a350fe512905e489f719L23-R34): Consolidated the initialization examples for `Website` and `App` surveys into a single example using `@formbricks/js`. Updated the instructions to include a link to the user identification feature documentation.
> chore: update js README for v3 release

- apps/storybook/.storybook/preview.ts
This pull request includes a small but important change to the `apps/storybook/.storybook/preview.ts` file. The change updates the import path for the global CSS file to ensure the correct styles are applied.
* [`apps/storybook/.storybook/preview.ts`](diffhunk://#diff-d3465b788be6992fe2c66486f56491694616dd0e1cf47cb2e114ff457991b48bL2-R2): Updated the import path for `globals.css` from `../../web/app/globals.css` to `../../../packages/ui/globals.css`.
> fix: chromatic github action

- apps/docs/app/self-hosting/migration-guide/page.mdx
- apps/web/app/(app)/environments/[environmentId]/(people)/attributes/actions.ts
docs: update wording for 2.6 migration
> docs: update wording for 2.6 migration

- apps/web/app/(app)/environments/[environmentId]/integrations/webhooks/actions.ts
- apps/web/app/(app)/environments/[environmentId]/integrations/webhooks/components/AddWebhookModal.tsx
- apps/web/app/(app)/environments/[environmentId]/integrations/webhooks/components/WebhookSettingsTab.tsx
- apps/web/lib/utils/helper.ts
- packages/lib/messages/de-DE.json
- packages/lib/messages/en-US.json
- packages/lib/messages/fr-FR.json
- packages/lib/messages/pt-BR.json
Fixes webhook deleteion and updation working
Try to delete/ update webhook
> fix: webhook deleteion and updation working

- .github/workflows/scorecard.yml
This pull request includes updates to the GitHub Actions workflow for the project. The changes focus on enhancing the workflow triggers and correcting artifact naming conventions.
Enhancements to workflow triggers:
* [`.github/workflows/scorecard.yml`](diffhunk://#diff-2e3112f4e81a9c47df8000638ce3b1b9ca15edcc82b228c207a7a4ff3bc7133fR16): Added `workflow_dispatch` to enable manual triggering of the workflow.
Corrections to artifact naming conventions:
* [`.github/workflows/scorecard.yml`](diffhunk://#diff-2e3112f4e81a9c47df8000638ce3b1b9ca15edcc82b228c207a7a4ff3bc7133fL66-R67): Changed the artifact name from `SARIF file` to `SARIF-file` for consistency.
> fix: scorecard action

- docs/mint.json
- docs/self-hosting/configuration/smtp.mdx
- packages/lib/messages/de-DE.json
- packages/lib/messages/en-US.json
- packages/lib/messages/fr-FR.json
- packages/lib/messages/pt-BR.json
- packages/lib/messages/zh-Hant-TW.json
Add `SMTP Configuration` documentation page for self-hosters.
> docs: add smtp configuration page for self-hosters

- docs/self-hosting/setup/kubernetes.mdx
This pull request includes significant updates to the Kubernetes deployment documentation for Formbricks. The changes primarily focus on enhancing clarity, adding new sections for production deployment, and updating the upgrade process.
Key changes include:
* [`docs/self-hosting/setup/kubernetes.mdx`](diffhunk://#diff-b94fceba11c811048e5f563f170b77e04281c3cc66343c32d0a9cf4e6f006cb9L7-L34): Revised the introductory section to clarify the purpose of the guide and added a prerequisites section.
* [`docs/self-hosting/setup/kubernetes.mdx`](diffhunk://#diff-b94fceba11c811048e5f563f170b77e04281c3cc66343c32d0a9cf4e6f006cb9L7-L34): Introduced a new section for production deployment, including instructions for using managed database and cache services.
* …
> docs: update kubernetes deployment page

- .github/ISSUE_TEMPLATE/bug_report.yml
- packages/lib/messages/de-DE.json
- packages/lib/messages/en-US.json
- packages/lib/messages/fr-FR.json
- packages/lib/messages/pt-BR.json
- packages/lib/messages/pt-PT.json
- packages/lib/messages/zh-Hant-TW.json
Add bug label to new Github bug issues to work with Slack integration
> chore: add bug label to new bug issues

- docs/self-hosting/configuration/auth-sso/saml-sso.mdx
- docs/xm-and-surveys/core-features/integrations/overview.mdx
- docs/xm-and-surveys/surveys/link-surveys/quickstart.mdx
- docs/xm-and-surveys/surveys/website-app-surveys/quickstart.mdx
This PR removes or changes the duplicate titles from the docs for better SEO results. It does that mainly for the following 6 links.
1. https://formbricks.com/docs/self-hosting/configuration/auth-sso/saml-sso
2. https://formbricks.com/docs/xm-and-surveys/enterprise-features/saml-sso
3. https://formbricks.com/docs/xm-and-surveys/core-features/integrations/overview
4. https://formbricks.com/docs/development/overview
5. https://formbricks.com/docs/xm-and-surveys/surveys/website-app-surveys/quickstart
6. https://formbricks.com/docs/xm-and-surveys/surveys/link-surveys/quickstart
Fixes #(issue)
- Test A:
1. Run the docs app.
2. Check titles for the pages I mentioned above.
> docs: Remove duplicate titles for better SEO

- .github/workflows/terrafrom-plan-and-apply.yml
- infra/terraform/main.tf
- infra/terraform/secrets.tf
- use helm chart release 3.5.1
- point to s3 bucket to existing s3 bucket
- stop terraform atuomation while we are working on migration to avoid conflicts
- remove DATABASE_URL from the code managed secret
> release: pre steps switch from vercel to aws

- docs/self-hosting/advanced/license.mdx
This pull request includes updates to the `docs/self-hosting/advanced/license.mdx` file to improve the formatting and readability of the license documentation. The changes involve updating the title format, correcting a table entry, and breaking long lines for better readability.
Formatting improvements:
* Changed the title format from single quotes to double quotes for consistency.
* Broke long lines into multiple lines for better readability, particularly in the Note sections. [[1]](diffhunk://#diff-564dd5545616f9c6cdd3428101351325aa095440c795e185d9576c08805c3707L2-R12) [[2]](diffhunk://#diff-564dd5545616f9c6cdd3428101351325aa095440c795e185d9576c08805c3707L47-R50)
Corrections:
* Corrected the alignment of the "Cluster support" entry in the features table.
> docs: update license page

- docs/xm-and-surveys/surveys/general-features/hidden-fields.mdx
update hidden fields in app & website surveys
> docs: update hidden field docs

- docs/api-reference/client-api->-response/update-response.mdx
- docs/api-reference/openapi.json
Fix formatting and environmentId missing in client api v1 docs.
> docs: fix response client api endpoint is missing environmentId

- packages/android/formbricksSDK/src/main/java/com/formbricks/formbrickssdk/Formbricks.kt
- packages/android/formbricksSDK/src/main/java/com/formbricks/formbrickssdk/manager/SurveyManager.kt
- packages/android/formbricksSDK/src/main/java/com/formbricks/formbrickssdk/webview/FormbricksFragment.kt
- packages/android/formbricksSDK/src/main/java/com/formbricks/formbrickssdk/webview/FormbricksViewModel.kt
- packages/ios/Demo/Demo/AppDelegate.swift
- packages/ios/Demo/Demo/ContentView.swift
- packages/ios/FormbricksSDK/FormbricksSDK/Formbricks.swift
- packages/ios/FormbricksSDK/FormbricksSDK/Manager/PresentSurveyManager.swift
- packages/ios/FormbricksSDK/FormbricksSDK/Manager/SurveyManager.swift
- packages/ios/FormbricksSDK/FormbricksSDK/Networking/Base/APIClient.swift
- packages/ios/FormbricksSDK/FormbricksSDK/WebView/FormbricksViewModel.swift
- packages/ios/FormbricksSDK/FormbricksSDK/WebView/SurveyWebView.swift
Fixes #(issue)
- Test A
- Test B
> feat: add hidden field in HTML template Android/IOS

- docs/xm-and-surveys/surveys/link-surveys/data-prefilling.mdx
docs: tweak Data Prefilling docs for clarity
> docs: tweak Data Prefilling docs for clarity

- docs/self-hosting/advanced/license.mdx
> docs: update ee feature table

- apps/web/app/page.test.tsx
- apps/web/app/page.tsx
- apps/web/lib/project/service.test.ts
- apps/web/lib/project/service.ts
Fixes the default environment redirect
Fixes #6027
- Test A
- Test B
> fix: backport in organization landing

- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/components/CustomFilter.test.tsx
- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/components/CustomFilter.tsx
- apps/web/locales/fr-FR.json
- apps/web/modules/ui/components/data-table/components/data-table-toolbar.tsx
- apps/web/modules/ui/components/data-table/components/selected-row-settings.tsx
Fixes https://github.com/formbricks/formbricks/issues/5692
Adds a loading state to the download responses button in the responses view 
https://github.com/user-attachments/assets/694d87bd-f207-48d8-abe6-5aa3e86706b9
- Go to the responses page of a survey
- Click the download button and download some responses
> fix: adds loading state to the responses download button

- apps/web/modules/auth/signup/components/password-checks.tsx
- apps/web/modules/survey/editor/components/animated-survey-bg.tsx
sonarqube low reliability issues
Fixes https://github.com/formbricks/internal/issues/542
- Please check the reliability issues flagged in the SonarQube from the ticket,
> chore: sonarqube low reliability issues

- apps/web/modules/auth/lib/authOptions.ts
secure cookies fix for callback URL
Fixes https://github.com/formbricks/internal/issues/862
1. NextAuth Configuration: Use `https` URL and `experimental-https` flag in `pnpm go` command.
2. Callback URL Cookie Key: `__Secure-next-auth.callback-url`.
3. Invite Flow Callback URL: Should not be empty.
> fix: secure cookies fix for callback URL

- apps/web/locales/de-DE.json
- apps/web/locales/en-US.json
- apps/web/locales/fr-FR.json
- apps/web/locales/pt-BR.json
- apps/web/locales/pt-PT.json
- apps/web/locales/zh-Hant-TW.json
- apps/web/modules/ee/teams/team-list/components/team-settings/team-settings-modal.test.tsx
- apps/web/modules/ee/teams/team-list/components/team-settings/team-settings-modal.tsx
fixes Missing space in Access Control Modal
Fixes #6337 
- test the edit team modal without any projects or members?
> fix: Missing space in Access Control Modal

- apps/web/app/global-error.tsx
- apps/web/lib/organization/service.ts
- packages/surveys/src/components/general/response-error-component.tsx
- packages/surveys/src/components/wrappers/stacked-card.tsx
fixes SonarQube medium vulnerability issues
Fixes https://github.com/formbricks/internal/issues/536
- The app should work fine.
> fix: sonarqube medium vulnerability issues

- apps/web/locales/de-DE.json
- apps/web/locales/en-US.json
- apps/web/locales/fr-FR.json
- apps/web/locales/pt-BR.json
- apps/web/locales/pt-PT.json
- apps/web/locales/zh-Hant-TW.json
Updates the tolgee key `delete_response_confirmation` to production
Fixes #(issue)
- Check the delete response modal
> fix: updates tolgee key

- apps/web/locales/de-DE.json
- apps/web/locales/en-US.json
- apps/web/locales/fr-FR.json
- apps/web/locales/pt-BR.json
- apps/web/locales/pt-PT.json
- apps/web/locales/zh-Hant-TW.json
- apps/web/modules/ui/components/input-combo-box/index.tsx
- Fixes an issue that was brought up in this slack discussion: https://formbricks.slack.com/archives/C08UUA6TXPA/p1754468930305709
- The Dropdown's width depends on its content. Very long question potentially exceed the available viewport width (and look weird)
- Introduces a min-w to `InputComboBox`
- Introduces a dynamic width to the Dropdown element, to make it as wide as the Trigger (if min-w has been exceeded)
- Introduced tolgee localization for default 'Search' placeholder in Combobox.
| Status Quo | New: min width | New: dynamic width |
|--------|--------|--------|
| <img width="818" height="510" alt="Screenshot 2025-08-06 at 12 12 28" src="https://github.com/user-attachments/assets/df3061f2-b82d-4ca0-b205-c881d0e8fe3a" /> | <img width="818" height="510" alt="Screenshot 2025-08-06 …
> fix: dynamic width for InputCombobox

- .github/actions/upload-sentry-sourcemaps/action.yml
- apps/web/locales/ro-RO.json
Addresses two security vulnerabilities identified by OneLeet Code Scanning in the GitHub Actions workflow for uploading Sentry sourcemaps.
1. **Removed unnecessary token validation step** that exposed the Sentry auth token
- Eliminated explicit API call that stored token in environment variables
- Removed curl command that could expose token in process lists
- Deleted temporary file creation that could leak sensitive data
- API to validate token call can be skipped as this will also be checked by the Sentry action itself.
2. **Fixed command injection vulnerability** in shell script echo statements
- Properly quoted all variable expansions using `${VAR}` syntax
- Applied fix to `$DOCKER_IMAGE`, `$CONTAINER_ID`, and `$sourcemap_count` variables
- Maintained existing regex validation for …
> fix: OneLeet Code Scanning Sentry action issues

- apps/web/locales/de-DE.json
- apps/web/locales/en-US.json
- apps/web/locales/fr-FR.json
- apps/web/locales/pt-BR.json
- apps/web/locales/pt-PT.json
- apps/web/locales/ro-RO.json
- apps/web/locales/zh-Hant-TW.json
- apps/web/modules/ee/billing/api/lib/constants.ts
- apps/web/modules/ee/billing/components/pricing-table.tsx
Change the Pricing link to use the new Pricing form
Fixes #(issue)
- Test A
- Test B
> chore: Change pricing form link

- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/summary/components/share-survey-modal.tsx
- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/summary/components/shareEmbedModal/share-view.tsx
Fixes https://github.com/formbricks/internal/issues/953
- Open the share modal for a link survey and turn on single use links
- The website, email embeds and social media and QR code tabs should get disabled
with single use disabled:
with single use enabled:
> fix: disables share tabs when single use is active

- apps/web/locales/de-DE.json
- apps/web/locales/en-US.json
- apps/web/locales/fr-FR.json
- apps/web/locales/pt-BR.json
- apps/web/locales/pt-PT.json
- apps/web/locales/ro-RO.json
- apps/web/locales/zh-Hant-TW.json
- apps/web/modules/survey/link/lib/metadata-utils.ts
Fixes an issue with customizable metadata in multi-language surveys where, if metadata is defined only in the default language and left blank in other languages, viewing the survey in another language would incorrectly display the metadata (title and description) from the default language instead of falling back to the survey’s actual default values (e.g., survey name).
For example 
```
metadata.title: {  
default: "metadata in default language",  
de: ""  
}  
```
Previously, if metadata.title for de was missing, the code would render the default language’s metadata rather than the intended default survey title.
- Test A
- Test B
> fix: metadata issue

- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/summary/components/shareEmbedModal/link-settings-tab.tsx
- apps/web/modules/survey/link/contact-survey/page.test.tsx
- apps/web/modules/survey/link/contact-survey/page.tsx
- apps/web/modules/survey/link/lib/metadata-utils.test.ts
- apps/web/modules/survey/link/lib/metadata-utils.ts
- apps/web/modules/survey/link/metadata.test.ts
- apps/web/modules/survey/link/metadata.ts
Fixes placeholder and removes product name from title
- Test A
- Test B
> chore: metadata tweaks backport

- packages/cache/.cursor/rules/cache-package.md
- packages/cache/.eslintrc.cjs
- packages/cache/.gitignore
- packages/cache/package.json
- packages/cache/src/factory.test.ts
- packages/cache/src/factory.ts
- packages/cache/src/index.test.ts
- packages/cache/src/index.ts
- packages/cache/tsconfig.json
- packages/cache/vite.config.ts
- pnpm-lock.yaml
- sonar-project.properties
- turbo.json
Implements https://github.com/formbricks/internal/issues/972
- Added package structure including package.json, TypeScript configuration, and Vite setup.
- Implemented factory functions for creating a Redis client and cache service.
- Included unit tests for core functionalities.
- Configured ESLint and .gitignore for the new package.
- Updated pnpm-lock.yaml to include new dependencies.
Verify if these commands work:
`pnpm --filter @formbricks/cache lint passes`
`pnpm --filter @formbricks/cache test passes`
`pnpm --filter @formbricks/cache build creates dist/`
> feat: introduce @formbricks/cache package with Redis client

- apps/web/lib/utils/recall.test.ts
- apps/web/lib/utils/recall.ts
- apps/web/modules/survey/components/question-form-input/components/fallback-input.tsx
- packages/surveys/src/lib/recall.test.ts
- packages/surveys/src/lib/recall.ts
Fixes https://github.com/formbricks/internal/issues/816
Test issue mentioned in link ticket
Initially it was not possible to create recall with no spaces in between. But redirect url cannot have spaces and hence this was failing
> fix: multiple recalls in redirect url

- apps/web/modules/survey/link/components/verify-email.tsx
Fixes https://github.com/formbricks/internal/issues/1015
https://github.com/user-attachments/assets/822f1b97-081f-442a-8362-24e215787d6f
Test issue mentioned in linked ticket
> fix: email verify survey question preview

- apps/web/modules/ui/components/media-background/index.test.tsx
- apps/web/modules/ui/components/media-background/index.tsx
- apps/web/modules/ui/components/preview-survey/index.tsx
Fixes #6470 
Initial 
After fix
Create a very long question for a link survey and preview it on a very large screen (or zoom out)
> fix: mobile preview on large screens

- apps/web/modules/ui/components/tag/stories.tsx
Fixes https://github.com/formbricks/internal/issues/923
Test tag story
> chore: tag stories

- apps/web/app/(app)/environments/[environmentId]/actions/components/ActionSettingsTab.tsx
Fixes https://github.com/formbricks/internal/issues/939
Test issue mentioned in linked ticket regarding action class updation
> fix: update action class issue

- README.md
Congrats! We have onboarded Formbricks to LFX Insights, the Linux Foundation's platform for monitoring the world's most critical open-source projects.
https://insights.linuxfoundation.org/project/formbricks
> Add Linux Foundation health score badge to README

- .cursor/rules/documentations.mdc
- docs/docs.json
- docs/xm-and-surveys/core-features/user-management.mdx
- docs/xm-and-surveys/core-features/user-management/invite-members.mdx
- docs/xm-and-surveys/core-features/user-management/organizations-and-roles.mdx
- docs/xm-and-surveys/core-features/user-management/teams-and-roles.mdx
- docs/xm-and-surveys/core-features/user-management/two-factor-auth.mdx
> docs: clarified Roles docs + added 2FA

- .github/actions/build-and-push-docker/action.yml
- .github/actions/docker-build-setup/action.yml
- .github/actions/resolve-docker-version/action.yml
- .github/actions/update-package-version/action.yml
- .github/workflows/build-and-push-ecr.yml
- .github/workflows/deploy-formbricks-cloud.yml
- .github/workflows/formbricks-release.yml
- .github/workflows/move-stable-tag.yml
- .github/workflows/release-docker-github-experimental.yml
- .github/workflows/release-docker-github.yml
- .github/workflows/release-helm-chart.yml
This PR backports important workflow and action changes that are needed for the new release pipeline to work. 
It adds three composite actions: `build-and-push-docker`, `docker-build-setup`, and `resolve-docker-version`, each designed to handle input validation, secure versioning, and registry-specific logic for container builds and deployments.
**Docker Build and Push Workflow Enhancements**
* Added `.github/actions/build-and-push-docker/action.yml` to provide a comprehensive and configurable workflow for building and pushing Docker images to ECR and GHCR, supporting automatic version resolution, conditional tagging, and image signing.
* Introduced `.github/actions/resolve-docker-version/action.yml` to securely resolve and validate Docker-compatible SemVer versions, including …
> chore(backport): updated release workflow

- apps/web/app/(app)/environments/[environmentId]/settings/(account)/notifications/components/IntegrationsTip.test.tsx
- apps/web/app/(app)/environments/[environmentId]/settings/(account)/notifications/components/IntegrationsTip.tsx
- apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/summary/components/shareEmbedModal/success-view.tsx
- apps/web/app/api/google-sheet/callback/route.ts
- apps/web/app/api/v1/integrations/airtable/callback/route.ts
- apps/web/app/api/v1/integrations/notion/callback/route.ts
- apps/web/app/api/v1/integrations/slack/callback/route.ts
Fixes broken links for integrations
Try to connect integrations
> fix: integration redirect links

- apps/web/app/(app)/environments/[environmentId]/settings/(account)/notifications/components/IntegrationsTip.test.tsx
- apps/web/app/(app)/environments/[environmentId]/settings/(account)/notifications/components/IntegrationsTip.tsx
- apps/web/modules/ee/quotas/components/quota-list.tsx
- apps/web/modules/organization/settings/api-keys/components/add-api-key-modal.tsx
- apps/web/modules/organization/settings/api-keys/components/view-permission-modal.test.tsx
- apps/web/modules/organization/settings/api-keys/components/view-permission-modal.tsx
- apps/web/modules/organization/settings/api-keys/lib/utils.test.ts
- apps/web/modules/organization/settings/api-keys/lib/utils.ts
- apps/web/modules/survey/follow-ups/components/follow-up-item.tsx
Fixes 
Also Fixes https://github.com/formbricks/internal/issues/1073
After fix
test api key modal
> fix: api key modal tweaks

- packages/types/common.ts
Fixes https://github.com/formbricks/internal/issues/1074
We had `mailto:ceo@company.com`, as button url for CTA question in churn survey template. But we checks for https:// during zod validation, fixed it by adding support for mailto:
Create a churn survey
> fix: broken churn survey template

- apps/web/app/api/(internal)/pipeline/lib/handleIntegrations.ts
- apps/web/lib/responses.ts
- apps/web/lib/surveyLogic/utils.ts
- apps/web/modules/analysis/components/SingleResponseCard/components/RenderResponse.tsx
- apps/web/modules/analysis/components/SingleResponseCard/util.ts
- packages/surveys/src/components/general/question-conditional.tsx
- packages/surveys/src/components/questions/multiple-choice-single-question.tsx
- packages/surveys/src/lib/logic.ts
- packages/types/responses.ts
Fixes 
https://github.com/formbricks/internal/issues/1059
https://github.com/formbricks/internal/issues/1060
Test issue mentioned in linked tickets
> fix: logic issues

- apps/web/modules/survey/link/components/survey-renderer.tsx
Fixes https://github.com/formbricks/internal/issues/931
Test link previews for completed and paused surveys
> fix: block previews for completed and paused surveys

- docs/xm-and-surveys/surveys/general-features/quota-management.mdx
> docs: remove beta note

- apps/web/lib/jwt.test.ts
- apps/web/lib/jwt.ts
- apps/web/modules/auth/lib/authOptions.test.ts
- apps/web/modules/email/index.tsx
- docker/formbricks.sh
- docs/self-hosting/setup/one-click.mdx
We are backporting these 2 PRs to the 4.0 release:
https://github.com/formbricks/formbricks/pull/6604
https://github.com/formbricks/formbricks/pull/6596
> chore: backport jwt and script fix

- docs/self-hosting/advanced/license-activation.mdx
- docs/self-hosting/advanced/license.mdx
Update license activation page:
> docs: update license pages

- docs/docs.json
- docs/xm-and-surveys/surveys/general-features/tags.mdx
> docs: add tag docs
