components/form/NewFormModal.tsx, components/frontend/App.tsx, components/layout/BaseLayoutAuthorized.tsx, components/layout/BaseLayoutUnauthorized.tsx, lib/posthog.ts, next.config.js, package.json, pages/auth/signin.tsx, pages/auth/signup.tsx, pages/auth/verification-requested.tsx, pages/auth/verify.tsx, pages/f/[id].tsx, yarn.lock
add possibility to track events with posthog by setting environment variables POSTHOG_API_KEY and POSTHOG_API_HOST
=> add posthog integration

.gitignore, README.md
Took me a couple minutes to get the local setup going, though to add my 2 cents that'd have saved me those minutes
=> Clarifying README.md

pages/404.tsx
- Adds a 404.tsx into `/pages` with some basic layout and a link back to the homepage
=> #49: Update 404 page

components/FormList.tsx, components/layout/BaseLayoutManagement.tsx, components/layout/MenuBreadcrumbs.tsx, components/layout/NewFormNavButton.tsx, package.json, tailwind.config.js, yarn.lock
Fix issues with too long form names
=> Truncate formname #56

lib/posthog.ts, lib/telemetry.ts, lib/utils.ts, package.json, pages/api/forms/index.ts, pages/api/public/users/index.tsx, yarn.lock
Use simple API calls for Posthog Tracking to increase compatibility
=> Fix Posthog Tracking

components/editorjs/tools/EmailQuestion.tsx, components/editorjs/tools/MultipleChoiceQuestion.tsx, components/editorjs/tools/MultipleChoiceQuestionComponent.tsx, components/editorjs/tools/NumberQuestion.tsx, components/editorjs/tools/PhoneQuestion.tsx, components/editorjs/tools/TextQuestion.tsx, components/editorjs/tools/WebsiteQuestion.tsx, components/frontend/App.tsx, pages/forms/[id]/preview.tsx
- Adds `helperText` to `data` objects as well as adding necessary input fields
=> #21: Add helperText to all question types

apps/web/components/editorjs/tools/EmailQuestion.tsx, apps/web/components/editorjs/tools/EmailQuestionComponent.tsx
=> Refactor EmailQuestion Component

apps/web/components/editorjs/tools/TextQuestion.tsx, apps/web/components/editorjs/tools/TextQuestionComponent.tsx
=> Refactor TextQuestion Component

.envrc, .gitignore, apps/web/components/editorjs/tools/NumberQuestion.tsx, apps/web/components/editorjs/tools/NumberQuestionComponent.tsx, apps/web/components/editorjs/tools/PhoneQuestion.tsx, apps/web/components/editorjs/tools/PhoneQuestionComponent.tsx, apps/web/components/editorjs/tools/WebsiteQuestion.tsx, apps/web/components/editorjs/tools/WebsiteQuestionComponent.tsx, flake.lock, flake.nix, pnpm-lock.yaml
Hey, I wanted to refactor the phone, website, and number components. I also added [nixos](https://nixos.org/) development configs for everyone else who also uses nix to speed up the development time.
Resolves #99 
Resolves #98 
Resolves #97 
related: https://github.com/formbricks/snoopforms/pull/119
=> refactor: phone, website, number components, add: nixos development

apps/web/components/pipelines/emailNotification/SettingsComponent.tsx
Resolves #132
Fixed typo in email noification pipeline setting: webhooks -> email notifications
=> Fix Typo in Email Notification Pipeline Settings

apps/formbricks-com/pages/docs/react-form-library/input-checkbox/index.mdx, apps/formbricks-com/pages/docs/react-form-library/input-email/index.mdx, apps/formbricks-com/pages/docs/react-form-library/input-number/index.mdx, apps/formbricks-com/pages/docs/react-form-library/input-password/index.mdx, apps/formbricks-com/pages/docs/react-form-library/input-phone/index.mdx, apps/formbricks-com/pages/docs/react-form-library/input-radio/index.mdx, apps/formbricks-com/pages/docs/react-form-library/input-search/index.mdx, apps/formbricks-com/pages/docs/react-form-library/input-submit/index.mdx, apps/formbricks-com/pages/docs/react-form-library/input-text/index.mdx, apps/formbricks-com/pages/docs/react-form-library/input-textarea/index.mdx, apps/formbricks-com/pages/docs/react-form-library/input-url/index.mdx, apps/formbricks-com/pages/gdpr-guide.mdx, apps/formbricks-com/pages/gdpr.mdx, apps/formbricks-com/pages/privacy-policy.mdx
also added "imports" to all of the inputs in the docs
=> update privacy policy

apps/hq/src/components/forms/pipelines/AddPipelineModal.tsx, apps/hq/src/components/forms/pipelines/PipelineSettings.tsx, apps/hq/src/components/forms/pipelines/PipelinesOverview.tsx, apps/hq/src/components/forms/pipelines/slackNotification.tsx, apps/hq/src/components/forms/submissions/SubmissionDisplay.tsx, apps/hq/src/lib/email.ts, apps/hq/src/lib/pipelinesHandler.ts, apps/hq/src/lib/submissions.ts, packages/database/prisma/migrations/20230112143317_add_slack_notification/migration.sql, packages/database/prisma/schema.prisma, packages/feedback-widget/test-div.html
Add Slack Notification Pipeline
=> add slackNotification Pipeline

apps/web/src/components/forms/feedback/FeedbackResults.tsx, apps/web/src/components/forms/pipelines/PipelinesOverview.tsx, apps/web/src/components/forms/pmf/OverviewResults.tsx, apps/web/src/components/forms/pmf/PMFResults.tsx, apps/web/src/components/forms/pmf/SuperhumanApproach.tsx, apps/web/src/pages/_app.tsx
=> Prevent smartphone view + responsiveness settings for dashboards

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .devcontainer/docker-compose.yml, apps/demo/pages/demos/feedback.tsx, packages/feedback/src/errors.ts, packages/feedback/src/index.ts
Closes #199 
This PR includes:
- 3 Custom Error Classes
- FormbricksError
- InvalidConfigError
- NetworkError
- Configuration files for github codespaces/devcontainers
=> add: support for custom error handling

apps/web/src/components/layout/LayoutApp.tsx, apps/web/src/lib/email-template.ts, apps/web/src/lib/email.ts
updated styling and content of transactional email
=> Email templates

apps/web/README.md
- Indent code blocks and texts in enumeration appropriately to make auto-enumeration work.
- Use auto-enumeration (aka 1. for every enum item) to be more robust with respect to changes.
=> Improve apps/web/README.md by using auto-enumeration

apps/web/app/environments/[environmentId]/AddProductModal.tsx, apps/web/app/environments/[environmentId]/EnvironmentsNavbar.tsx, apps/web/lib/products/products.ts, apps/web/lib/teams.ts, apps/web/pages/api/v1/environments/[environmentId]/index.ts, apps/web/pages/api/v1/environments/[environmentId]/product/index.ts
=> Feature create new products

apps/web/components/preview/Modal.tsx, apps/web/components/preview/MultipleChoiceSingleQuestion.tsx, packages/js/src/components/MultipleChoiceSingleQuestion.tsx
https://github.com/formbricks/formbricks/issues/230
=> #230: add required attr to multiple choice inputs

apps/web/app/environments/[environmentId]/events/EventSettingsTab.tsx
Issue #234 
Before Updating the field 
While updating the field 
After the update we can see that action type is changed
=> fix: add functionality to make events editable after creating them

apps/formbricks-com/pages/docs/contributing/setup/index.mdx, apps/formbricks-com/pages/docs/self-hosting/deployment/index.mdx
update self-hosting guide & contributors project setup guide with more information
=> Improve Docs with better setup & deployment instructions

apps/formbricks-com/components/shared/Pricing.tsx
Fixes a typo in the pricing component.
=> Fix typo in Pricing.tsx

packages/ui/components/ErrorComponent.tsx
Fixes typos in error notification.
- Make the app to throw an uncaught error
- <s>I haven't read the [contributing guide](https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't performed a self-review of my own code and corrected any misspellings
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my PR needs changes to the documentation
- I haven't checked if my changes generate no new warnings
- I haven't checked if my changes generate build errors (`pnpm build`) or linting errors (`pnpm lint`)
- I haven't checked if I removed all console.logs's
- I haven't checked for merge conflicts by merging the latest changes from main with `git pull origin main`</s>
=> Fix typo in ErrorComponent

apps/web/components/auth/SigninForm.tsx, apps/web/components/auth/Testimonial.tsx
small changes to LP based on feedback: https://github.com/formbricks/design/issues/14
=> Improvements to Auth Screen based on Design Feedback

apps/web/app/s/[surveyId]/LinkSurvey.tsx
=> update preview UI

apps/web/app/api/pipeline/route.ts
Await sendResponseFinishedEmail to fix email not sending on vercel
- Test A
- Test B
=> await sendResponseFinishedEmail

apps/formbricks-com/components/shared/Footer.tsx, apps/formbricks-com/pages/oss-friends.tsx
add OSS Friends subpage + footer link
=> add oss-friends page

apps/formbricks-com/pages/oss-friends.tsx
Add Hanko to OSS Friends page
--
=> add hanko to oss friends

.github/PULL_REQUEST_TEMPLATE.md
=> fix typo in PR template

.github/PULL_REQUEST_TEMPLATE.md
update wording in PR checklist
=> update wording in PR checklist

apps/formbricks-com/pages/oss-friends.tsx
* Updates OpenBB Text on the oss-friends page
* Text changes only
- Small text update solely
=> Update oss-friends.tsx w OpenBB text

packages/js/package.json
Update JS package version to 0.1.18
=> update package version to 0.1.18

apps/web/app/api/v1/client/actions/route.ts, apps/web/app/api/v1/client/displays/[displayId]/responded/route.ts, apps/web/app/api/v1/client/displays/route.ts, apps/web/app/api/v1/client/responses/[responseId]/route.ts, apps/web/app/api/v1/client/responses/route.ts, apps/web/app/api/v1/client/sessions/route.ts, apps/web/app/api/v1/client/settings/route.ts, apps/web/app/api/v1/client/users/[userCuid]/attribute/route.ts, apps/web/app/api/v1/client/users/[userCuid]/user-id/route.ts, apps/web/app/api/v1/client/users/route.ts, apps/web/lib/api/response.ts, apps/web/lib/utils.ts, packages/js/src/lib/commandQueue.ts, packages/js/src/lib/errors.ts, packages/js/src/lib/init.ts, packages/js/src/lib/noCodeEvents.ts
Add new client Endpoints for App-Router (WIP)
Fix Logging in JS Client
=> Add new client Endpoints for App-Router (WIP)

packages/js/package.json
update formbricks js to 0.1.19
=> update formbricks js to 0.1.19

packages/database/package.json, pnpm-lock.yaml
Update Prisma version to benefit from new performance improvements
=> Update Prisma version for performance improvements

apps/formbricks-com/pages/oss-friends.tsx
add Boxy HQ to OSS Friends page
=> Add BoxyHQ to OSS Friends

apps/web/app/auth/login/page.tsx, apps/web/app/auth/signup/page.tsx, apps/web/app/environments/[environmentId]/surveys/[surveyId]/SurveyResultsTabs.tsx, apps/web/app/environments/[environmentId]/surveys/[surveyId]/edit/LogicEditor.tsx, apps/web/app/environments/[environmentId]/surveys/[surveyId]/edit/MultipleChoiceMultiForm.tsx, apps/web/app/environments/[environmentId]/surveys/[surveyId]/edit/MultipleChoiceSingleForm.tsx, apps/web/app/environments/[environmentId]/surveys/[surveyId]/edit/QuestionCard.tsx, apps/web/app/environments/[environmentId]/surveys/[surveyId]/edit/QuestionDropdown.tsx, apps/web/app/environments/[environmentId]/surveys/[surveyId]/edit/QuestionsView.tsx, apps/web/components/auth/FormWrapper.tsx, apps/web/components/auth/SigninForm.tsx, apps/web/components/auth/SignupForm.tsx, apps/web/components/auth/Testimonial.tsx, apps/web/components/environments/SecondNavBar.tsx, apps/web/components/shared/SurveyNavBarName.tsx
Adds Duplicate Question functionality
Adds survey name to summary page:
Introduces changes to Login Screen (as discussed in design repo):
=> Duplicate Questions, Add Survey Name to Summary, Update Login Screen

README.md
Update Upcoming Features in Readme
=> Update Upcoming Features in Readme

apps/formbricks-com/pages/docs/contributing/setup/index.mdx, apps/web/Dockerfile, package.json, packages/database/prisma/migrations/20230531143258_remove_user_attributes_from_response/migration.sql, packages/types/responses.ts, turbo.json
fix prisma commands with new json plugin
=> fix prisma commands with new json plugin

apps/web/app/environments/[environmentId]/surveys/SurveyList.tsx
fix security issue in "Show Preview" link. (Potentially unsafe external link - External links without noopener/noreferrer are a potential security risk.)
=> fix security issue in link

apps/formbricks-com/pages/oss-friends.tsx
=> Reorder OSS Friends (alphabetically)

apps/web/app/environments/[environmentId]/EnvironmentsNavbar.tsx, apps/web/app/environments/[environmentId]/FormbricksClient.tsx, apps/web/app/onboarding/Objective.tsx, apps/web/app/onboarding/Role.tsx, apps/web/lib/formbricks.ts, apps/web/pages/api/v1/client/environments/[environmentId]/people/[personId]/user-id.ts, packages/js/src/index.ts, packages/js/src/lib/commandQueue.ts
Fix multiple issues when using Formbricks within Formbricks
* add `await` option for all @formbricks/js commands
* fix logout in Formbricks app also removes sdk user
* improve onboarding data sent to Formbricks by using label instead of id
* fix typos
=> Multiple fixes for Formbricks usage within Formbricks

apps/web/app/onboarding/Objective.tsx
mark onboarding responses as finished in formbricks
=> mark onboarding responses as finished in formbricks

apps/formbricks-com/components/shared/Header.tsx, apps/formbricks-com/pages/careers.tsx, apps/formbricks-com/pages/oss-friends.tsx
=> add careers page, update OSS friends

apps/web/app/FormbricksClient.tsx, packages/api/package.json, packages/database/package.json, packages/errors/package.json, packages/js/app.html, packages/js/package.json, packages/js/src/lib/api.ts, packages/js/src/lib/widget.ts, packages/lib/package.json, pnpm-lock.yaml
Include formbricks-api into formbricks-js and fix multiple issues with package deployment, building and usage
=> Include formbricks-api into formbricks-js

apps/web/app/s/[surveyId]/LinkSurvey.tsx
Fix issue #357 where link survey breaks when question is too long.
=> fix FOR-760

apps/formbricks-com/pages/docs/webhook-api/overview/index.mdx
Update webhook overview doc with more usage information
- How to authorize
- What are triggers
- Which updates to I receive
=> Update webhook overview doc with more usage information

apps/web/app/environments/[environmentId]/surveys/[surveyId]/responses/ResponseNote.tsx, apps/web/app/environments/[environmentId]/surveys/[surveyId]/responses/SingleResponse.tsx, packages/types/v1/responses.ts
=> update note height and fix multiple choice zod

apps/web/app/environments/[environmentId]/attributes/AttributeClassesList.tsx, apps/web/app/environments/[environmentId]/settings/members/EditMemberships.tsx
It adds a separate column in member settings which shows user role
Fixes #369 
- Go to settings
- Click on members on left navbar, you should be able to see separate user column
=> Feat: Add a column to add user roles and added useMemo in attributeclassesList

apps/web/app/api/v1/client/responses/[responseId]/route.ts, apps/web/app/api/v1/client/responses/route.ts, apps/web/lib/pipelines.ts, packages/types/v1/pipelines.ts, packages/types/v1/webhooks.ts
fix email notifications display empty responses, fix webhook data format
=> fix email notifications display empty responses, fix webhook data format

pnpm-lock.yaml
Update pnpm lock file to fix Docker build issues
=> Update pnpm lock file to fix Docker build issues

apps/web/app/environments/[environmentId]/attributes/AttributeActivityTab.tsx, apps/web/app/environments/[environmentId]/attributes/AttributeDetailModal.tsx, apps/web/lib/attributeClasses/attributeClasses.ts, apps/web/pages/api/v1/environments/[environmentId]/attribute-classes/[attributeClassId]/index.ts
Fixes #388
https://github.com/formbricks/formbricks/assets/69904519/55ea2666-c6d5-49cc-abf5-f9aca5fdc9c0
- Go to actions and attributes and go to the attributes tab then click on any attribute
=> feat: active and inactive surveys in attribute list

apps/web/app/api/pipeline/route.ts, apps/web/app/environments/[environmentId]/surveys/[surveyId]/edit/AudienceView.tsx, apps/web/app/environments/[environmentId]/surveys/[surveyId]/edit/ResponseOptionsCard.tsx, packages/database/migrations/20230616174129_add_auto_complete_in_survey_schema/migration.sql, packages/database/schema.prisma, packages/js/src/lib/event.ts, packages/types/surveys.ts
Allows users to set a certain number after which , the form stops accepting responses
Fixes #389
Loom Video: https://www.loom.com/share/60e579c62a614cadba9a0b00e4b893cb?sid=265c85d8-03d6-4654-840e-4d5499f297f2
Screenshots
- Test A
- Test B
=> mark survey as completed after x responses

apps/web/app/environments/[environmentId]/attributes/AttributeClassesList.tsx, apps/web/app/environments/[environmentId]/attributes/AttributeSettingsTab.tsx, apps/web/app/environments/[environmentId]/people/[personId]/PersonDetails.tsx, apps/web/app/environments/[environmentId]/settings/members/EditMemberships.tsx, apps/web/app/environments/[environmentId]/surveys/[surveyId]/edit/AudienceView.tsx, apps/web/app/environments/[environmentId]/surveys/[surveyId]/edit/MultipleChoiceMultiForm.tsx, apps/web/app/environments/[environmentId]/surveys/[surveyId]/edit/UpdateQuestionId.tsx, apps/web/app/environments/[environmentId]/surveys/[surveyId]/edit/WhoToSendCard.tsx, apps/web/components/shared/DeleteDialog.tsx, megaprompt.md, packages/api/src/types.d.ts
Format code according to prettier rules in all files
=> Format code according to prettier rules in all files

apps/demo/pages/app/index.tsx
=> fix responsiveness of demo app

apps/web/app/environments/[environmentId]/settings/product/editProduct.tsx
improve delete product dialog, send error toast on failed request
=> improve delete product dialog, send error toast on failed request

apps/web/app/environments/[environmentId]/settings/members/AddMemberModal.tsx, apps/web/app/environments/[environmentId]/settings/members/EditMemberships.tsx, apps/web/lib/api/apiHelper.ts, apps/web/lib/members.ts, apps/web/pages/api/v1/teams/[teamId]/invite/[inviteId]/index.ts, apps/web/pages/api/v1/teams/[teamId]/invite/index.ts, apps/web/pages/api/v1/teams/[teamId]/members/[userId]/index.ts
Fixes #385 
- Added Feature to update Member Role by adding a Select Component to Add Member Modal
- Added Feature to update Invitee Role by adding a Select Component to Add Member Modal
- Updated Add Member button variant to Dark CTA.
- Added Server Side Validations to allow role updation only for Users with Owner and Admin level Access.
- Added functionality to prevent user's from modifying their own role.
- Added UI to show badge for Role display if the current user is doesn't have Admin or Owner level access, and if the users have owner or admin level access they would see a dropdown button to update the Role.
- Added UI to enable Add Member feature only for users with Admin or Owner level access.
=> [FEATURE]: Add user roles to invite and allow changing roles

apps/formbricks-com/components/dummyUI/QuestionConditional.tsx, apps/web/app/environments/[environmentId]/surveys/[surveyId]/edit/LogicEditor.tsx, apps/web/app/environments/[environmentId]/surveys/[surveyId]/edit/QuestionCard.tsx, apps/web/app/environments/[environmentId]/surveys/[surveyId]/responses/SingleResponse.tsx, apps/web/app/environments/[environmentId]/surveys/[surveyId]/summary/MultipleChoiceSummary.tsx, apps/web/app/environments/[environmentId]/surveys/[surveyId]/summary/RatingSummary.tsx, apps/web/app/environments/[environmentId]/surveys/[surveyId]/summary/SummaryList.tsx, apps/web/components/preview/QuestionConditional.tsx, apps/web/lib/questions.ts, packages/js/src/components/QuestionConditional.tsx, packages/types/questions.ts, packages/types/v1/surveys.ts
Added questionType enum in place of strings to attain consistency 
Refactoring
- Test A
- Test B
=> refactor: added questionType enum in place of strings

pnpm-lock.yaml
fix compatibility issue with new pnpm version
=> fix compatibility issue with new pnpm version

apps/formbricks-com/components/shared/Header.tsx, apps/formbricks-com/pages/careers.tsx, apps/formbricks-com/pages/community.tsx, apps/web/app/billing-confirmation/ConfirmationPage.tsx, apps/web/app/environments/[environmentId]/AddProductModal.tsx, apps/web/app/environments/[environmentId]/attributes/AttributeSettingsTab.tsx, apps/web/app/environments/[environmentId]/events/AddNoCodeEventModal.tsx, apps/web/app/environments/[environmentId]/events/EventSettingsTab.tsx, apps/web/app/environments/[environmentId]/integrations/alerts/slack/AddSlackAlertModal.tsx, apps/web/app/environments/[environmentId]/surveys/[surveyId]/edit/UpdateQuestionId.tsx, apps/web/app/environments/[environmentId]/surveys/[surveyId]/summary/LinkSurveyModal.tsx
=> remove careers page, update remaining CTAs

packages/database/migrations/20230626105714_add_redirect_url/migration.sql, packages/types/v1/surveys.ts
=> add missing migration

packages/js/package.json
update formbricks-js to 0.1.22
=> update formbricks-js to 0.1.22

apps/formbricks-com/components/shared/Pricing.tsx, apps/web/app/environments/[environmentId]/settings/billing/PricingTable.tsx
=> remove early bird

apps/web/app/api/v1/client/environments/[environmentId]/people/getOrCreate/route.ts, apps/web/app/api/v1/client/people/getOrCreate/route.ts, apps/web/lib/api/clientPerson.ts, apps/web/lib/linkSurvey/linkSurvey.ts, apps/web/lib/people/people.ts
Connects link survey responses to **Person** in the Formbricks database.
Fixes #384 
https://github.com/formbricks/formbricks/assets/1277672/c288e038-862a-495a-a38d-4c7d28bdb677
Create responses and then check the survey responses from `Responses` tab.
=> [FEATURE] identify users in link surveys #384

apps/formbricks-com/components/home/GitHubSponsorship.tsx, apps/formbricks-com/components/home/Hero.tsx, apps/formbricks-com/components/shared/Footer.tsx, apps/formbricks-com/components/shared/Header.tsx, apps/formbricks-com/package.json, apps/formbricks-com/pages/concierge.tsx, apps/formbricks-com/pages/index.tsx, pnpm-lock.yaml
Add Concierge Page to Landing Page
=> Add Concierge Page to Landing Page

apps/formbricks-com/next.config.mjs
=> forward /deal

apps/web/app/api/v1/client/people/getOrCreate/route.ts
fix userId prefilling not working properly
=> fix userId prefilling not working properly

apps/web/app/environments/[environmentId]/surveys/[surveyId]/ResponsesLimitReachedBanner.tsx, apps/web/app/environments/[environmentId]/surveys/[surveyId]/responses/page.tsx, apps/web/app/environments/[environmentId]/surveys/[surveyId]/summary/LinkModalButton.tsx, apps/web/app/environments/[environmentId]/surveys/[surveyId]/summary/StatusDropdown.tsx, apps/web/app/environments/[environmentId]/surveys/[surveyId]/summary/SuccessMessage.tsx, apps/web/app/environments/[environmentId]/surveys/[surveyId]/summary/SummaryList.tsx, apps/web/app/environments/[environmentId]/surveys/[surveyId]/summary/SummaryMetadata.tsx, apps/web/app/environments/[environmentId]/surveys/[surveyId]/summary/page.tsx, packages/lib/package.json, packages/lib/services/response.ts, packages/lib/services/survey.ts, pnpm-lock.yaml
fix necessary hard reload on responses summary and list
=> fix necessary hard reload on responses summary and list

README.md
i used the link thats being used on the website: https://cal.com/johannes/onboarding
=> added contact link to readme

packages/database/package.json, packages/tailwind-config/tailwind.config.js
Fix Widget Position not working in Preview
=> Fix Widget Position not working in Preview

apps/web/app/environments/[environmentId]/settings/members/EditMemberships.tsx, apps/web/app/environments/[environmentId]/settings/members/ShareInviteModal.tsx, apps/web/lib/members.ts, apps/web/pages/api/v1/teams/[teamId]/invite/[inviteId]/index.ts, packages/tailwind-config/tailwind.config.js
Added an icon in the edit team member section to allow user to share an invite link. When the user clicks on the share icon, a modal will pop up to display the invite link.
Fixes #249 
ShareInviteModal:
Go to the member page in the teams settings, add a new team member, then click the share icon. copy and send the link to that member. Once the member opens that link, they should be added to the team. 
Tested with two separate accounts in local env.
=> Feature: share team invite link

apps/web/app/onboarding/Onboarding.tsx
fix error during onboarding when environment not fully loaded
=> fix error during onboarding when environment not fully loaded

apps/web/app/api/v1/responses/route.ts, packages/lib/services/response.ts
add response poll endpoint for zapier
=> add response poll endpoint for zapier

apps/web/README.md
Fixing the web package's readme
- [x ] Bug fix (non-breaking change which fixes an issue)
Read over it
=> fix README.md for dev setup

apps/web/app/environments/[environmentId]/EnvironmentsNavbar.tsx, packages/lib/constants.ts
Add Feedback Box to Formbricks. Top Right Menu -> "Product Feedback"
=> Add Feedback Box

README.md
=> Update images in ReadMe

README.md
=> Add dark mode images

README.md
=> fix images

.github/ISSUE_TEMPLATE/feature_request.md, apps/web/app/environments/[environmentId]/settings/members/EditMemberships.tsx, apps/web/pages/api/v1/teams/[teamId]/invite/[inviteId]/index.ts, packages/js/src/lib/noCodeEvents.ts, packages/js/tests/__mocks__/apiMock.ts, packages/js/tests/constants.ts, packages/js/tests/index.test.ts, packages/js/tests/types.ts
=> Fix formatting issues

apps/formbricks-com/pages/concierge.tsx
=> remove GitHub Deal

apps/web/app/environments/[environmentId]/surveys/[surveyId]/responses/SingleResponse.tsx
Fixes #477
- View survey responses
=> fix: display user email in survey responses

apps/web/app/environments/[environmentId]/people/loading.tsx, apps/web/app/environments/[environmentId]/people/page.tsx, packages/lib/services/person.ts
Fix people service loading time
=> Fix people service loading time

packages/lib/services/person.ts, packages/types/v1/people.ts, packages/types/v1/surveys.ts
Fix autoComplete survey schema validation
=> Fix autoComplete survey schema validation

apps/web/lib/linkSurvey/linkSurvey.ts
1. Added prefill for consent question type
2.  fixed the prefiling loader bug
https://github.com/formbricks/formbricks/assets/56182734/bae2f968-e7dc-4579-8c7e-3e70bd9c44cc
- Test A
- Test B
=> feat: Added prefill for consent question type and fixed the loader bug

apps/formbricks-com/components/home/Hero.tsx, apps/formbricks-com/components/shared/BestPracticeNavigation.tsx, apps/formbricks-com/pages/blog/github-accelerator-experience/index.mdx
=> fix lp & update blog

apps/web/env.mjs
Fix Zod Schema for PRISMA_GENERATE_DATAPROXY env variable
=> Fix Zod Schema for PRISMA_GENERATE_DATAPROXY env variable

apps/web/env.mjs
Add empty string dataproxy env to enable dev development without proxy
- Test A
- Test B
=> Add empty string dataproxy env

apps/web/app/environments/[environmentId]/surveys/[surveyId]/edit/UpdateQuestionId.tsx
Fixes #483
https://github.com/formbricks/formbricks/assets/26919832/a2e34328-7f55-4745-a227-d28ff200e15a
1. Open Survey
2. Find the Question Card and select it.
3. In the Question Card settings, go to the Advanced Settings section.
4. Locate the questionId field and attempt to edit it by adding a space.
5. If the questionId input contains a space, you will observe a red border color indicating an error.
6. Additionally, the save button should be disabled, preventing you from saving the changes until the questionId input is corrected.
7. Try to remove any spaces from the questionId input before proceeding.
=> Fix space not allowed in questionid input

.env.example, .github/workflows/checks.yml
add .env file to checks workflow
=> add .env file to checks workflow

apps/web/Dockerfile
=> fix next config suffix

apps/web/app/api/v1/responses/route.ts, apps/web/app/environments/[environmentId]/surveys/[surveyId]/ResponsesLimitReachedBanner.tsx, apps/web/app/environments/[environmentId]/surveys/[surveyId]/responses/page.tsx, apps/web/app/environments/[environmentId]/surveys/[surveyId]/summary/SummaryList.tsx, apps/web/app/environments/[environmentId]/surveys/[surveyId]/summary/data.ts
add SurveyId filter option to responses endpoint
=> add SurveyId filter option to responses endpoint

packages/lib/services/survey.ts, pnpm-lock.yaml
Fix duplicated closeOnDate in survey service
=> Fix duplicated closeOnDate in survey service

apps/formbricks-com/pages/docs/link-surveys/data-prefilling/index.mdx, apps/web/app/environments/[environmentId]/surveys/[surveyId]/edit/ResponseOptionsCard.tsx, packages/ui/components/DatePicker.tsx
- Refactor Response Settings
- Fix Typo in Docs
Play around with it once. 
- [X ] Filled out the "How to test" section in this PR
- [ X] Read the [contributing guide](https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md)
- [ X] Self-reviewed my own code
- [ v] Commented on my code in hard-to-understand bits
- [ X] Ran `pnpm build`
- [ X] Checked for warnings, there are none
- [ X] Removed all `console.logs`
- [ X] Merged the latest changes from main onto my branch with `git pull origin main`
- [ X] My changes don't cause any responsiveness issues
- [ X] Updated the Formbricks Docs if changes were necessary
=> refactor response settings

apps/web/app/environments/[environmentId]/surveys/[surveyId]/edit/LogicEditor.tsx, apps/web/app/environments/[environmentId]/surveys/[surveyId]/edit/QuestionCard.tsx, apps/web/app/environments/[environmentId]/surveys/[surveyId]/edit/QuestionsView.tsx
Fixes #524 
https://github.com/formbricks/formbricks/assets/67850763/e8d409e3-82a8-4752-9b97-d4082f08c3dd
1) Create a survey that involves branching
2) Change questionIds
3) Take the survey
=> FIX : QuestionIds not updating in existing logic

.github/workflows/cron-weeklySummary.yml, apps/web/app/api/pipeline/route.ts
Fix email notification not working
=> Fix email notification not working

apps/web/pages/api/v1/environments/[environmentId]/surveys/[surveyId]/index.ts
fix error while saving in-app surveys
=> fix error while saving in-app surveys

packages/js/src/components/CTAQuestion.tsx, packages/js/src/components/ConsentQuestion.tsx, packages/js/src/components/MultipleChoiceMultiQuestion.tsx, packages/js/src/components/MultipleChoiceSingleQuestion.tsx, packages/js/src/components/NPSQuestion.tsx, packages/js/src/components/OpenTextQuestion.tsx, packages/js/src/components/RatingQuestion.tsx, packages/js/src/components/SurveyView.tsx, packages/js/src/lib/noCodeEvents.ts, packages/js/src/lib/person.ts
fix client-side errors in formbricks-js
=> Fix multiple client-side errors in formbricks-js

apps/web/app/environments/[environmentId]/settings/members/EditMemberships.tsx
- fixes that non admins and owners see delete member ui
- fixes that you can remove yourself from a team (caused an error if its the only team you're in)
=> fix delete member ui

.changeset/config.json, .github/workflows/release.yml, package.json
=> Fix changesets config

apps/web/app/environments/[environmentId]/surveys/[surveyId]/edit/SurveyMenuBar.tsx
Just fix the condition using double negation so that it result into a boolean value
Fixes #548 
- Create a survey and publish it
- Try to edit that survey and make sure that there is no response in that survey
- In the survey menubar, you will now not see 0 in the middle of the menu bar
=> Fix the condition for 0 response in survey menubar

apps/web/app/environments/[environmentId]/surveys/[surveyId]/QuestionFilterComboBox.tsx, apps/web/app/environments/[environmentId]/surveys/[surveyId]/QuestionsComboBox.tsx, apps/web/app/environments/[environmentId]/surveys/[surveyId]/SummaryHeader.tsx, packages/ui/components/Command.tsx
- Switched Survey Name and Product Name
- Added hover bg to filter dropdown
- Changed font to match other dropdowns
-
Yes
=> improve filter ux, update summary header

apps/web/app/environments/[environmentId]/surveys/[surveyId]/edit/MultipleChoiceMultiForm.tsx, apps/web/app/environments/[environmentId]/surveys/[surveyId]/edit/MultipleChoiceSingleForm.tsx, apps/web/app/environments/[environmentId]/surveys/[surveyId]/edit/RecontactOptionsCard.tsx, apps/web/app/environments/[environmentId]/surveys/[surveyId]/edit/WhenToSendCard.tsx, apps/web/app/environments/[environmentId]/surveys/[surveyId]/edit/WhoToSendCard.tsx, apps/web/components/preview/MultipleChoiceSingleQuestion.tsx
=> fix order dropdown, other field and UX tweaks

.github/workflows/cron-weeklySummary.yml, packages/database/package.json
Fix weekly summary cron workflow
=> Fix weekly summary cron workflow

apps/web/app/environments/[environmentId]/surveys/[surveyId]/(analysis)/responses/ResponseTagsWrapper.tsx, apps/web/app/environments/[environmentId]/surveys/[surveyId]/(analysis)/responses/Tag.tsx, apps/web/pages/api/v1/environments/[environmentId]/tags/merge.ts
=> fix: fixes tag merging logic

apps/formbricks-com/pages/docs/getting-started/quickstart/index.mdx, apps/web/app/environments/[environmentId]/settings/setup/SetupInstructions.tsx
Update formbricks-js version in html docs
=> Update formbricks-js version in html docs

apps/formbricks-com/components/home/GitHubSponsorship.tsx, apps/formbricks-com/components/home/Hero.tsx
- Media query for the GitHub Sponsorship div for margin to come into play only on wider screens
- Reduce horizontal padding in Hero Section (Star us onGithub) div that worked for bigger screens as well
=> Minor Responsiveness bugs in iPhone Mini screens

packages/js/tests/__mocks__/apiMock.ts
The JS tests were broken when we updated the response format of our API! This PR updates the responses as per the current format and the JS tests now are working again! 🚀 
The new response data is now wrapped under a `data:{}` field which does the job! Hence replicated the same in the mocked responses!
`pnpm run test`
=> Update new API Response Formats in Jest JS Package Testing

apps/formbricks-com/pages/docs/client-api/create-response/index.mdx, apps/web/app/api/pipeline/route.ts, apps/web/app/api/v1/client/responses/[responseId]/route.ts, apps/web/app/api/v1/client/responses/route.ts, apps/web/app/api/v1/webhooks/route.ts, apps/web/lib/email.ts, apps/web/lib/pipelines.ts, apps/web/lib/responses/questionResponseMapping.ts, apps/web/pages/api/v1/client/environments/[environmentId]/responses/[responseId]/index.ts, apps/web/pages/api/v1/client/environments/[environmentId]/responses/index.ts, packages/database/schema.prisma, packages/database/zod-utils.ts, packages/lib/constants.ts, packages/lib/services/apiKey.ts, packages/lib/services/response.ts, packages/lib/time.ts, packages/types/v1/pipelines.ts, packages/types/v1/responses.ts
=> Fix Email Notifications

LICENSE, apps/formbricks-com/pages/imprint.mdx, apps/formbricks-com/pages/privacy-policy.mdx, apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/responses/SingleResponse.tsx, packages/database/jsonTypes.ts, packages/errors/LICENSE, packages/js/LICENSE, packages/types/v1/responses.ts
Fix build errors and update contact to Formbricks GmbH
=> Fix build errors and update contact to Formbricks GmbH

apps/formbricks-com/pages/concierge.tsx
The /concierge page had uneven div containers due to cal.com internally setting a margin-top to their container! This overwrites the same and balances them
=> Landing Page: Balance cal.com widget with Concierge Div

apps/formbricks-com/pages/docs/getting-started/nextjs-app/index.mdx
Update docs for nextjs setup with app directory
=> Update docs for nextjs setup with app directory

apps/web/app/(app)/billing-confirmation/ConfirmationPage.tsx, apps/web/app/(app)/environments/[environmentId]/EnvironmentsNavbar.tsx, apps/web/app/(app)/environments/[environmentId]/settings/billing/PricingTable.tsx, apps/web/app/(app)/environments/[environmentId]/settings/billing/page.tsx
=> Update Stripe Data

apps/web/pages/api/v1/client/environments/[environmentId]/responses/[responseId]/index.ts, apps/web/pages/api/v1/client/environments/[environmentId]/responses/index.ts, packages/lib/services/attributeClass.ts
Fix legacy sdk endpoints not working with new services
- Test A
- Test B
=> Fix legacy sdk endpoints not working with new services

apps/web/app/(app)/environments/[environmentId]/actions.ts
=> Fix build errors

apps/web/app/api/auth/[...nextauth]/authOptions.ts
Fix 404 when Email exists in GitHub Login
=> Fix 404 when Email exists in GitHub Login

apps/web/app/api/cron/weekly_summary/email.ts, apps/web/app/api/cron/weekly_summary/route.ts
- fix calculation of completion rate
- fix email for "Live survey but no response this week"
- tweak UI
=> Fix several bugs in Weekly

package.json, packages/database/package.json, turbo.json
Fix errors in pnpm go script dependencies
=> Fix errors in pnpm go script dependencies

apps/web/app/(app)/environments/[environmentId]/surveys/page.tsx
Fix: Add revalidation to surveys overview page
=> Fix: Add revalidation to surveys overview page

apps/formbricks-com/pages/api/oss-friends/index.ts
Add OSS friends api endpoint
resolves #603
=> Add OSS friends api endpoint

apps/formbricks-com/lib/docsNavigation.ts, apps/formbricks-com/pages/docs/webhook-api/webhook-payload/index.mdx
Adds documentation for webhook payload
Fixes #516 
Visit [Formbricks docs](https://formbricks.com/docs)
Check **webhook payload** under Webhook API section
=> Docs : Webhook payload documentation update

apps/web/app/(app)/environments/[environmentId]/surveys/PreviewSurvey.tsx, apps/web/app/s/[surveyId]/LinkSurvey.tsx, apps/web/components/preview/OpenTextQuestion.tsx, apps/web/components/preview/QuestionConditional.tsx
Fix: Disable autoFocus when embedded with iframe
=> Fix: Disable autoFocus when embedded with iframe

apps/web/components/Smileys.tsx, packages/js/src/components/Smileys.tsx
Fix smileys in rating questions not showing in Safari Browser
=> Fix smileys in rating questions not showing in Safari Browser

.github/workflows/cron-weeklySummary.yml, apps/web/pages/api/v1/client/environments/[environmentId]/sessions/index.ts
Fix session creation endpoint throw unexpected error
=> Fix session creation endpoint throw unexpected error

apps/web/app/api/v1/webhooks/[webhookId]/route.ts, apps/web/lib/api/response.ts, packages/lib/services/webhook.ts
Fix Authentication issues for Webhook API
=> Fix Authentication issues for Webhook API

.changeset/young-snails-drum.md, apps/web/Dockerfile, apps/web/app/api/v1/js/sync/route.ts, apps/web/lib/responses/questionResponseMapping.ts, packages/js/src/lib/init.ts, packages/js/src/lib/person.ts, packages/js/src/lib/sync.ts, packages/js/src/lib/widget.ts
Fix new Session event not triggered every time a new session is created
=> Fix new Session event not triggered every time a new session is created

apps/formbricks-com/pages/api/oss-friends/index.ts
=> Add Twenty.com to OSS friends

docker/docker-compose.yml, docker/production.sh
Work on the feedback given from OhMyForm and make the production deployment script cleaner!
- Handles the cases where the `openssl rand` command generated special characters that were not parsable by the `sed` command into the docker file hence it now works everytime without any bugs!
- Shifts the Postgres DB password envirnment variable inside the environment itself in the docker compose file as well as the production.sh for a cleaner way to handle vars.
Fire up an EC2 instance, copy the script and run it!
=> Cleaner Production Script 

apps/formbricks-com/pages/docs-feedback/index.tsx, apps/formbricks-com/pages/docs/api/api-key-setup/index.mdx, apps/formbricks-com/pages/docs/webhook-api/webhook-payload/index.mdx, apps/formbricks-com/pages/imprint.mdx, apps/formbricks-com/pages/oss-friends.tsx, apps/formbricks-com/pages/privacy-policy.mdx, apps/formbricks-com/pages/terms.mdx, apps/web/app/(auth)/auth/login/page.tsx, apps/web/components/auth/SignupForm.tsx
=> Fix SEMRush SEO issues

.changeset/three-masks-retire.md, packages/js/src/components/FormbricksSignature.tsx, packages/js/src/components/Headline.tsx, packages/js/src/components/HtmlBody.tsx, packages/js/src/components/Modal.tsx, packages/js/src/components/Subheader.tsx, packages/js/tailwind.config.js
Increase formbricks-js z-index to 999999 to increase compatibility with more websites
=> Increase formbricks-js z-index to 999999 to increase compatibility with more websites

apps/formbricks-com/components/shared/APILayout.tsx, apps/formbricks-com/pages/docs/webhook-api/create-webhook/index.mdx
- Create Webhook had invalid body key
- Request headers were not showing the asterisk even when they were required
=> Fix Webhook API Documentation

apps/web/app/api/cron/weekly_summary/email.ts, apps/web/app/api/cron/weekly_summary/route.ts
Fix Weekly: Remove N/A completion rate, exclude "completed" survey if has no submission in last 7 days
Tested it
=> Fix Weekly: Remove N/A completion rate, exclude "completed" survey if has no submission in last 7 days

apps/web/components/preview/MultipleChoiceMultiQuestion.tsx, packages/types/v1/product.ts
Simplify highlightBorderColor in product type
=> Simplify highlightBorderColor in product type

packages/lib/services/product.ts, packages/types/v1/product.ts
Fix product service throwing validation error
=> Fix product service throwing validation error

apps/web/components/preview/Modal.tsx
=> Fix build error

pnpm-lock.yaml
'
Update npm packages to latest minor version
=> Update npm packages to latest minor version

turbo.json
Add prebuild as a build dependency
=> Add prebuild as a build dependency

pnpm-lock.yaml
=> Update pnpm lock file

apps/web/app/(app)/environments/[environmentId]/settings/members/DeleteTeam.tsx, packages/js/src/components/SurveyView.tsx
Fixes [1106](https://linear.app/formbricks/issue/FOR-1106/bug-call-to-action-card-dismiss-button-in-the-widget-not-working)
https://github.com/formbricks/formbricks/assets/67850763/a66b1959-06e3-4f08-ad42-7c2395857275
Create a survey beginning with call to action card
Click on skip (No thanks)
=> Fix: Call to Action card dismiss button issue

apps/web/lib/linkSurvey/linkSurvey.ts, packages/js/src/lib/localStorage.ts, pnpm-lock.yaml
Fix back button in link surveys follow logic jumps
- Create a new link survey (ideally with logic jumps)
- Fill out the link survey and check the response in Formbricks
- Check if logic jumps work
- Go back after following logic jumps
- Reload the page in the middle of the survey and check if the survey continues and if following answers are stored correctly in the previous response
=> Fix back button in link surveys follow logic jumps

apps/web/app/(app)/environments/[environmentId]/settings/profile/actions.ts, apps/web/lib/linkSurvey/linkSurvey.ts, packages/types/v1/profile.ts
Fix thank you screen is disabled after completing a survey
=> Fix thank you screen is disabled after completing a survey

apps/formbricks-com/pages/docs/self-hosting/deployment/index.mdx, docker-compose.yml
…ucture
Use .env.docker in advanced docker-compose setup to simplify file structure
=> Use .env.docker in advanced docker-compose setup to simplify file structure

apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/SurveyEditor.tsx, apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/SurveyMenuBar.tsx
Fix saved changes are not visible in Survey Editor
=> Fix saved changes are not visible in Survey Editor

apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/QuestionFilterComboBox.tsx, apps/web/components/preview/MultipleChoiceMultiQuestion.tsx, apps/web/lib/surveys/surveys.ts, packages/js/src/components/MultipleChoiceMultiQuestion.tsx, packages/lib/utils/array.ts
Remove lodash dependency from formbricks-js
=> Remove lodash dependency from formbricks-js

apps/web/app/(app)/environments/[environmentId]/settings/profile/EditAvatar.tsx, apps/web/app/(app)/environments/[environmentId]/settings/profile/EditName.tsx, apps/web/components/shared/EmptySpaceFiller.tsx, apps/web/components/shared/GoBackButton.tsx, packages/js/src/components/MultipleChoiceSingleQuestion.tsx, packages/ui/index.tsx
=> Apply prettier formatting

.changeset/real-singers-allow.md, apps/web/package.json, pnpm-lock.yaml
Prepare release of Formbricks v1.0.2
=> Prepare release of Formbricks v1.0.2

.changeset/thin-phones-act.md, packages/js/src/index.ts, packages/js/src/lib/commandQueue.ts, packages/js/src/lib/person.ts, pnpm-lock.yaml
Convert all attributes and userIds to string in formbricks-js
=> Convert all attributes and userIds to string in formbricks-js

apps/demo/pages/app/index.tsx, apps/web/components/shared/SurveyStatusIndicator.tsx, packages/js/src/components/CTAQuestion.tsx
Fixes [1148](https://linear.app/formbricks/issue/FOR-1148/align-buttons-right) 
Fill out survey with CTA in JS widget
=> fix: left align issue

apps/demo/.env.example
Add explainer note to demo app env example
=> Add explainer note to demo app env example

apps/formbricks-com/components/shared/Fence.jsx, apps/web/app/(app)/environments/[environmentId]/(actionsAndAttributes)/attributes/AttributeRowData.tsx, apps/web/app/(app)/environments/[environmentId]/(actionsAndAttributes)/attributes/AttributeTableHeading.tsx, apps/web/app/(app)/environments/[environmentId]/EnvironmentsNavbar.tsx, apps/web/app/(app)/environments/[environmentId]/integrations/page.tsx, apps/web/app/(app)/environments/[environmentId]/people/page.tsx, apps/web/app/(app)/environments/[environmentId]/surveys/PreviewSurvey.tsx, apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/summary/CTASummary.tsx, apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/summary/NPSSummary.tsx, apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/summary/OpenTextSummary.tsx, apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/summary/RatingSummary.tsx, apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/HowToSendCard.tsx, apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/QuestionsSettingsTabs.tsx, apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/RecontactOptionsCard.tsx, apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/ResponseOptionsCard.tsx, apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/WhenToSendCard.tsx, apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/WhoToSendCard.tsx, apps/web/app/s/[surveyId]/page.tsx, packages/js/src/components/CTAQuestion.tsx
Fix build errors in formbricks-com
=> Fix build errors in formbricks-com

apps/web/app/(app)/environments/[environmentId]/settings/setup/SetupInstructions.tsx
Add Formbricks version number to Setup Checklist
=> Add Formbricks version number to Setup Checklist

apps/web/app/api/v1/client/responses/route.ts, apps/web/pages/api/v1/client/environments/[environmentId]/sessions/index.ts, apps/web/pages/api/v1/environments/[environmentId]/surveys/[surveyId]/responses/[submissionId]/responsesNotes/index.ts, apps/web/pages/api/v1/environments/[environmentId]/surveys/[surveyId]/responses/[submissionId]/tags/index.ts, apps/web/pages/api/v1/environments/[environmentId]/tags/index.ts, packages/lib/services/response.ts
Move Telemetry events to services and limit events to surveyCreated and responseCreated
=> Move Telemetry events to services

packages/lib/constants.ts
Fix old survey data shown in survey overview
=> Fix old survey data shown in survey overview

apps/web/app/(app)/environments/[environmentId]/people/[personId]/DeletePersonButton.tsx, apps/web/app/(app)/environments/[environmentId]/people/[personId]/HeadingSection.tsx, apps/web/app/(app)/environments/[environmentId]/people/[personId]/page.tsx, packages/database/schema.prisma, packages/lib/services/person.ts
Increase loading speed of person detail page
=> Improve loading time of person detail page

apps/formbricks-com/pages/api/oss-friends/index.ts
Add Ghostfolio to the OSS Friends page.
Also see https://ghostfol.io/en/about/oss-friends
- Check `<localhost>/oss-friends`
=> Add Ghostfolio

apps/formbricks-com/pages/api/oss-friends/index.ts
=> Remove zero width characters

apps/web/app/s/[surveyId]/page.tsx
Fix Link Survey also showing for In-Product Surveys
=> Fix Link Survey also showing for In-Product Surveys

apps/formbricks-com/pages/api/oss-friends/index.ts
Added spark framework OS project.
=> Add Spark Framework to OSS Friends array.

apps/formbricks-com/components/shared/Header.tsx, apps/formbricks-com/components/shared/LayoutMdx.tsx, apps/formbricks-com/components/shared/SlideInBanner.tsx, apps/formbricks-com/pages/careers.tsx, apps/formbricks-com/pages/learn/[slug].tsx
- Rerelease careers page
- UI tweaks in MDX articles
=> Careers page + UI Tweaks in SEO Content

apps/formbricks-com/pages/api/oss-friends/index.ts
Harmonizes the `href` in the OSS Friends API
=> Harmonize href in OSS Friends

apps/formbricks-com/app/docs/api/api-key-setup/page.mdx, apps/formbricks-com/app/docs/best-practices/cancel-subscription/page.mdx, apps/formbricks-com/app/docs/best-practices/docs-feedback/page.mdx, apps/formbricks-com/app/docs/best-practices/feature-chaser/page.mdx, apps/formbricks-com/app/docs/best-practices/feedback-box/page.mdx, apps/formbricks-com/app/docs/best-practices/improve-trial-cr/page.mdx, apps/formbricks-com/app/docs/best-practices/interview-prompt/page.mdx, apps/formbricks-com/app/docs/best-practices/pmf-survey/page.mdx, apps/formbricks-com/app/docs/getting-started/framework-guides/page.mdx, apps/formbricks-com/app/docs/integrations/zapier/page.mdx, apps/formbricks-com/app/docs/link-surveys/data-prefilling/page.mdx, apps/formbricks-com/components/docs/Libraries.tsx
- Links each framework guide to it's relevant example repo's folder
- Fixes bug where heading was visible in white even in light mode
- Small bug where an image was not respecting the max width when placed side by side with another image is also fixed
=> Integrate Docs with Example Repo and Minor Bug Fixes

README.md
=> Replace Logo in readme

apps/formbricks-com/pages/api/oss-friends/index.ts
https://github.com/rivet-gg/rivet
Thank you for organizing this!
=> Add Rivet to OSS Friends 

apps/formbricks-com/pages/careers.tsx
=> update job description 

apps/formbricks-com/pages/careers.tsx
=> Update Career wording

apps/formbricks-com/pages/blog/best-open-source-survey-software-2023/index.mdx, apps/formbricks-com/pages/blog/experience-management-open-source/index.mdx, apps/formbricks-com/pages/blog/github-accelerator-experience/index.mdx, apps/formbricks-com/pages/blog/inaugural-batch-github-accelerator/index.mdx, apps/formbricks-com/pages/blog/open-source-forms-will-save-the-world/index.mdx, apps/formbricks-com/pages/blog/open-source-qualtrics-beats-typeform/index.mdx, apps/formbricks-com/pages/blog/snoopforms-becomes-formbricks/index.mdx, apps/formbricks-com/pages/blog/why-open-source-no-code-is-the-future-of-enterprise-gov-software/index.mdx
Fixes #763 
before Changes:
The images are causing issue on the mobile mode.
After changes:
Added width  of 100% on all image component on blog page
- Test A
- Test B
=> fixed image width on blog page

package.json
Increase turborepo concurrency level
=> Fix: Increase turborepo concurrency level

packages/n8n-node/package.json, pnpm-lock.yaml
fix: Update n8n-node dependencies and fix build errors
- Test A
- Test B
=> fix: Update n8n-node dependencies

package.json, packages/n8n-node/package.json, pnpm-lock.yaml
eslint in pre-commit hook failed
=> fix: eslint in pre-commit hook failed

apps/formbricks-com/app/docs/api/display/page.mdx, apps/formbricks-com/app/docs/api/people/page.mdx, apps/formbricks-com/components/docs/Navigation.tsx
There were a few client-side exposed APIs that we did not document yet. This PR documents all of those!
=> fix: document missing APIs

packages/js/src/components/MultipleChoiceMultiQuestion.tsx
NPE check.
While displaying survey as web widget one could not answer 'multiple option question'. He had to go 'back' and than hit 'next' twice. Since js code tried to calculate distance between new response and previous one, when previous one was missing it wasn't going through.
Init survey on your page with:
if (typeof window !== "undefined") {
formbricks
.init({
environmentId: environmentId,
apiHost: FORMBRICK_APIHOST,
debug: FORMBRICK_DEBUG,
})
Try answearing 'multiple option question'
- [] Added a screen recording or screenshots to this PR
- [] Updated the Formbricks Docs if changes were necessary
=> fix: Null pointer expection for multiple choice question on web form

apps/web/app/api/auth/[...nextauth]/authOptions.ts
We currently provide specific error messages on failed auth! This leads to attackers trying to brute force emails and find out if a user exists or not (ie if we throw that password is invalid instead of a user not found error).
This PR generalised the error messages for all the failed cases to avoid such detection! At a later stage, we also have to look into rate-limiting or preventing robots spamming the app!
=> fix: (security) Prevent User Account Enumeration

apps/web/app/(app)/environments/[environmentId]/settings/setup/actions.ts, apps/web/components/shared/WidgetStatusIndicator.tsx, packages/lib/services/environment.ts, packages/types/v1/actions.ts
format code based on prettier rules
=> chore: format code based on prettier rules

.changeset/afraid-dingos-sing.md, .github/workflows/nextjs-bundle-analysis.yml, package.json, packages/lib/responseQueue.ts
fixed an issue in responseQueue that could lead to a response sent twice
=> fix: issue in responseQueue that could lead to a response sent twice

.github/workflows/lint.yml, apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/responses/TagsCombobox.tsx, apps/web/app/api/cron/weekly_summary/email.ts, apps/web/pages/api/v1/client/environments/[environmentId]/responses/[responseId]/index.ts, apps/web/pages/api/v1/client/environments/[environmentId]/responses/index.ts, packages/lib/services/person.ts
format code and fix lint workflow
=> chore: format code and fix lint workflow

apps/web/components/auth/SignupForm.tsx
Fixes 1327 (linear) (issue)
https://github.com/formbricks/formbricks/assets/54475686/f4abd890-a09a-4dd9-83e2-4ef5c3aab06d
- Go to `/auth/signup`
- Sign up with Github
=> fix: fixes github sign up invite token

packages/lib/time.ts
[BUG_FIX]: Validation error causes auto close of survey to not work
Fixes #764 
- Create a survey with with X response limit to close the survey, including a free text question.
- On the Xth response, input a numerical string (e.g. 1234) as the answer of the free text question and submit.
- Complete the rest of the survey as usual.
- Check the survey summary page, the status should get automagically updated to `completed`.
- Test A
- Test B
=> fix: Validation error causes auto close of survey to not work

apps/web/app/api/v1/js/sync/route.ts
Temporarily fix sync overload issue
=> Temporarily fix sync overload issue

apps/web/app/api/v1/js/sync/route.ts
=> temporarily deactivate sync endpoint

packages/database/package.json, packages/database/src/client.ts, pnpm-lock.yaml
Swap prisma dataproxy for the new Prisma accelerate to be able to better control caching and connection pooling.
=> feat: add prisma accelerate support

apps/web/app/api/v1/js/sync/route.ts, packages/database/src/client.ts
=> feat: fix prisma accelerate types

apps/web/app/(auth)/invite/InviteContentComponents.tsx, apps/web/app/api/auth/[...nextauth]/authOptions.ts, packages/lib/jwt.ts, packages/lib/package.json, pnpm-lock.yaml
Fixes build issues in `packages/lib/jwt.ts`
Adds `@types/jsonwebtoken` as a dev dependency
Fixes [1339](https://linear.app/formbricks/issue/FOR-1339/make-jwt-typesafe)
Check jwt.ts
=> refactor: Made JWT typesafe

apps/web/app/api/v1/js/sync/route.ts
Fix a formatting issue and build error
=> fix: formatting issue and build error

packages/lib/services/attributeClass.ts
cache fix: invalidate attributeClasses cache on create
=> fix: invalidate attributeClasses cache on create

apps/web/app/api/v1/js/sync/lib/sync.ts, apps/web/app/api/v1/js/sync/route.ts, packages/lib/constants.ts, packages/lib/services/person.ts
add mau limit to web-app survey to prevent excessive usage on the endpoints.
=> feat: add mau limit to web-app survey

apps/formbricks-com/pages/api/oss-friends/index.ts
We are adding OpenStatus to the friends list 🔥
- Test A
- Test B
=> chore: add openstatus to friends

apps/formbricks-com/components/shared/Header.tsx
=> Chore: Remove Careers Page

apps/formbricks-com/pages/api/oss-friends/index.ts
- Adds Requestly to /oss-friends
- Requestly Github - https://github.com/requestly/requestly
- OSS Friends Page - https://requestly.io/oss-friends
Thank you so much for organizing this!
=> chore: Add Requestly to OSS Friends

apps/web/.gitignore, apps/web/token.json
=> fix: remove credentials file

apps/web/lib/email-template.ts
Fixes email indentation
Test emails
=> fix: email indentation

apps/web/lib/email.ts
Check mail with survey response
=> fix: preserve white spaces for responses in email

packages/lib/services/googleSheet.ts
Fixes Google sheet integration issue
- Test A
- Test B
=> fix: typo in env variables for GS integration

apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/responses/ResponseTimeline.tsx, packages/surveys/src/components/NPSQuestion.tsx
Fixes issue of NPS response not being stored
take survey with NPS question
=> fix: NPS response issue

apps/web/app/(app)/environments/[environmentId]/integrations/page.tsx
If user has already configured Google sheet integration button text changes to "ManageSheets"
Configure your GS integration and check GS integration card button
=> enhancement: Adds manage sheets label to GS integration card

apps/formbricks-com/pages/api/oss-friends/index.ts
Adds **Papermark** to the list of **oss-friends**. 
Can be checked on the page of OSS Friends.
=> chore: Adds Papermark

apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/SurveyEditor.tsx, apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/WhenToSendCard.tsx, packages/surveys/src/components/Survey.tsx
Fixes https://tella.video/johanness-video-boe2
Also removes a console.log form WhenToSendCard
Keep only one question in survey editor and then change preview type (linksurvey or in app)
You will notice that preview goes blank
=> fix: Fixes question preview bug

README.md
Adds One click railway setup button
Click on railway button
=> docs: Update Readme with Railway button

README.md
This links to our docs on formbricks.com for local setup and adds a gitpod setup banner. The motivation behind this PR was to make little improvements to formbricks docs daily from my findings comparing 5 different OS projects. It was suggested to me by @mattinannt and this is the first quick win in improving our contributors onboarding experience.
1. All ports are up and running.
2. I was able to successfully create and account and log in.
3. A new survey created on my Gitpod environment.
- Click the Gitpod logo in the README.
- Wait for Gitpod to completely build the whole project
- Allow popup in your browser in order for the web application to open in a new tab once build is compelte
- If you are creating a new account on the web app, open the link on port `8025` to …
=> docs: add local and gitpod setup to README.md

apps/web/app/api/v1/js/people/[personId]/set-attribute/route.ts, packages/lib/services/person.ts
=> fix: moves prisma logic from set-attribute to person service

.gitpod.yml, README.md
This PR allows mailhog to automatically open after gitpod sets up.
https://github.com/formbricks/formbricks/assets/31730715/023bc5f4-1b87-4127-bfb0-6882918c9386
- Visit https://github.com/rotimi-best/formbricks/tree/gitpod-mailhog
- Wait for everything to setup
- Enable Popup in your browser
- Expect that Mailhog (port 8025) and the web app (port 3000) opens in a new tab
=> feat: Open mailhog in browser on setup complete

apps/web/app/(app)/layout.tsx, apps/web/app/(auth)/layout.tsx, packages/ui/components/NoMobileOverlay.tsx, packages/ui/index.tsx
Fixes [1341](https://linear.app/formbricks/issue/FOR-1341/block-mobile-usage-of-admin-interface)
Try to open app.formbricks on smaller devices
=> refactor: Blocks mobile usage

apps/formbricks-com/pages/formtribe/index.tsx
This PR Fixes a typo in the title of the [FormTribe](https://formbricks.com/formtribe) page.
~FormbTribe~ FormTribe
Fixed this Typo in Line 222 of `apps/formbricks-com/pages/formtribe/index.tsx`
- No Test Required as such
=> fix: Fixed Typo in Line 222 of FormTribe Page

README.md
From my investigation of other Open source projects, one thing we didn't have was a Prerequisites section in our README.md. This PR fixes this.
- Open README.md
- Look for Prerequisites section
- You should see this
=> docs: add prerequisities to readme.md

packages/types/v1/surveys.ts
fix validation error in surveyClosedMessage
=> fix: validation error in surveyClosedMessage

apps/formbricks-com/app/docs/integrations/google-sheets/page.mdx
=> tweaking docs page

packages/js/src/lib/eventListeners.ts, packages/js/src/lib/init.ts, packages/surveys/src/components/Modal.tsx
fix formbricks-js not displaying properly on smaller screens
=> fix: formbricks-js not displaying properly on smaller screens

apps/formbricks-com/components/shared/Header.tsx, apps/formbricks-com/components/shared/OpenSourceInfo.tsx, apps/formbricks-com/components/shared/PricingCalculator.tsx, apps/formbricks-com/components/shared/PricingGetStarted.tsx, apps/formbricks-com/components/shared/PricingTable.tsx, apps/formbricks-com/components/shared/Slider.tsx, apps/formbricks-com/components/shared/icons/XCircleIcon.jsx, apps/formbricks-com/package.json, apps/formbricks-com/pages/index.tsx, apps/formbricks-com/pages/pricing.tsx, packages/ui/components/icons/CrossMarkIcon.tsx, pnpm-lock.yaml
Adds a pricing page
ToDo:
https://www.loom.com/share/a6484c115d1e4efb8a001b6bcc14a98d?sid=d076b9a6-ed11-439c-aa2e-e8b78505506d
=> feat: pricing page

apps/web/pages/api/v1/environments/find-first.ts
enviroment -> environment
- Test A
- Test B
=> Fix typo in find-first.ts

apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/ResponseFilter.tsx, apps/web/env.mjs, packages/lib/constants.ts
invalid validation of VERCEL_URL leads to build errors on Vercel
=> fix: invalid validation of VERCEL_URL leads to build errors on Vercel

apps/web/vercel.json
add vercel.json file to configure Vercel deployments
=> feat: add vercel.json file to configure Vercel deployments

.github/ISSUE_TEMPLATE/feature_request.yml, apps/formbricks-com/pages/formtribe/index.tsx
=> Release Side Quests

apps/web/app/(app)/environments/[environmentId]/surveys/PreviewSurvey.tsx
Fixes
1. Progress bar moving forward when user switch between templates in templates selector page
2. Restart button not resetting progress ,when only first question is filled
https://github.com/formbricks/formbricks/assets/67850763/6ca00186-bed0-44f8-859a-0a555f8ef9ba
https://github.com/formbricks/formbricks/assets/67850763/777df6be-0a66-449e-9fa6-28eb99fd3715
Click on create a new survey on surveys page
Try clicking on different templates
When in survey editor
Answer first question in question preview
Click on reset
=> fix: Progress bar reset

apps/formbricks-com/app/docs/contributing/introduction/page.mdx
Adds the CLA requirement into the Contribution guide.
- Launch `formbricks-com`
- Go to docs
- Go to Contribution guide
- In the introduction section you should see the CLA section at the far bottom.
=> docs: add cla form to getting started doc

apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/WhenToSendCard.tsx
Fixes #896 
https://www.loom.com/share/c94e0a7bb2ab4025a2a97e50cd3b84b0?sid=e54f4d6d-fd0c-4d55-a0c5-1d620e0a8d0a
=> fix: add action on survey edit

apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/summary/components/CTASummary.tsx, apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/summary/components/ConsentSummary.tsx, apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/summary/components/Headline.tsx, apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/summary/components/MultipleChoiceSummary.tsx, apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/summary/components/NPSSummary.tsx, apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/summary/components/OpenTextSummary.tsx, apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/summary/components/RatingSummary.tsx, apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/SurveyMenuBar.tsx, packages/surveys/src/components/CTAQuestion.tsx, packages/surveys/src/components/ConsentQuestion.tsx, packages/surveys/src/components/Headline.tsx, packages/surveys/src/components/MultipleChoiceMultiQuestion.tsx, packages/surveys/src/components/MultipleChoiceSingleQuestion.tsx, packages/surveys/src/components/NPSQuestion.tsx, packages/surveys/src/components/OpenTextQuestion.tsx, packages/surveys/src/components/RatingQuestion.tsx, packages/surveys/src/components/ThankYouCard.tsx
mandatory question indicator added
Fixes #885 
- Test A
- Test B
=> feat: Mandatory question indicator added

packages/surveys/src/components/MultipleChoiceMultiQuestion.tsx, packages/surveys/src/lib/logicEvaluator.ts, pnpm-lock.yaml
fix: multi select evaluator and required
Fixes #901 
- Test A
- Test B
=> fix: multi select evaluator and required

apps/formbricks-com/pages/formtribe/index.tsx
=> update how to section

apps/web/app/s/[surveyId]/LinkSurvey.tsx
fixed displays not sent correctly in link surveys
=> fix: display not sent correctly in link surveys

.github/PULL_REQUEST_TEMPLATE.md
This PR updates the following info in the "PR template". It adds the following:
1. Adds optional text to uploading video and image to PR
2. Replace contribution guide with How we code
3. Regroup the checklists into required and not required so when reviewing it is clear what points were left out which are compulsory
- Review the `PULL_REQUEST_TEMPLATE.md`
=> docs: improve pull request template with latest info

packages/lib/actionClass/auth.ts, packages/lib/apiKey/auth.ts, packages/lib/apiKey/service.ts, packages/lib/response/auth.ts, packages/lib/response/service.ts, packages/lib/services/attributeClass.ts, packages/lib/services/displays.ts, packages/lib/services/environment.ts, packages/lib/services/googleSheet.ts, packages/lib/services/invite.ts, packages/lib/services/membership.ts, packages/lib/services/product.ts, packages/lib/services/profile.ts, packages/lib/services/survey.ts, packages/lib/services/tagOnResponse.ts, packages/lib/services/team.ts, packages/lib/services/teamDetails.ts, packages/lib/tag/auth.ts, packages/lib/tag/service.ts, packages/lib/tagOnResponse/auth.ts
Add `import server-only` to every service
- General walk through test
Not sure how I should go about testing here.
=> feat: consistent use of server-only

apps/web/app/(app)/environments/[environmentId]/settings/members/EditMemberships/EditMemberships.tsx, packages/lib/services/invite.ts
Rename function with typo
- Ran pnpm build to make sure everything build successfully
=> fix: rename function name typo

packages/lib/services/profile.ts
Removes unused function in a service that is error prone
- Check within the application if this function is called
=> fix: remove error prone unused function

packages/lib/services/team.ts
This PR is a service improvement to remove the usage of prisma types directly in a service 
- Go to specific function
- Check if there are linting errors based off this change
=> fix: remove direct usage of prisma type in services

apps/web/app/(app)/onboarding/components/Objective.tsx, packages/lib/services/profile.ts, packages/types/v1/profile.ts
fix bug that validation error in profile update input
=> fix: validation error in profile update input

.env.example
Fixes this issue when you run `pnpm build`
- Clone repo
- Follow dev set up guide
- run `pnpm build`
- You should get a success message after build
=> fix: move close comment to end in .env.example

apps/web/next.config.mjs, turbo.json
add ASSET_PREFIX_URL to add support for proxies
By setting the environment variable ASSET_PREFIX_URL we are setting the [next config assetPrefix](https://nextjs.org/docs/pages/api-reference/next-config-js/assetPrefix) parameter to ship javascript and css files from a complete URL instead of the current domain.
- Test A
- Test B
=> feat: add ASSET_PREFIX_URL to add support for proxies

.github/workflows/release-docker.yml
fixing docker release deployment pipeline
=> fix: docker release deployment pipeline

packages/lib/survey/service.ts
improve error logging in survey service
=> chore: improve error logging in survey service

apps/formbricks-com/pages/api/oss-friends/index.ts
Add Hook0 to the OSS Friends page.
Also see https://www.hook0.com/oss-friends
his change. -->
- Check `<localhost>/oss-friends`
=> chore: Add Hook0 to OSS Friends

apps/formbricks-com/pages/formtribe/index.tsx
=> lp: update leaderboard

apps/web/app/s/[surveyId]/not-found.tsx
Fixes a sentence (single word).
- Test A
- Test B
=> chore: Fix sentence

apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/QuestionCard.tsx, apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/Validation.ts
- Fixes the incorrect passing of input values
- Removes the validation check for now as it avoid users entering spaces
Closes #965
=> fix: backButton and button target mixup

README.md
Updated contributors section in readme.md
- [✅] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [✅] Self-reviewed my own code
- [✅] Checked for warnings, there are none
- [✅] Merged the latest changes from the main onto my branch with `git pull origin main`
- [✅] My changes don't cause any responsiveness issues
=> Fixed #974 Updated README.md

apps/web/app/(app)/environments/[environmentId]/people/[personId]/(responseSection)/ResponsesFeed.tsx, apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/SummaryHeader.tsx, apps/web/components/shared/SurveyStatusDropdown.tsx
fix build errors in current version
=> fix: build errors

apps/formbricks-com/components/shared/Header.tsx
Fixes #997 
Makes the navigation bar responsive
Before :
After :
Try changing screen size by inspecting the page
=> fix#997 making navigation bar responsive

packages/surveys/src/components/MultipleChoiceMultiQuestion.tsx
Fixes #1008 
- Create New Survey with MultiSelect Required True and select any option and submit.
- [] Checked for warnings, there are none
=> fix: Required Condition Update for MultiSelectQuestion.

apps/formbricks-com/pages/formtribe/index.tsx
lp: update leader board 081023
=> lp: update leader board 081023

apps/web/app/api/v1/client/displays/[displayId]/route.ts
add cors to display update endpoint
=> fix: add cors to display update endpoint

.github/workflows/pr.yml
=> fix: make pr.yml mandatory on all PRs

apps/web/app/(app)/environments/[environmentId]/settings/notifications/EditAlerts.tsx, apps/web/app/(app)/environments/[environmentId]/settings/notifications/EditWeeklySummary.tsx, apps/web/app/(app)/environments/[environmentId]/settings/notifications/NotificationSwitch.tsx, apps/web/app/(app)/environments/[environmentId]/settings/notifications/actions.ts
Authorizes the user on the server side and does not take a userId as an input from client anymore
=> feat: authorization in notificationUpdateAction

.github/workflows/build.yml, .github/workflows/lint.yml, .github/workflows/pr.yml, .github/workflows/test.yml
=> chore: update github build action

apps/web/app/(app)/environments/[environmentId]/settings/lookandfeel/actions.ts
We authorize if the user has access to the product before updating its value.
=> feat: authorization in product update in look and feel page

apps/web/app/(app)/environments/[environmentId]/(actionsAndAttributes)/attributes/actions.ts, packages/lib/attributeClass/auth.ts
Adds an auth method to check if a user can access an attributeClass or not and uses that in the attributeAcitivityTab
Try passing a random attributeClassId now and you should not be able to get its data from the server
=> feat: authorization in attributeClassAction

.github/workflows/build.yml, .github/workflows/lint.yml, .github/workflows/release-docker.yml
add ENCRYPTION_KEY generation to github actions
=> chore: add ENCRYPTION_KEY to github actions

packages/lib/attributeClass/service.ts
fix issue where getAttributeClassByName cache returns wrong entries
=> fix: getAttributeClassByName cache returns wrong entries

apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/responses/components/ResponseTimeline.tsx, apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/summary/components/SummaryList.tsx
responses not visible when sdk not connected
=> fix: responses not visible when sdk not connected

README.md
add FULL_STOP to Readme File
- Test A
- Test B
=> add FULL_STOP to Readme File

.gitpod.yml
Fixes  #1079
- Open formbricks with gitpod
- [  ] Commented on my code in hard-to-understand bits
=> fix: added script to setup encryption key in gitpod script

apps/web/app/api/v1/client/displays/route.ts, packages/surveys/src/components/MultipleChoiceMultiQuestion.tsx
Also removed a consle log from display route
Fixes #1085 
- Test A
- Test B
=> fix: multiChoice undefined value check

packages/surveys/src/components/Modal.tsx, packages/surveys/src/components/Survey.tsx
fixes #1067 
Fixed by Reducing the top padding and reduced the size of X button. It does not change the size of widget.
- Test A
- Test B
=> fix: X and optional text overlap

packages/surveys/src/styles/global.css
Fixes #1050 
You can use demo app for testing this
Give styling to scroll bar in demo app
Take an in-app survey
=> fix: scrollbar issue

README.md
I have done a very simple change by adding the node js official website link at the end.
The link for Docker and Pnpm was already given in the prerequisite so for the setup i have given the direct node js link and it is necessary because node js is the backbone of the project.
- [✔️] This change requires a documentation update
- Test A
- Test B
- [ ✔️] My changes don't cause any responsiveness issues
- [ ✔️] Updated the Formbricks Docs if changes were necessary
=> chore: add nodejs URL in readme

apps/formbricks-com/app/docs/actions/code/page.mdx, apps/formbricks-com/app/docs/attributes/custom-attributes/page.mdx, apps/formbricks-com/app/docs/attributes/identify-users/page.mdx, apps/formbricks-com/app/docs/best-practices/docs-feedback/page.mdx, apps/formbricks-com/app/docs/best-practices/pmf-survey/page.mdx, apps/formbricks-com/app/docs/contributing/demo/page.mdx, apps/formbricks-com/app/docs/contributing/setup/page.mdx, apps/formbricks-com/app/docs/contributing/troubleshooting/page.mdx, apps/formbricks-com/app/docs/getting-started/framework-guides/page.mdx, apps/formbricks-com/app/docs/introduction/what-is-formbricks/page.mdx, apps/formbricks-com/app/docs/link-surveys/data-prefilling/page.mdx, apps/formbricks-com/app/docs/link-surveys/user-identification/page.mdx, apps/formbricks-com/app/docs/self-hosting/docker/page.mdx, apps/formbricks-com/app/docs/self-hosting/from-source/page.mdx, apps/formbricks-com/app/docs/self-hosting/migrating-to-1.1/page.mdx, apps/formbricks-com/app/docs/self-hosting/production/page.mdx
Buttons Margin and code snippets issue across Docs FIXED
Fixes https://github.com/formbricks/formbricks/issues/1016
- Test A
- Test B
=> fix: Buttons Margin and code snippets issue across Docs

apps/formbricks-com/pages/formtribe/index.tsx
lp: update leaderboard Friday 13th
=> lp: update leaderboard Friday 13th

.changeset/odd-rocks-pay.md, apps/formbricks-com/app/docs/getting-started/framework-guides/page.mdx, apps/formbricks-com/components/home/SetupTabs.tsx, apps/web/app/(app)/environments/[environmentId]/settings/setup/SetupInstructions.tsx, packages/api/.eslintrc.cjs, packages/js/index.html, packages/js/package.json, packages/js/vite.config.js
Prepare release of formbricks-js 1.1.0
=> chore: Prepare release of formbricks-js 1.1.0

.changeset/odd-rocks-pay.md, packages/js/CHANGELOG.md, packages/js/package.json
=> chore: Version Packages

apps/formbricks-com/app/docs/getting-started/framework-guides/page.mdx, apps/formbricks-com/components/home/SetupTabs.tsx, apps/web/app/(app)/environments/[environmentId]/settings/setup/SetupInstructions.tsx, packages/js/index.html, packages/js/package.json
fix formbricks-js not starting properly in a browser due to the .cjs extension or some incompatibilities with the cdn. Going back to non-module solves the issue.
=> fix: formbricks-js not starting in a browser

apps/storybook/package.json, packages/api/package.json, packages/js/package.json, packages/lib/package.json, packages/prettier-config/package.json, packages/surveys/package.json, packages/surveys/vite.config.ts, packages/tsconfig/package.json, packages/ui/package.json, pnpm-lock.yaml
fixing conflicting typescript and dts from surveys package producing error
=> fix: conflicting typescript and dts from surveys package producing error

apps/formbricks-com/components/home/ScrollToTop.tsx, apps/formbricks-com/pages/index.tsx
Added a scroll to top button
Fixes #1122 (https://github.com/formbricks/formbricks/issues/1122)
https://github.com/formbricks/formbricks/assets/43564765/7b908e21-a66e-472b-bb82-3323312c2046
```sh
pnpm install
cd apps/formbricks-com
pnpm dev
```
=> fix: added scroll to top button

packages/lib/survey/service.ts
chore: improve logging in survey service
=> chore: improve logging in survey service

apps/formbricks-com/components/shared/Header.tsx
#pricing   ->   /pricing
On mobile screens , in the Hamburger menu the pricing does not navigates anywhere .I basically fixes that and now it works fine
Fixes # (1157)
- Test A
- Test B
- [ x] Filled out the "How to test" section in this PR
- [ x] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [ x] Self-reviewed my own code
- [ x] Commented on my code in hard-to-understand bits
- [x ] Ran `pnpm build`
- [ x] Checked for warnings, there are none
- [ x] Removed all `console.logs`
- [ x] Merged the latest changes from main onto my branch with `git pull origin main`
- [ x] My changes don't cause any responsiveness issues
=> fix: Pricing Link in mobile menu on LP , Update Header.tsx

apps/formbricks-com/pages/feedback-box/index.tsx
Fixed a grammatical mistake mentioned in issue #1159 where there was a spelling mistake 
Fixes #1159
notice  the line : "feel heared and"
should look like :
- Test A
- Test B
- [ x ] If a UI change was made: Added a screen recording or screenshots to this PR
=> style: Fixed a minor grammatical mistake.

apps/web/app/lib/email.ts
Fixes email being inserted into email notification
=> fix: replace ' with backticks

packages/js/vite.config.js, packages/lib/survey/service.ts, packages/surveys/package.json, packages/surveys/postcss.config.js, packages/surveys/vite.config.ts, turbo.json
fixing formbricks-surveys not compiling correctly leads to formbricks-js throwing error in action creation
additionally remove database object validation in surveys service to be more consistent with other services.
=> fix: formbricks-surveys not compiling correctly leads to formbricks-js throwing error in action creation

apps/formbricks-com/next.config.mjs, apps/formbricks-com/pages/oss-friends.tsx
=> lp: Update oss friends page

apps/formbricks-com/app/docs/contributing/how-we-code/page.mdx
Adds doc for code quality and styling section
- Go to formbricks web
- Go to How we code at Formbricks
- Go to the section of pull request
=> docs: code quality & styling section

apps/storybook/package.json, apps/web/app/api/cron/weekly_summary/types.ts, apps/web/pages/api/v1/client/environments/[environmentId]/events/index.ts, packages/lib/action/service.ts, packages/lib/profile/service.ts, packages/types/v1/actionClasses.ts, packages/types/v1/surveys.ts
fixing: remove prisma types import in runtime
=> fix: remove prisma types import in runtime

README.md
This PR adds hyperlink to LICENSE word reference in LICENSE  section at README.md
Check HERE:
https://github.com/malivinayak/formbricks#%EF%B8%8F-license
=> chore: add hyperlink to LICENSE reference

apps/formbricks-com/pages/formtribe/index.tsx
Update Formtribe Leaderboard as per the latest scorecard and points provided as per Discord
=> feat: update latest leaderboard points

apps/formbricks-com/components/home/Highlights.tsx
Fixes #1231 
- Test A
- Test B
=> fix: Typo on main page is fixed

apps/formbricks-com/components/docs/Header.tsx, apps/formbricks-com/components/shared/PricingTable.tsx, apps/formbricks-com/pages/feedback-box/index.tsx, apps/web/app/(app)/environments/[environmentId]/actions.ts, apps/web/app/(app)/environments/[environmentId]/settings/product/components/EditProductName.tsx, apps/web/app/(app)/environments/[environmentId]/settings/product/components/EditWaitingTime.tsx, apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/actions.ts, apps/web/app/api/cron/weekly_summary/email.ts, apps/web/app/api/v1/client/storage/route.ts, apps/web/pages/api/v1/client/environments/[environmentId]/responses/[responseId]/index.ts, apps/web/pages/api/v1/client/environments/[environmentId]/responses/index.ts, packages/js/src/lib/noCodeActions.ts, packages/lib/person/service.ts, packages/lib/survey/service.ts, packages/tailwind-config/tailwind.config.js, packages/ui/TagsCombobox/index.tsx
fix: survey trigger cannot be deleted
=> fix: survey trigger cannot be deleted

apps/formbricks-com/components/dummyUI/AddEventDummy.tsx, apps/formbricks-com/components/shared/BestPracticeNavigation.tsx, apps/formbricks-com/components/shared/UseCaseCTA.tsx, packages/ui/Select/index.tsx
Corrected the styles of the Add Dummy Event example component from Step 4 in landing page
Fixes #1219 
Light theme thick border is seen around the dropdown in Dark mode
Alignment of items is not correct
Corrected the border color of the dropdown in Dark mode
Corrected the alignment of items
- Test A
- Test B
=> fix: Corrected landing page styles

apps/web/app/error.tsx
chore: improve error component and display message to user
=> chore: improve error component and display message to user

apps/formbricks-com/pages/api/oss-friends/index.ts
Added Firecamp to the list of oss-friends. 
here is the url of oss-friends of Firecamp website - https://firecamp.io/oss-friends
thank you for creating oss-friends page!
=> feat: added Firecamp to oss-friends the list

apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/components/EditWelcomeCard.tsx
This PR Resolve the issue no. #1297 .
If this PR related to issue no. #1289 , assign the points.
I request you to kindly check issue no. #1297 First.
https://www.loom.com/share/9a8d88df062a4c01a409d05dfbe1942a?sid=521bb21c-ea4d-4307-96dc-120fc7b11ab2
=> fix: Survey : Welcome Card Button is buggy

apps/web/app/error.tsx, apps/web/pages/api/v1/environments/[environmentId]/tags/[tagId]/index.ts, packages/lib/action/service.ts, packages/lib/apiKey/service.ts, packages/lib/display/service.ts, packages/lib/environment/service.ts, packages/lib/googleSheet/service.ts, packages/lib/integration/service.ts, packages/lib/invite/service.ts, packages/lib/membership/service.ts, packages/lib/person/service.ts, packages/lib/product/service.ts, packages/lib/profile/service.ts, packages/lib/response/service.ts, packages/lib/responseNote/service.ts, packages/lib/session/service.ts, packages/lib/shortUrl/service.ts, packages/lib/survey/service.ts, packages/lib/team/service.ts, packages/lib/teamDetail/service.ts
chore: improve error logging in services
- Test A
- Test B
=> chore: improve error logging in services

apps/web/app/(app)/environments/[environmentId]/components/WidgetStatusIndicator.tsx, packages/lib/action/service.ts
fix: survey list loading error for products with a lot of actions
=> fix: survey list loading error for products with a lot of actions

README.md
[trendshift.io](https://trendshift.io/) captures the daily Github Trending data and generates a nice dynamic badge based on the highest achieved rank. This PR embeds the badge in the readme file, and hopefully, It helps to motivate contributors and attract users.
- [] This change requires a documentation update
No code change, just update the readme file to embed the GitHub Trending badge.
- [] Filled out the "How to test" section in this PR
=> chore: (docs) add GitHub trending badge in readme file

apps/formbricks-com/pages/formtribe/index.tsx
Updates Formtribe leaderboard as per the Discord side quests channel for the day
- Test A
- Test B
=> feat: update formtribe leaderboard as per today

apps/formbricks-com/app/docs/actions/code/page.mdx
This pull request fixes typo `specfic -> specific` in the documentation page.
=> docs: fix typo in apps/formbricks-com/app/docs/actions/code/page.mdx

apps/web/app/api/v1/js/actions/route.ts
fix: add hotfix for not storing 50% scroll and exit intent in db
=> fix: add hotfix for not storing 50% scroll and exit intent in db

apps/formbricks-com/components/shared/MetaInformation.tsx
=> fix: Logo is not visible in edge search #1265

apps/demo/.env.example, apps/web/app/(app)/environments/[environmentId]/components/UrlShortenerModal.tsx
This PR fix the copy button the copy button is working while its value is null  and shorten button should be disabled while it's value is null
Fixes #1327
Loom Video: https://www.loom.com/share/3600d3c4013d484182858eaf099f8dcb?sid=2f0b1e66-b443-4c0e-be68-73be98257eed
- [] Ran `pnpm build`
- [] If a UI change was made: Added a screen recording or screenshots to this PR
- [] Updated the Formbricks Docs if changes were necessary
=> fix: Copy button disabled while it's value is null

apps/demo/pages/app/index.tsx, apps/demo/pages/test-nocode-app/index.tsx
This PR fix the background does not load up on the entire page! 
Fixes #1308 
Loom Video: https://www.loom.com/share/58bd08da127048f1b16ea6fbb749c876?sid=7c6f5522-3a7f-4867-baf9-b61540cef654
=> fix: the background does not load up on the entire page! 

packages/js/src/lib/actions.ts
Prevents creation of actions from the `packages/js` in the formbricks DB!
=> fix: prevent exit intent and scroll intent in js package to make api call

.github/PULL_REQUEST_TEMPLATE.md, apps/formbricks-com/next.config.mjs
=> chore: add cla to PR template & /cla

apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/components/SurveyMenuBar.tsx
fix: survey with empty pin cannot be created
=> fix: survey with empty pin cannot be created

apps/formbricks-com/components/shared/MetaInformation.tsx
I've added the Twitter title, Twitter description, and keywords meta tags for better SEO. This fixes the issue #1333 
You can open the formbricks-com website, inspect and check the meta tags
=> fix: add twitter title, desc and keyword meta tags

.changeset/seven-seals-film.md
Bump @formbricks/js package with latest changes
=> feat: release patch release formbricks/js with changesets

.changeset/seven-seals-film.md, packages/js/CHANGELOG.md, packages/js/package.json
`@formbricks/js@1.1.3`
https://github.com/formbricks/formbricks/commit/d11728312e8c4438118e08cb9c037dac7ffef138: Multiple bugfixes and performance improvements
=> feat: Release @formbricks/js@1.1.3

packages/surveys/src/components/MultipleChoiceMultiQuestion.tsx
This PR fixes the survey break, on **Convert to Multi Select**, Clicked (while creating survey).
Fixes #1382
https://watch.screencastify.com/v/b2khRjWPSW7m8glm8Muo
- Navigate to Create Survey, Add Question, select question type Single-Select, select any option in preview, and click on Convert to Multi Select
- Navigate to Create Survey, Add Question, select question type Multi-Select, click on Convert to Single-Select, and choose any option in the preview and Click on Convert to Multi Select
=> fix: Page break on Convert to Multi Select

apps/web/app/not-found.tsx
This pull request fixes the issue related to the "Back to Home" button on the 404 Error page not redirecting users to the homepage.
Fixes #1380 
Loom video https://www.loom.com/share/1de478248da24d30833a18dbf13788af?sid=20b43c44-8c7c-4ec1-8ac7-7824880cb5e5
- Test A: Navigate to any page, intentionally input an incorrect URL, observe the appearance of the 404 Error page, and check that clicking the "Back to Home" button now successfully redirects to the homepage.
- Test B: Add any additional relevant tests.
- [] Ran `pnpm build`
- [] First PR at Formbricks? [Please sign the CLA!](https://formbricks.com/clmyhzfrymr4ko00hycsg1tvx) Without it, we won't be able to merge it 🙏
=> fix: Resolve issue with "Back to Home" button on 404 page

apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/summary/components/LinkModalButton.tsx
This PR fixes the modal not opening on the click of share button in the form response pages
Fixes #1386
1. Go to form response screen
2. Clicked on share button 
3. And modal is opening
=> fix: Share modal not opening

apps/formbricks-com/pages/formtribe/index.tsx
Update Formtribe Leaderboard as per today
=> feat: update leaderboard as per today

apps/web/app/(app)/environments/[environmentId]/surveys/templates/templates.ts
This PR fixes the issue no. #1401 
=> fix: In Review Prompt Lower and Upper labels are not showing in dummyUi/Preview

apps/formbricks-com/components/shared/ThemeSelector.jsx
Introduce a user interface enhancement that changes the theme switcher from a dropdown to a toggle switch.The previous implementation used a dropdown for selecting the theme, and this update improves the user experience.
Changes:
1. Replaced the theme selector dropdown with a toggle switch.
2. Modified the functionality to control the theme using the toggle switch.
3. The theme is now set as the system default by default, providing a seamless transition for users who prefer system-defined themes.
4. Ensured that the toggle switch correctly reflects the current theme state.
Fixes #1267
https://github.com/formbricks/formbricks/assets/85775976/ee5a14a3-50e0-46e9-b8dc-31bce8e6f514
- Test A
- Test B
=> fix: Refactor theme switcher from dropdown to toggle

packages/ui/FileInput/index.tsx
Fixes #1294 
I couldn't replicate the error in local development but I created an error in the [uploadFile](https://github.com/formbricks/formbricks/blob/main/packages/ui/FileInput/lib/fileUpload.ts) function just for testing.
https://github.com/formbricks/formbricks/assets/70102539/e650eb9d-7b2d-4574-8759-bdfb5dc7b419
- Go to https://app.formbricks.com/
- Navigate to to the surveys page
- Create new Survey
- Try to upload around `6.6 MB` image as company logo
- An appropriate error message is now displayed and the image is removed
=> fix: Display appropriate error message when uploading image

apps/web/app/api/v1/client/displays/[displayId]/route.ts, apps/web/app/api/v1/client/displays/route.ts, apps/web/app/api/v1/client/responses/[responseId]/route.ts, apps/web/app/api/v1/client/responses/route.ts, apps/web/app/api/v1/js/sync/route.ts, apps/web/app/i/[shortUrlId]/page.tsx, packages/lib/environment/service.ts, packages/lib/product/service.ts, packages/lib/survey/service.ts, packages/lib/team/service.ts
chore: improve error logging in client endpoints
=> chore: improve error logging in client endpoints

apps/web/app/api/v1/client/storage/local/route.ts
=> fix: fixes client storage api route method

.changeset/smooth-cows-exist.md, packages/js/CHANGELOG.md, packages/js/package.json
feat: formbricks-js 1.1.4 release
=> feat: formbricks-js 1.1.4 release

apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/summary/components/LinkSingleUseSurveyModal.tsx, packages/lib/crypto.ts
fix: survey url incorrect in single use share dialoge
=> fix: survey url incorrect in single use share dialoge

apps/formbricks-com/app/docs/contributing/setup/page.mdx, apps/formbricks-com/app/docs/self-hosting/docker/page.mdx, apps/formbricks-com/app/docs/self-hosting/migration-guide/page.mdx
Fixed build errors in formbricks-com
=> fix: build errors in formbricks-com

.github/workflows/release-docker.yml, pnpm-lock.yaml
fix: docker release github action
=> fix: docker release github action

apps/formbricks-com/components/shared/Header.tsx
Fixes #1463 
1. Visit [Formbricks](https://formbricks.com/)
1. Switch to dark mode 
1. Scroll down and watch that the Navbar is not clearly visible.
Before
After
=> fix: [BUG] In Dark Mode Navbar is not Properly Visible #1463

apps/formbricks-com/pages/formtribe/index.tsx
=> update side quests

packages/lib/responseNote/service.ts
chore: improve error logging in responseNote service
=> chore: improve error logging in responseNote service

packages/lib/response/service.ts
fix: summary loading infinitely
=> fix: summary loading infinitely

packages/api/src/api/client/response.ts
Fixes Source tracking
We recently merged source tracking PR but somehow, it broke
Even if you provide source into URL, it was not getting saved
=> fix: source tracking

apps/formbricks-com/pages/formtribe/index.tsx
Updates Formtribe Leaderboard as per Notion as of now
=> feat: formtribe leaderboard update as per today

apps/formbricks-com/package.json, pnpm-lock.yaml
=> chore: downgrade next version in formbricks-com

apps/web/app/(auth)/auth/login/components/SigninForm.tsx
Fixes [FOR-1461](https://linear.app/formbricks/issue/FOR-1461/error-message-on-login-not-shown)
Create a formbricks account without using any provider (for example test@gmail.com)
Now try to login using same email but this time using a provider(for example lets say google)
=> fix: Error message on Login not shown 

apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/components/ResponseOptionsCard.tsx
Fixes [FOR-1463](https://linear.app/formbricks/issue/FOR-1463/zod-validation-error-pin)
Create a new survey and enable pin validation, now try to save without changing the default pin(1234)
=> fix: zod pin validation failing

apps/web/app/(app)/environments/[environmentId]/components/UrlShortenerModal.tsx
#1501 Fixes the bug of not resetting the long URL field after closing the Modal.
https://www.loom.com/share/878810dfb8c14c04a3b820ba5b60b78e?sid=6fa377e2-33e1-40a5-9e31-5f90f47c3416
- Test A
- Test B
=> fix: long url not getting reset after closing modal

apps/formbricks-com/app/docs/api/management/webhooks/page.mdx, apps/formbricks-com/app/docs/best-practices/cancel-subscription/page.mdx, apps/formbricks-com/app/docs/best-practices/docs-feedback/page.mdx, apps/formbricks-com/app/docs/best-practices/feature-chaser/page.mdx, apps/formbricks-com/app/docs/best-practices/interview-prompt/page.mdx, apps/formbricks-com/app/docs/contributing/gitpod/page.mdx, apps/formbricks-com/app/docs/getting-started/framework-guides/page.mdx, apps/formbricks-com/app/docs/link-surveys/single-use-links/page.mdx
some of them are:
multipe => multiple
specfic => specific
simplte => simple
Worskpace => workspace
Paylod => Payload
- Test A
- Test B
=> fix: Spelling Errors

apps/formbricks-com/components/docs/Navigation.tsx
=> fix: Error in Docs navigation #1518

apps/web/app/(app)/environments/[environmentId]/settings/members/components/AddMemberModal.tsx
set default role to admin of new invited member. If user doesn't select any role!
Fixes #1523 
- Test A
- Test B
=> fix(bug): default role implemented

apps/web/app/api/v1/js/people/[personId]/set-attribute/route.ts, apps/web/app/api/v1/js/people/[personId]/set-user-id/route.ts, packages/ui/BillingSlider/index.tsx
=> fix: fixes surveys cache

apps/formbricks-com/components/shared/PricingTable.tsx
fix: Pricing Table on formbricks-com
=> fix: Pricing Table on formbricks-com

apps/formbricks-com/pages/pricing.tsx
chore: add special deal to pricing
=> chore: add special deal to pricing

apps/formbricks-com/pages/pricing.tsx
=> fix: pricing table dark mode

apps/web/app/(app)/environments/[environmentId]/integrations/page.tsx, apps/web/app/(app)/environments/[environmentId]/integrations/webhooks/components/WebhookSettingsTab.tsx
=> fix: Getting page not found error for DOC #1539

packages/lib/response/service.ts, packages/lib/team/service.ts
fix: team response count calculation
=> fix: team response count calculation

apps/formbricks-com/pages/pricing.tsx, apps/web/app/(app)/environments/[environmentId]/settings/billing/components/PricingTable.tsx
chore: remove limited launch deal from pricing
=> chore: remove limited launch deal from pricing

apps/formbricks-com/pages/pricing.tsx
=> fix: fix build on lp

apps/formbricks-com/pages/blog/preseed-announcement/index.mdx
=> add month to preseed

packages/surveys/src/lib/logicEvaluator.ts
Cause
When a user skips an open text question, its response value is `undefined`
But as you can see here, we dont handle the case when response value is undefined and hence it was returning false and due to which logic was failing
- Test A
- Test B
=> fix: skip logic

apps/web/app/api/cron/report-usage/route.ts, apps/web/app/api/v1/js/actions/route.ts, apps/web/app/api/v1/js/people/[personId]/set-user-id/route.ts, apps/web/app/api/v1/js/sync/route.ts
chore: improve client api error responses
=> chore: improve client api error responses

apps/web/app/(app)/environments/[environmentId]/settings/setup/components/SetupInstructions.tsx
https://discord.com/channels/979077669410979880/1011351796507213874/1170015301837000704
- Test A
- Test B
=> fix: link to Check out the docs is broken

apps/web/app/(app)/environments/[environmentId]/settings/product/components/DeleteProductRender.tsx
Fixed: Delete button is not disabled when clicking once
Fixes #1519
Screenshot of the Loading button state
- Test A - Tested by creating few new products and then deleting
- Test B
=> fix : delete btn is not disabling when clicking #1519

apps/formbricks-com/pages/api/oss-friends/index.ts
Adds Unkey to OSS Friends API
N/A
Verify that Unkey is returned from the oss-friends API
=> feat: Add Unkey to OSS Friends

.github/workflows/release-docker-github.yml
chore: Add docker packages to Github Packages on release
=> chore: Add docker packages to Github Packages on release

apps/formbricks-com/app/docs/self-hosting/deployment/page.mdx
Adds the Required Hardware configuration to self host Formbricks and run it with decent loadtimes.
=> feat: recommended hardware requirements to self host formbricks

packages/js/package.json
chore: release formbricks-js 1.1.5
=> chore: release formbricks-js 1.1.5

packages/ee/lib/service.ts, packages/lib/constants.ts
- The same method was present inside the `ee/` package as well and it made more sense to keep it there than in the constants file to avoid importing caching and etc here.
- The env is now only imported in the constants file like the rest of the project and the constant is now imported wherever needed.
=> chore: remove unused method and restructure env var fetching for team roles

apps/formbricks-com/app/docs/attributes/identify-users/page.mdx
=> docs: userId typo in docs

packages/lib/authOptions.ts
…gnin callback of authOptions.ts
Fixes #1610
The issue was due to an outdated prisma.user.create invocation in signin callback of authOptions. The model EventClass was replaced with ActionClass in the #1470 , but the mentioned invocation still had eventClasses instead of actionClasses in the body.
- Test if an unregistered user can now register using providers other than credentials (github/google)
=> fix: #1610

packages/surveys/src/components/OpenTextQuestion.tsx
Also fixes an issue where, user was able to submit empty fields with Enter button even when question is required
check autofocus in open text
=> fix: auto focus issue

packages/surveys/src/components/OpenTextQuestion.tsx
=> fix: survey editor issue

packages/surveys/src/lib/logicEvaluator.ts
=> fix: logic jumps

packages/ui/SingleResponseCard/index.tsx
Currently if you hover over delete button in single response card for responses which are not completed but still older then 5 minutes, you see a tooltip "submission in progress" and cursor changes to not allowed, while is not the expected behaviour
Test uncompleted responses older than 5 minutes
=> fix: response delete in single response card

apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/summary/actions.ts, apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/summary/components/ShareEmbedSurvey.tsx, apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/summary/components/shareEmbedTabs/EmailTab.tsx, apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/summary/lib/emailTemplate.tsx
Fixes #1606
This PR moves the logic for React Email to the server and queries the data using a server action. This way we can reduce the bundle size a lot since react email is no longer needed in the client plus we solve the problem of the app freezing while switching tabs because of the computation required by React email.
=> feat: load react email serverside

apps/formbricks-com/components/shared/MetaInformation.tsx
=> fix: add canonical URL for lp

apps/web/app/(app)/environments/[environmentId]/settings/lookandfeel/components/EditBranding.tsx
Fixes [1487](https://linear.app/formbricks/issue/FOR-1487/bug-wording)
- Test A
- Test B
=> fix: wording on look & feel page

packages/lib/person/service.ts
fix: caching issue by simplifying person service
=> fix: caching issue by simplifying person service

packages/surveys/src/components/general/Headline.tsx
This PR centers the thank you card title.
- The horizontal alignment of thank you card title needs to be tested.
=> fix: thank you card headline issue FOR-1489

packages/surveys/src/components/general/Headline.tsx, packages/surveys/src/components/general/ThankYouCard.tsx
Fixed Headline alignment
- Headline alignment needs to be tested horizontally
=> fix: headline alignment issue

apps/formbricks-com/app/docs/api/management/surveys/page.mdx, apps/formbricks-com/components/dummyUI/templates.ts, apps/web/app/(app)/environments/[environmentId]/surveys/templates/templates.ts
Made a small correction in the typo in the preview section.
fix: [fixed the typo in the preview section] #1642 
- Test A
- Test B
=> fix: typo in template

packages/lib/person/auth.ts, packages/lib/person/cache.ts, packages/lib/person/service.ts
fix: personByUserId not cached properly
=> fix: personByUserId not cached properly

packages/lib/person/service.ts
chore: simplify getPersonByUserId by removing legacy person support
=> chore: simplify getPersonByUserId by removing legacy person support

apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/components/SurveyEditor.tsx, apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/components/WhenToSendCard.tsx
Actually whenever a user adds a new actionClass, survey which is passed as a prop to survey editor is refetched, which further resets the localSurvey as there is a useEffect that runs whenever survey changes and all the progress gets lost. But we dont really need to update the survey there, we already do it in `WhenToSendCard.tsx`
Fixes [1479](https://linear.app/formbricks/issue/FOR-1479/changes-get-lost-in-survey-editor-after-adding-an-action)
Try creating a new action in survey editor
=> fix: page refresh issue on adding new action

.github/workflows/release-docker-github.yml, packages/js/src/lib/initialize.ts, packages/js/src/lib/person.ts
fix: close formbricks-js surveys on logout
=> fix: close formbricks-js surveys on logout

apps/formbricks-com/app/docs/api/client/displays/page.mdx, packages/types/displays.ts
- Bug Fix in Updating a Display (usedId does not need to be a `cuid` type anymore since we accept userId). this bug was causing to not updating the display and throwing an error
- Updated Documentation for `/v1/client/<env-id>/displays` endpoints
- Removed documentation for legacy endpoints
=> feat: updated client display endpoint docs & update display bug fix

apps/formbricks-com/app/docs/api/client/actions/page.mdx, apps/formbricks-com/components/docs/Navigation.tsx
Adds documentation for the new Action endpoint in the client API
=> feat: new client actions endpoint docs

apps/formbricks-com/pages/privacy-policy.mdx
chore: Add sentry to privacy policy
=> chore: Add sentry to privacy policy

apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/layout.tsx, apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/page.tsx
Added survey name in metadata title
#1668 
Navigating to diffrent surveys
=> fix: survey meta data title added

packages/js/vite.config.js
This PR adds the functionality to build a pixel as an Immediately Invoked Function Expression (IIFE), aiming to improve compatibility and resolve specific issues related to other forms of build formats. This change enhances the compatibility of the pixel across various environments and avoids namespace pollution.
Build js pixel via `pnpm turbo run build --filter=js...` and add the iife pixel to different websites that use react, vue, angular, ...
=> chore: add iife support

apps/formbricks-com/app/docs/api/management/surveys/page.mdx, apps/web/app/api/v1/management/surveys/[surveyId]/route.ts
- Add missing docs for update survey endpoint
- Endpoint now accept partial fields in update survey api endpoint instead of the whole survey object
Hit the survey API endpoint and test, also visible in the docs
=> fix: add missing docs for update survey endpoint

packages/surveys/src/components/general/AddedImage.tsx, packages/surveys/src/components/general/QuestionImage.tsx, packages/surveys/src/components/questions/CTAQuestion.tsx, packages/surveys/src/components/questions/ConsentQuestion.tsx, packages/surveys/src/components/questions/MultipleChoiceMultiQuestion.tsx, packages/surveys/src/components/questions/MultipleChoiceSingleQuestion.tsx, packages/surveys/src/components/questions/NPSQuestion.tsx, packages/surveys/src/components/questions/OpenTextQuestion.tsx, packages/surveys/src/components/questions/PictureSelectionQuestion.tsx, packages/surveys/src/components/questions/RatingQuestion.tsx
refactor for DRY code, UI tweak
=> fix: added images as reusable component, tweaked rating

apps/web/app/s/[surveyId]/components/VerifyEmail.tsx
fix: verify email screen responsiveness
=> fix: verify email screen responsiveness

apps/web/app/api/internal/excel-conversion/route.ts
=> fix: excel conversion

apps/web/app/(app)/environments/[environmentId]/settings/layout.tsx
=> fix: longer team names now do not cut pricing page sub components

packages/lib/constants.ts
Increase rate limits keeping in mind organisations/universities who have 1 public IP for multiple internal devices!
=> fix: increase rate limiting for auth endpoints

apps/formbricks-com/app/docs/api/client/overview/page.mdx, apps/formbricks-com/app/docs/best-practices/docs-feedback/page.mdx, apps/formbricks-com/app/docs/integrations/make/page.mdx, apps/formbricks-com/app/docs/integrations/n8n/page.mdx, apps/formbricks-com/app/docs/integrations/zapier/page.mdx
Fixes [1493](https://linear.app/formbricks/issue/FOR-1493/seo-fix-broken-links)
There were three broken links 
https://formbricks.com//docs/api/api-key-setup
https://formbricks.com//docs/client-api/create-response
https://formbricks.com//docs/client-api/update-response
which are now replaced with
https://formbricks.com/docs/api/management/api-key-setup
https://formbricks.com/docs/api/client/responses#create-a-response
https://formbricks.com/docs/api/client/responses#update-a-response
Also fixes numbering in https://formbricks.com/docs/best-practices/docs-feedback
From
To
Check docs
=> fix: broken links

apps/formbricks-com/app/docs/api/client/responses/page.mdx
Updates the Documentation for Client Response API endpoints
- Test A
- Test B
=> feat: updated client response endpoint docs

packages/ui/Editor/components/ToolbarPlugin.tsx
=> fix: editor adding paragraphs at the top on every render

apps/web/app/(app)/environments/[environmentId]/settings/api-keys/components/EditApiKeys.tsx
Fixes [1494](https://linear.app/formbricks/issue/FOR-1494/add-copy-option-to-api-keys)
https://github.com/formbricks/formbricks/assets/67850763/0bd869fb-6916-4e21-a259-94b37d65eec9
Create a new API key
Click on copy button
=> chore: added copy icon to api keys

.github/workflows/release-docker-github.yml, apps/web/next.config.mjs
fix: docker deployment failed because of new nextjs config
=> fix: docker deployment failed because of new nextjs config

.github/workflows/release-docker-github.yml, apps/web/next.config.mjs
fix: fix docker build action for github packages
=> fix: fix docker build action for github packages

apps/web/app/s/[surveyId]/page.tsx
Adds the Page Title as the Survey name for Link Surveys!
Fixes #1668 
Create a Lin Survey and open it, you should see the survey name in the header!
=> fix: link survey page title now has survey name

packages/ui/SingleResponseCard/components/QuestionSkip.tsx, packages/ui/SingleResponseCard/index.tsx
Fixes [1482](https://linear.app/formbricks/issue/FOR-1482/update-single-response-card)
Take a survey with welcome card
=> chore: added symbol for welcome card

apps/formbricks-com/app/docs/self-hosting/docker/page.mdx, apps/formbricks-com/app/docs/self-hosting/external-auth-providers/page.mdx, apps/formbricks-com/app/docs/self-hosting/production/page.mdx, apps/formbricks-com/components/docs/Navigation.tsx
Rename Self Hosting Section and Headings
- Test A
- Test B
=> fix: rename entire self hosting section

apps/formbricks-com/app/docs/api/client/actions/page.mdx, apps/formbricks-com/app/docs/api/client/displays/page.mdx, apps/formbricks-com/app/docs/api/client/people/page.mdx, apps/formbricks-com/app/docs/api/client/responses/page.mdx, apps/web/app/api/v1/client/[environmentId]/displays/route.ts, apps/web/app/api/v1/client/[environmentId]/people/route.ts
- Updates the Client API Responses and Request Objects as per the latest changes
- Updates the create person endpoint
=> feat: update client api docs as per new responses

packages/surveys/src/components/general/Survey.tsx
Fixes [1515](https://linear.app/formbricks/issue/FOR-1515/when-hidden-fields-is-selected-survey-preview-shouldnt-change)
https://github.com/formbricks/formbricks/assets/67850763/ce145b9c-e9ea-4181-b2ab-601055a22d1c
- Test A
- Test B
=> fix: avoid hidden field preview

apps/formbricks-com/app/docs/self-hosting/production/page.mdx, docker/production.sh
The current prod script only allowed a user to install the formbricks instance and its dependent containers and run them. We faced issues in our Discord about how they can update to the latest version w this!
To support that and more, we now support the following:
- Install (default)
- Uninstall (Removes the containers, directories, data, everything [asks for a confirmation from user])
- Update (updates the container to the pinned latest versions)
- Stop (stops the current instances)
- Restart (restarts the docker containers with the same config)
Run any of the command with the new script 🤞🏼
=> feat: prod script now supports update, delete, uninstall, stop, restart

apps/web/app/(auth)/auth/login/components/SigninForm.tsx, apps/web/app/(auth)/auth/verification-requested/page.tsx
We already converted emails to lowercase during signup
But the logic was missing for signin
Also added it on email verification page
Fixes [1517](https://linear.app/formbricks/issue/FOR-1517/fix-lowercase-email-in-signupsignin-before-processing)
Try signup/signin using Uppercase emails
=> chore: adds check for lowercase emails

apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/components/HiddenFieldsCard.tsx, apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/components/UpdateQuestionId.tsx
Fixes [1480](https://linear.app/formbricks/issue/FOR-1480/blacklist-welcomecard-as-questionid-and-hiddenfield)
Blacklisted "end", "start", "welcomeCard", "hidden" from questionIds
"end", "start", "welcomeCard" form hidden field names
- Test A
- Test B
=> chore: blacklisted questionIds

packages/surveys/postcss.config.js, packages/surveys/src/styles/global.css
=> fix: surveys package tailwind styles

apps/web/package.json, packages/js/package.json
=> chore: prepare 1.3.3 release

apps/web/app/api/internal/csv-conversion/route.ts, apps/web/app/api/internal/excel-conversion/route.ts
=> fix: fixes encoding of file name

packages/api/.eslintrc.cjs, packages/api/package.json, packages/js/.eslintrc.cjs, packages/js/package.json, packages/surveys/.eslintrc.cjs, packages/surveys/package.json, pnpm-lock.yaml
Fixes [1451](https://linear.app/formbricks/issue/FOR-1451/update-eslint-rules-for-packages)
- Test A
- Test B
=> chore: added individual eslints

.github/workflows/release-docker-github.yml, apps/web/Dockerfile
chore: use node 20 in dockerfiles
=> chore: use node 20 in dockerfiles

apps/formbricks-com/components/docs/docsFaq.tsx, apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/components/QuestionCard.tsx
- Increases font size of "Advanced Settings" in Question Card
- Adds FaQ item for customising button text
- Test A
- Test B
=> fix: add docs + increase size about increasing size of changing button text

packages/lib/constants.ts
fix: increase rate limit for client endpoints
=> fix: increase rate limit for client endpoints

apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/components/SurveyMenuBar.tsx
Fixes [1528](https://linear.app/formbricks/issue/FOR-1528/fix-survey-cannot-be-saved-with-empty-filter)
Add an empty attribute filter
Try to save the survey
=> fix: eliminate empty attribute filter

apps/formbricks-com/app/docs/self-hosting/migration-guide/page.mdx, docker-compose.yml, docker/docker-compose.yml
Since ASSET_PREFIX_URL is only a build time variable, we cannot allow users to set it at runtime, hence removing the option provided to users
- Test A
- Test B
=> fix: remove configuration option for asset prefix URL

apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/summary/components/SummaryMetadata.tsx, packages/lib/response/service.ts, packages/types/responses.ts
Fixes `Response not created bug`
- Test A
- Test B
=> fix: made ttc and userAgent optional

packages/lib/survey/service.ts
fix: in-app surveys not pulled correctly when user attributes get set
=> fix: in-app surveys not pulled correctly when user attributes get set

packages/lib/survey/service.ts
fix: remove person validation in syncSurveys for backwards compatibility
=> fix: remove person validation in syncSurveys for backwards compatibility

.github/workflows/cron-reportUsageToStripe.yml
fix: let report usage cron run with no-cache headers
=> fix: let report usage cron run with no-cache headers

apps/formbricks-com/app/docs/api/client/overview/page.mdx, apps/formbricks-com/app/docs/introduction/what-is-formbricks/page.mdx
=> docs: minor docs hygiene

apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/components/StylingCard.tsx
- Open the settings tab of the survey editor
- Overwrite the placement, select center modal but leave the rest to the default options
=> fix: adds default values for overlay and click outside close

packages/lib/profile/service.ts, packages/lib/profile/util.ts, packages/lib/response/util.ts, packages/types/responses.ts
fix #1741
- create a new user
- go through onboarding but skip every step (`I'll do it later`)
=> fix: onboarding ending in endless loop because of validation error

apps/formbricks-com/components/home/Hero.tsx
=> fix: landing page title typo

apps/demo/pages/app/index.tsx, apps/formbricks-com/app/docs/attributes/custom-attributes/page.mdx, apps/formbricks-com/app/docs/attributes/identify-users/page.mdx, packages/js/package.json, packages/js/src/lib/config.ts, packages/js/src/lib/initialize.ts, packages/js/src/lib/person.ts, packages/types/js.ts
=> feat: attributes on initialising formbricks

apps/web/app/s/[surveyId]/components/MediaBackground.tsx, apps/web/next.config.mjs
1. File doesnt get uploaded when using gitpod as the hostname is dynamic and needs to be added in the `next.config.mjs` file for it be be considered as a trusted source
2. Bg overlay doesnt work whenever the brightness is increased or decreased
This pr fixes above two
After changes:
Test A - Upload any file anywhere while using the gitpod  dev environment
Test B - Change to any multi media background and play with the bg overlay
=> fix: Gitpod file upload and background overlay

apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/components/SurveyMenuBar.tsx
Fixes [1546](https://linear.app/formbricks/issue/FOR-1546/fix-ui-for-editor-warning-on-smaller-screens)
https://github.com/formbricks/formbricks/assets/67850763/728efc3d-eb7b-4aad-a7c3-62ab977b0b13
Check survey editor on small size
=> fix: Survey editor caution text fix

.github/workflows/release-docker-github.yml, apps/web/Dockerfile, apps/web/next.config.mjs
fix: docker image not build correctly for arm
=> fix: docker build errors

packages/surveys/package.json, packages/surveys/src/components/questions/DateQuestion.tsx
chore: update surveys package to 1.0.1
=> chore: update surveys package to 1.0.1

apps/web/vercel.json
Fixes [1549](https://linear.app/formbricks/issue/FOR-1549/weekly-summary-failing-because-of-timeout)
- Test A
- Test B
=> fix: changed maxDuration for weekly summary endpoint
